Issue 1556
maxi-blocks/maxi-blocks pull request #1565
Opened 2021-06-02 05:31 UTC by javadsamiee

Add Width/Height for Group Maxi

2021-06-02 05:54 UTC, Alejandro9kgm approved these changes

2021-06-02 07:35 UTC, Naaaaiix reviewed
<img width="1911" alt="Captura de pantalla 2021-06-02 a las 9 32 21" src="https://user-images.githubusercontent.com/50477222/120442392-d8c83c00-c385-11eb-8c09-ac57249f0ca5.png">

2021-06-02 10:29 UTC, Naaaaiix reviewed
https://user-images.githubusercontent.com/50477222/120465310-1f299500-c39e-11eb-90d1-df1cb28d33cf.mp4

2021-06-09 08:27 UTC, Naaaaiix requested changes
Let's hide max-width when is fullwidth 👍 


https://user-images.githubusercontent.com/50477222/121320142-2b1cd600-c90d-11eb-8dd6-453169ff1ce5.mp4

2021-06-09 11:57 UTC, Naaaaiix approved these changes

2021-06-10 09:24 UTC, merged