New tests to add to components
maxi-blocks/maxi-blocks pull request #1618
Opened 2021-06-11 08:10 UTC by Alejandro9kgm

The added tests are :
arrow-displayer,
breadcrumbs,
default-styles-control,
indicators,
responsive-control,
setting-tabs-control,

2021-06-11 08:34 UTC, javadsamiee reviewed
![image](https://user-images.githubusercontent.com/65819265/121657322-8d183f80-cab5-11eb-8327-6447a80b0440.png)

2021-06-11 08:53 UTC, javadsamiee approved these changes

2021-06-14 07:25 UTC, Naaaaiix requested changes
Well, there are some tests that need to be redone, you'll find on the comments.

Some other global things:
1. Please, capitalize the titles and descriptions
2. The titles, being components, should keep the component name; for example: ArrowDisplayer or SettingTabsControl, and not Arrow Display.
3. Couldn't find ShapeControl test as has been listed on the description

Also, please, update the branch with master in order to have the last version 👍

2021-06-16 08:47 UTC, Naaaaiix reviewed
Well done TestMaster! 🐵 😄

2021-06-17 08:29 UTC, Naaaaiix approved these changes

2021-06-17 11:18 UTC, javadsamiee approved these changes

2021-06-17 11:27 UTC, merged