Issue 1682
maxi-blocks/maxi-blocks pull request #1740
Opened 2021-06-29 15:02 UTC by Naaaaiix

Fixes #1682 and #1265 . Some considerations:
1. Default color palette for 'active' and 'visited' has been set randomly as there's no indication on [this spreadsheet](https://docs.google.com/spreadsheets/d/18yHSXVRHlggTw_fVFu82kyNDFcCO9kMoyj1BtkcOzUA/edit#gid=0)
2. Just set on Text Maxi, but should be able to adapt to any other block without a problem

2021-06-30 08:04 UTC, elzadj requested changes

2021-06-30 12:54 UTC, elzadj requested changes
Not sure why we do not have the default color 5 for h1-h6 - now they always stay gray (well, color 3, same as 'p'). 
--maxi-light-h6-color-palette: var(--maxi-light-color-3);

Maybe we need a new issue for adding the default color numbers and checking them?

2021-06-30 14:12 UTC, elzadj approved these changes

2021-07-01 11:34 UTC, Alejandro9kgm approved these changes

2021-07-01 11:54 UTC, javadsamiee approved these changes
Good job 👍🏻

2021-07-01 11:54 UTC, merged