Issue 1859
maxi-blocks/maxi-blocks pull request #1863
Opened 2021-07-26 13:25 UTC by Naaaaiix

Fixes #1859

2021-07-26 13:28 UTC, javadsamiee approved these changes

2021-07-27 10:26 UTC, elzadj requested changes
Nice!

Looks like the custom border color on hover does not work (the palette color works fine):


https://user-images.githubusercontent.com/2401618/127139010-ecc57063-92bb-4544-8a24-4594d26b828f.mp4

2021-07-27 12:00 UTC, Alejandro9kgm approved these changes

2021-07-27 12:10 UTC, elzadj approved these changes

2021-07-28 08:10 UTC, merged