Issue 1881
maxi-blocks/maxi-blocks pull request #1928
Opened 2021-08-04 07:58 UTC by javadsamiee

2021-08-04 11:07 UTC, elzadj requested changes
https://github.com/yeahcan/maxi-blocks/pull/1928#issuecomment-892568852

2021-08-05 16:30 UTC, Naaaaiix approved these changes
Well done @javadsamiee , this one has been a tough one 💪

2021-08-06 14:13 UTC, elzadj requested changes
Great work @javadsamiee !

There is a bug with the icon alignment on frontend: 


https://user-images.githubusercontent.com/2401618/128523092-44acde46-365d-4f5c-b3c1-04deb32aeba5.mp4

And that setting made by brain explode :exploding_head: 

 
![Edit-Page-‹-Local-Wordpress-—-WordPress (20)](https://user-images.githubusercontent.com/2401618/128523250-3f0cb2ce-ffc9-478c-8228-e106ad7cb256.jpg)

Right on the left, left on the right.... 

![1j9mml](https://user-images.githubusercontent.com/2401618/128523510-f9e923fa-668e-431a-a0f8-6c92f383106c.jpg)

2021-08-09 07:09 UTC, Naaaaiix approved these changes

2021-08-09 07:37 UTC, elzadj approved these changes

2021-08-09 08:57 UTC, merged