Issue 1965
maxi-blocks/maxi-blocks pull request #1974
Opened 2021-08-12 16:43 UTC by Naaaaiix

Fixes #1965

2021-08-13 06:46 UTC, javadsamiee reviewed
Excellent work 👍🏻  I think it's better to have a reset for "Colour Opacity"

2021-08-13 06:51 UTC, javadsamiee approved these changes

2021-08-13 07:40 UTC, elzadj requested changes
I think we need to hide the palette's opacity when we use a Custom color. 
![Edit-Page-‹-Local-Wordpress-—-WordPress (35)](https://user-images.githubusercontent.com/2401618/129321954-54cc9d3e-6de8-4db8-ad98-5e74f0411904.jpg)

2021-08-13 09:40 UTC, elzadj requested changes
Thanks @Naaaaiix 

There is a bug with the Opacity number - first I cannot change it with keyboard, and then it breaks with

```
react-dom.js?ver=16.13.1:82 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
```


https://user-images.githubusercontent.com/2401618/129337691-d78f0d8a-fbd4-40e9-904c-a5083d7cadaa.mp4


[blocks.txt](https://github.com/yeahcan/maxi-blocks/files/6981428/blocks.txt)

2021-08-16 05:23 UTC, javadsamiee approved these changes

2021-08-17 10:47 UTC, merged