Issue 2153
maxi-blocks/maxi-blocks pull request #2156
Opened 2021-09-17 13:35 UTC by Naaaaiix

Fixes #2153 
Add new method `getColorRGBAParts`
Add tests for `getColorRGBAParts`
Update colours for dark on SC
Update tests

2021-09-20 06:13 UTC, Alejandro9kgm reviewed
The same bug happens if you use a button

https://user-images.githubusercontent.com/58038966/133962427-262ac7ac-5efb-45f9-9c73-d6f3f5f000b1.mp4

2021-09-20 07:39 UTC, elzadj requested changes
> The same bug happens if you use a button

I confirm, the error for the Text Block is:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'p')
    at getTypographyFromSC (index.js:104936)
    at getCustomFormatValue (index.js:122495)
    at getValue (index.js:98153)
    at index.js:98323
    at renderWithHooks (react-dom.js:14938)
    at mountIndeterminateComponent (react-dom.js:17617)
    at beginWork (react-dom.js:18731)
    at HTMLUnknownElement.callCallback (react-dom.js:182)
    at Object.invokeGuardedCallbackDev (react-dom.js:231)
    at invokeGuardedCallback (react-dom.js:286)
```

and for the Button Block:

```
getTypographyFromSC.js:16 Uncaught TypeError: Cannot read properties of undefined (reading 'button')
    at getTypographyFromSC (getTypographyFromSC.js:16)
    at getCustomFormatValue (getCustomFormatValue.js:84)
    at getValue (index.js:454)
    at index.js:635
    at renderWithHooks (react-dom.js?ver=16.13.1:14938)
    at mountIndeterminateComponent (react-dom.js?ver=16.13.1:17617)
    at beginWork (react-dom.js?ver=16.13.1:18731)
    at HTMLUnknownElement.callCallback (react-dom.js?ver=16.13.1:182)
    at Object.invokeGuardedCallbackDev (react-dom.js?ver=16.13.1:231)
    at invokeGuardedCallback (react-dom.js?ver=16.13.1:286)
```

2021-09-20 09:26 UTC, Alejandro9kgm approved these changes

2021-09-20 10:11 UTC, elzadj approved these changes

2021-09-20 10:13 UTC, javadsamiee approved these changes

2021-09-21 06:23 UTC, Alejandro9kgm approved these changes

2021-09-22 10:00 UTC, merged