Refactor MaxiModal
maxi-blocks/maxi-blocks pull request #2176
Opened 2021-09-24 11:33 UTC by Naaaaiix

Replaced dispatch action `updateBlockAttributes` for `onSelect` method which relays the responsibility of the attributes changed from the Modal on the block and not on the Modal itself.
Rewrite MaxiModal to be a functional component instead of class component.

What to test:
- All modal instances do the same they were doing before

2021-09-24 11:55 UTC, elzadj requested changes
New Block - Maxi Cloud Library - Load a pattern ==> 
```
Uncaught TypeError: onSelect is not a function
    at onRequestInsertPattern (container.js:222)
    at onRequestInsert (container.js:342)
    at HTMLUnknownElement.callCallback (react-dom.js?ver=16.13.1:182)
    at Object.invokeGuardedCallbackDev (react-dom.js?ver=16.13.1:231)
    at invokeGuardedCallback (react-dom.js?ver=16.13.1:286)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.js?ver=16.13.1:300)
    at executeDispatch (react-dom.js?ver=16.13.1:383)
    at executeDispatchesInOrder (react-dom.js?ver=16.13.1:408)
    at executeDispatchesAndRelease (react-dom.js?ver=16.13.1:3401)
    at executeDispatchesAndReleaseTopLevel (react-dom.js?ver=16.13.1:3410)
```

Everything else seems to work fine :+1:

2021-09-24 11:59 UTC, javadsamiee approved these changes

2021-09-27 06:32 UTC, Alejandro9kgm approved these changes

2021-09-27 07:32 UTC, elzadj approved these changes

2021-09-27 07:38 UTC, merged