Issue 2236
maxi-blocks/maxi-blocks pull request #2244
Opened 2021-10-23 10:08 UTC by Naaaaiix

Fixes #2236

2021-10-25 07:21 UTC, elzadj approved these changes

2021-10-25 07:22 UTC, elzadj requested changes
Repeated twice:

![Edit-Page-‹-Local-Wordpress-—-WordPress (58)](https://user-images.githubusercontent.com/2401618/138652115-437d2d84-1f1f-4ebc-8408-9ac40b9f4b9e.jpg)


And long shapes look weird on the preview (can be a new issue, no probs)

2021-10-25 10:02 UTC, elzadj requested changes
- A container's BG Shape disappears on hover by default (if not related - make a new issue pls): 

https://user-images.githubusercontent.com/2401618/138674957-2c0708ab-dfdb-4b07-92bf-dafc9c42033e.mp4

- Something weird- add a shape, change its colour, then try to change the colour to an image: 

https://user-images.githubusercontent.com/2401618/138675871-b505a73f-4667-495f-93f5-6c6e3ad7e554.mp4

The error in the console is 
```
utils.js:45 Uncaught TypeError: Cannot read properties of null (reading 'remove')
    at utils.js:45
    at Array.forEach (<anonymous>)
    at utils.js:42
    at Array.forEach (<anonymous>)
    at injectImgSVG (utils.js:41)
    at callback (index.js:173)
    at onClick (index.js:70)
    at HTMLUnknownElement.callCallback (react-dom.js?ver=16.13.1:182)
    at Object.invokeGuardedCallbackDev (react-dom.js?ver=16.13.1:231)
    at invokeGuardedCallback (react-dom.js?ver=16.13.1:286)
```

2021-10-25 12:09 UTC, elzadj approved these changes
Set an image in a bg shape, remove it, set another image:

https://user-images.githubusercontent.com/2401618/138692219-1edea21e-d1c7-46f6-8eb8-24170a02d7e4.mp4


if you click somewhere the editor, it starts working. Really weird one.No errors in the console too. Something with the state maybe? 

Can be a new issue too, no probs.

2021-10-26 08:10 UTC, Alejandro9kgm approved these changes

2021-10-26 13:16 UTC, javadsamiee approved these changes

2021-10-26 13:42 UTC, merged