Issue 2216
maxi-blocks/maxi-blocks pull request #2247
Opened 2021-10-25 10:25 UTC by Naaaaiix

Fixes #2216

2021-10-25 12:46 UTC, elzadj requested changes
Works great now, just one thing: we don't need ```figcaption``` on frontend when it's actually empty (it also adds an unwanted margin): 

![Screenshot from 2021-10-25 15-43-45](https://user-images.githubusercontent.com/2401618/138697492-d0c10fc2-166f-48ce-90cf-a698535e7740.png)

2021-10-26 07:50 UTC, elzadj requested changes
Thanks @Naaaaiix 

I think that if we allow setting up the Caption's setting before we add the image, we should show the Caption placeholder on backend, or we do not really see the changes we make:
![Edit-Page-‹-Local-Wordpress-—-WordPress (62)](https://user-images.githubusercontent.com/2401618/138831967-0e8672bf-6f7f-4949-b6b4-fc1024bb2523.jpg)

And a small thing - the alignment here is not right, it's centered by default: 
![Edit-Page-‹-Local-Wordpress-—-WordPress (61)](https://user-images.githubusercontent.com/2401618/138832082-82fd8750-ee6c-44b3-84e6-f6c67e055d22.jpg)

2021-10-26 09:22 UTC, elzadj approved these changes

2021-10-26 13:12 UTC, javadsamiee approved these changes

2021-10-26 13:42 UTC, merged