Issue I2078
maxi-blocks/maxi-blocks pull request #2275
Opened 2021-10-29 11:23 UTC by Naaaaiix

Fixes #2078

2021-10-29 14:46 UTC, elzadj requested changes
'Show Percentage Sign' does not work, 'Hide Circle' hides everything: 

https://user-images.githubusercontent.com/2401618/139455322-43144dbb-dfab-4b76-a7f1-fbe513e0acdb.mp4

Both options are ok on master.

2021-11-01 09:47 UTC, elzadj requested changes
-  I'm getting 
``` 
Uncaught TypeError: Cannot set properties of null (setting 'innerHTML')
    at front-scripts.js?ver=5.8:178
``` 
on frontend, here is the blocks' code to re-create:  
[number-counter-frontend-js-error.txt](https://github.com/yeahcan/maxi-blocks/files/7452206/number-counter-frontend-js-error.txt
)

https://user-images.githubusercontent.com/2401618/139653126-f3c7f5c9-edf3-43fd-b5b0-daed7fb73b73.mp4

- Let's hide the circle's settings when it's disabled: 

![Edit-Page-‹-Local-Wordpress-—-WordPress (65)](https://user-images.githubusercontent.com/2401618/139653259-ec7fe155-8407-4be7-959e-e9ebb36a404c.jpg)

2021-11-03 07:04 UTC, Alejandro9kgm approved these changes

2021-11-03 08:39 UTC, elzadj requested changes
Almost there!

- Please hide the message when the end number is ok:
![Add-New-Page-‹-Local-Wordpress-—-WordPress (1)](https://user-images.githubusercontent.com/2401618/140028887-391270e9-bd65-409b-ab47-c136a928f830.jpg)

- Please hide the Stroke setting when the circle is hidden:
![Add-New-Page-‹-Local-Wordpress-—-WordPress](https://user-images.githubusercontent.com/2401618/140028955-bf4f544a-cb3c-4da8-bbf7-0eec397d0b4e.jpg)

- The custom colour for text is not working, it's the same on our master, so a new issue is ok:

https://user-images.githubusercontent.com/2401618/140029509-81b7e9c1-353f-45f0-be65-7b036f002438.mp4

- Title Font Size does not go below 32. That's weird. Again, same on master, so you can make a new issue.
- Opacity for all Circle Colours does not work, same as on master.

2021-11-03 09:41 UTC, elzadj approved these changes

2021-11-03 09:48 UTC, merged