Issue 2259
maxi-blocks/maxi-blocks pull request #2278
Opened 2021-10-29 15:46 UTC by Naaaaiix

Fixes #2259

Set a 100 as `%` max-width for SVG Icon Maxi block. Not sure about if is a good plan, what do you think?

2021-11-01 08:37 UTC, elzadj requested changes
I'm getting 
```
WARNING in ./src/blocks/svg-icon-maxi/styles.js 101:5-17
"export 'getSvgStyles' was not found in '../../extensions/styles/helpers'
 @ ./src/blocks/svg-icon-maxi/edit.js
 @ ./src/blocks/svg-icon-maxi/svg-icon-maxi.js
 @ ./src/index.js
```

And the SVG block crashes. Looks like there is a confusion with 'getSvgStyles' and 'getSVGWidthStyles'.

2021-11-02 10:47 UTC, javadsamiee reviewed
I see src/blocks/svg-icon-maxi/editor.scss and src/blocks/svg-icon-maxi/style.scss have not correct CSS organization and also colors should use backend color variables.

2021-11-02 12:13 UTC, Naaaaiix reviewed
> I see src/blocks/svg-icon-maxi/editor.scss and src/blocks/svg-icon-maxi/style.scss have not correct CSS organization and also colors should use backend color variables.

Didn't touch that files more than to move existing code 👍

2021-11-02 12:25 UTC, javadsamiee approved these changes

2021-11-03 07:22 UTC, Alejandro9kgm approved these changes

2021-11-03 07:58 UTC, merged