Issue 2317
maxi-blocks/maxi-blocks pull request #2318
Opened 2021-11-09 14:53 UTC by Naaaaiix

Fixes #2317

2021-11-10 09:08 UTC, javadsamiee reviewed
I think after reset it should be returned to 100 not remain in current value, now the color resets but the opacity value remains.

2021-11-10 09:31 UTC, elzadj requested changes
Now the reset button does not do anything.

2021-11-11 10:53 UTC, elzadj approved these changes

2021-11-11 12:12 UTC, javadsamiee approved these changes

2021-11-11 13:03 UTC, merged