#2342 Fix height everywhere
maxi-blocks/maxi-blocks pull request #2348
Opened 2021-11-22 13:33 UTC by Marko64

Fixes #2342 

Removed the following option:
![removed-height](https://user-images.githubusercontent.com/19425503/142870178-ab529d76-9538-4d5a-bd1a-acad89632f7c.jpg)

2021-11-22 16:39 UTC, Naaaaiix reviewed
There's a good and a bad new:
1. The good one: you've made your first PR, your first implementation and is everything perfectly good! 😌 Congrats, you're in the game 🤾‍♂️ 
2. The bad one: the solution wasn't the one wrote up on the issue 😅 removing wasn't the real solution, as it was failing for another reason:

https://user-images.githubusercontent.com/50477222/142900062-01cf9941-280f-4b0a-ae0c-26f539df1165.mp4

As you can see the real error is related with the height unit. So, let's keep playing 🏀 👍

2021-12-08 10:54 UTC, elzadj requested changes
Aha, understood @Naaaaiix , thanks.

I can't change the unit, and the component breaks after (also: 22.22 px :smile_cat: ):
![Edit-Page-‹-Local-Wordpress-—-WordPress (89)](https://user-images.githubusercontent.com/2401618/145196446-cc70fb12-480b-4eb1-b47c-fe2299062a3f.jpg)

2021-12-08 12:04 UTC, elzadj approved these changes
Works, thanks @Naaaaiix 

The setting is not responsive tho - I guess we need it? @kyrapieterse ?

Can be a new issue if we need it.

2021-12-08 15:30 UTC, elzadj approved these changes

2021-12-09 07:41 UTC, Alejandro9kgm approved these changes

2021-12-09 07:56 UTC, merged