Issue 2232 Added Custom CSS tab
maxi-blocks/maxi-blocks pull request #2379
Opened 2021-11-30 15:40 UTC by Marko64

Fixes #2232 
- Added Custom CSS tab for all existing blocks
- Fixed getCategoriesCss() function to show custom CSS for options that exist. It was inverted.

2021-11-30 17:35 UTC, Naaaaiix reviewed
Very good, in terms of code looks fantastic. Also have to say @elzadj left it really easy 😜 

Apart of the comments left on code, couple of points:
1. May we should decide if we should put `:before` or `::before`; I prefer second option which corresponds to CSS 3 version.
2. I suspect @Marko64 and possibly @Rustam198804 are not working on a VSC environment with Prettier, Beautify and ESLint. We may do a document with the musts we need and the optional VSC extensions 👍

2021-12-01 11:18 UTC, elzadj requested changes
Text Block and some other blocks do not have Canvas, so the labels must be 'Before text', 'After text', 'Custom CSS for text ::before' etc., not '... canvas':
![Edit-Page-‹-Local-Wordpress-—-WordPress (84)](https://user-images.githubusercontent.com/2401618/144225198-27559a36-fef9-45ab-ac70-8205f5e541b0.jpg)

2021-12-01 13:32 UTC, elzadj approved these changes
Found 2 typos in Text, everything else is great, thank you @Marko64

2021-12-01 13:50 UTC, elzadj approved these changes

2021-12-01 14:50 UTC, Alejandro9kgm approved these changes

2021-12-01 15:53 UTC, merged