Issue 2466 - Palette colour SVG on list markers
maxi-blocks/maxi-blocks pull request #2494
Opened 2022-01-21 16:11 UTC by Naaaaiix

Fixes #2466 

Includes:
1. Automatic change of SVG icon content when changing the colour presets on SC on the editor.
2. Automatic update of the SC variable colours when rendering on frontend, which also updates SVG icon markers colour.
3. Added colour option for any type of list marker
4. Fixed reverse order error with custom ordered types
5. Fixed unordered list marker styles (was just showing disk)

Some notes:
1. Tests will be needed, @Alejandro9kgm set on your list onces this branch will be merge.
2. The current available icons for the list are the image shape ones; may we need a new category for list markers? @kyrapieterse @elzadj  what do you think?

2022-01-26 11:19 UTC, Alejandro9kgm approved these changes

2022-01-27 09:52 UTC, kyrapieterse approved these changes
APPPPPPPPPPPPPPPROVED!!!!!

2022-01-27 10:48 UTC, elzadj requested changes
Great work! Just some minor bugs to fix.

The custom colour for svg resets when I change the icon:

https://user-images.githubusercontent.com/2401618/151344244-8da3f09d-df18-4d5c-b6cd-e549aca2b5e4.mp4

2022-01-28 15:13 UTC, Alejandro9kgm approved these changes

2022-01-28 15:49 UTC, elzadj approved these changes
Everything is great, one note: the 'start from' acts kinda weird - if I start from 0, the first number must be 0, not 1. If I start from 1, the first one must be 1, not 2, etc.:

https://user-images.githubusercontent.com/2401618/151577878-14363e0a-2bc6-4cb7-896f-fafb31801db0.mp4

2022-02-03 09:40 UTC, Alejandro9kgm approved these changes

2022-02-03 10:42 UTC, merged