Issue-2446 Keep settings open to last use
maxi-blocks/maxi-blocks pull request #2502
Opened 2022-01-25 10:55 UTC by bilouStrike

Fixe #2446

2022-01-25 16:11 UTC, Naaaaiix reviewed
https://user-images.githubusercontent.com/50477222/151014597-aca318dd-ef69-4fe2-921a-913a49803f1e.mp4

Onces fixed the commented issues we can have a look at the tests 👍

2022-02-01 15:45 UTC, Naaaaiix requested changes
Good job! 👏 there are lots of comments, but most of them are small small small things that are just necessary to keep the concordance and the clean code, but the implementation works really good and is really solid. Congrats 🥳 

Some other things found:
1. Group Maxi returned this error 👍 To reproduce, create a Group Maxi, click outside, click on it again and voilá: 
<img width="530" alt="Captura de pantalla 2022-02-01 a las 16 18 21" src="https://user-images.githubusercontent.com/50477222/151996146-6bd89b8c-1600-4df7-917b-354f561b93ee.png">

2. Please, replace all `accordiont` for `accordion`; without the last 't'

2022-02-02 15:45 UTC, elzadj approved these changes

2022-02-04 11:13 UTC, Naaaaiix approved these changes

2022-02-04 11:47 UTC, Alejandro9kgm approved these changes

2022-02-04 12:06 UTC, merged