Fix responsive menu styles
maxi-blocks/maxi-blocks pull request #2537
Opened 2022-02-07 12:57 UTC by Rustam198804

Fixed responsive menu

2022-02-09 09:29 UTC, kyrapieterse approved these changes

2022-02-09 14:28 UTC, elzadj requested changes

2022-02-09 15:58 UTC, elzadj approved these changes

2022-02-10 15:17 UTC, Naaaaiix reviewed
Good job, looks fantastic! 😸 

Couple of comments:
1. Finding lots of "Invalid DOM property `stroke-linecap`. Did you mean `strokeLinecap`?" errors, would be good to fix them please @Rustam198804 .
2. Found much places where the styling standards commented on [this wiki](https://github.com/yeahcan/maxi-blocks/wiki/Styling-convention#order) like:
https://github.com/yeahcan/maxi-blocks/blob/92b5c0e416ae4c50acc39b243d15c43d41d6019f/src/editor/responsive-selector/editor.scss#L54-L70

2022-02-11 07:20 UTC, Alejandro9kgm approved these changes

2022-02-15 10:03 UTC, kyrapieterse approved these changes
Ok good enough for now....  lets merge this

2022-02-15 10:12 UTC, elzadj approved these changes
Looks good, thanks @Rustam198804 

I'm thinking if we should fix it for 500 px and down to 320 - it's not hard to just make it all smaller:
![Edit Page “Untitled” ‹ Local Wordpress — WordPress (3)](https://user-images.githubusercontent.com/2401618/154040454-7a997011-ec18-43c1-b9f3-bd9ab34f6b8b.jpg)

@kyrapieterse what do you think?

2022-02-15 15:19 UTC, Naaaaiix approved these changes

2022-02-15 15:21 UTC, merged