issue-2442 Button maxi shortcuts
maxi-blocks/maxi-blocks pull request #2538
Opened 2022-02-08 08:54 UTC by bilouStrike

Fixes #2442

2022-02-08 10:03 UTC, Naaaaiix approved these changes

2022-02-08 10:08 UTC, Naaaaiix requested changes

2022-02-08 16:38 UTC, Naaaaiix reviewed
In general is good, but look what happens when setting a border without a default: the border colour is the same than the background, which is really strange

https://user-images.githubusercontent.com/50477222/153033074-648240e5-c2b6-460d-a1ae-50a6f119644b.mp4

.

2022-02-10 15:39 UTC, Naaaaiix approved these changes
Please, update the tests 👍

2022-02-11 07:34 UTC, Alejandro9kgm approved these changes

2022-02-11 09:38 UTC, elzadj approved these changes

2022-02-11 09:50 UTC, merged