Issue 2504 - WP 5.9 support
maxi-blocks/maxi-blocks pull request #2540
Opened 2022-02-08 16:28 UTC by Naaaaiix

Fixes #2504

Update .wp-env.json file
Fixed inner-blocks
Fixed e2e utils
Fixed new responsive in iframe
Fixed placeholder z-index and block selector
Fixed minor errors related to WP 5.8
Replaced none camelCase 'accordion'

Important note:
To test, is necessary to update to WP 5.9 using a `wp-env start`. Onces finished with this PR, to come back to WP 5.8, change the branch to other under WP 5.8 and use same command again.

2022-02-09 14:01 UTC, elzadj requested changes
- can't scroll any of the modals (SVG, SCs, button icons)
- I see that error when I remove a button block (it's new, learndd does not have it)
```edit.js:54 Uncaught TypeError: Cannot read properties of null (reading 'ownerDocument')
    at edit.js:54:16
    at HTMLUnknownElement.callCallback (react-dom.js?ver=17.0.1:3942:16)
    at Object.invokeGuardedCallbackDev (react-dom.js?ver=17.0.1:3991:18)
    at invokeGuardedCallback (react-dom.js?ver=17.0.1:4053:33)
    at flushPassiveEffectsImpl (react-dom.js?ver=17.0.1:23573:13)
    at unstable_runWithPriority (react.js?ver=17.0.1:2942:14)
    at runWithPriority$1 (react-dom.js?ver=17.0.1:11306:12)
    at flushPassiveEffects (react-dom.js?ver=17.0.1:23477:16)
    at performSyncWorkOnRoot (react-dom.js?ver=17.0.1:22299:5)
    at react-dom.js?ver=17.0.1:11357:28
    ```

2022-02-11 08:40 UTC, Alejandro9kgm reviewed
minor bug in Maxi Cloud Library

https://user-images.githubusercontent.com/58038966/153560805-fa8e9cbe-d4e5-4326-ba3b-f5b68087fb12.mp4

2022-02-11 09:36 UTC, Alejandro9kgm approved these changes

2022-02-11 09:37 UTC, elzadj approved these changes
Greeeeeeat work!

2022-02-11 09:41 UTC, merged