Issue#2539 H6 line height from SC
maxi-blocks/maxi-blocks pull request #2548
Opened 2022-02-10 10:24 UTC by FitseTLT

#2539

2022-02-10 11:08 UTC, Naaaaiix requested changes
Dark object needs `"line-height-unit-xl"` also, just implemented on light.

File has been formatted different from the original one; this remain me the necessity of this issue => https://github.com/yeahcan/Maxi-feature-request/issues/47 . @elzadj should we prioritize it? 🤔

2022-02-10 14:43 UTC, Naaaaiix approved these changes

2022-02-11 07:25 UTC, Alejandro9kgm approved these changes

2022-02-11 09:41 UTC, elzadj approved these changes
:+1:

2022-02-11 09:45 UTC, merged