New grid
maxi-blocks/maxi-blocks pull request #2555
Opened 2022-02-10 15:53 UTC by Rustam198804

Change grid style

2022-02-18 10:08 UTC, kyrapieterse approved these changes

2022-02-18 11:51 UTC, Marko64 approved these changes

2022-02-22 09:26 UTC, FitseTLT approved these changes

2022-02-22 14:13 UTC, Naaaaiix requested changes
Some comments:
1. This padding is not going to exist in frontend; can't it be confusing for creators?
<img width="1121" alt="Captura de pantalla 2022-02-22 a las 14 58 23" src="https://user-images.githubusercontent.com/50477222/155147668-9bbab7bb-010d-4724-8fa9-b7abb87e5ad3.png">

2. Without the image link button, how can creators add links as images?
<img width="465" alt="Captura de pantalla 2022-02-22 a las 15 01 08" src="https://user-images.githubusercontent.com/50477222/155147706-8c4fccf9-4077-46f5-b699-5ac93262b189.png">

2022-02-25 10:41 UTC, Naaaaiix requested changes

2022-02-25 13:40 UTC, Naaaaiix approved these changes
Updated the tests. Please @Alejandro9kgm , onces this branch will be merged into master, we need to fix `e2e-tests/components/image-url/index.spec.js` and `e2e-tests/blocks/Image-maxi/index.spec.js` tests 👍

2022-03-01 12:55 UTC, merged