Optimization - fonts
maxi-blocks/maxi-blocks pull request #2560
Opened 2022-02-11 16:10 UTC by elzadj

Fixes #2145

2022-02-17 18:15 UTC, Naaaaiix requested changes
Found some bugs:

1. Found a `Trying to access array offset on value of type bool in /var/www/html/wp-content/plugins/maxi-blocks/core/class-maxi-styles.php on line 161 Notice: Trying to access array offset on value of type bool in /var/www/html/wp-content/plugins/maxi-blocks/core/class-maxi-styles.php on line 53` when don't using any Maxi block (just write random on a WP paragraph and do a preview).
2. Added a Text Maxi with bold Monserrat, and loaded also Roboto:
<img width="836" alt="Captura de pantalla 2022-02-17 a las 16 29 17" src="https://user-images.githubusercontent.com/50477222/154514518-45a9a4ff-3966-4372-8529-fdd81c9160a3.png">

3. Doesn't deal with more than one font-weight:

https://user-images.githubusercontent.com/50477222/154515071-11018766-6c1a-4409-b3eb-104aa15eb81d.mp4

4. Doesn't deal with weight+style, is strange both on back and front:

https://user-images.githubusercontent.com/50477222/154520902-c25ed028-1b83-4b50-a07e-54bb3d620a76.mp4

5. There's a bug on console in loop (+1 every sec):
<img width="603" alt="Captura de pantalla 2022-02-17 a las 17 05 36" src="https://user-images.githubusercontent.com/50477222/154521498-c5683f7b-b821-4859-ad6c-76620d049828.png">

6. On setting `Black (heavy)` the settings become bold:
<img width="1761" alt="Captura de pantalla 2022-02-17 a las 18 40 53" src="https://user-images.githubusercontent.com/50477222/154539925-21c4eb30-fcca-4ddc-be54-6300e52cacb3.png">

2022-02-17 23:29 UTC, bilouStrike approved these changes

2022-03-01 11:08 UTC, Marko64 approved these changes
Looks like a big one. Good job, Sv.

I hope I'm not overseeing anything, but Roboto is not anymore loaded from PHP, good; changing font families & weights, and switching SCs work well too.

2022-03-03 15:12 UTC, Alejandro9kgm approved these changes

2022-03-04 09:47 UTC, FitseTLT approved these changes

2022-03-18 08:22 UTC, Naaaaiix requested changes

2022-03-22 08:56 UTC, Naaaaiix approved these changes
Another PR bites the dust! 🤟 Splendid job @elzadj 😸

2022-03-22 08:56 UTC, merged