Transform getLastBreakpointAttribute parameters to object #2491
maxi-blocks/maxi-blocks pull request #2575
Opened 2022-02-15 20:20 UTC by FitseTLT

…as an object

2022-02-18 13:39 UTC, Alejandro9kgm approved these changes

2022-02-21 11:42 UTC, Marko64 approved these changes

2022-02-21 13:44 UTC, bilouStrike approved these changes

2022-02-23 11:50 UTC, Naaaaiix approved these changes
Cool, amazing 😻 

Please, update with master and ensure new implementations are under this new structure. Onces done it can be merged 👍

2022-03-03 13:41 UTC, elzadj requested changes
I see some bugs: svg aliment doesn't work, and the columns on frontend too: 
![Edit Page “Untitled” ‹ Local Wordpress — WordPress (8)](https://user-images.githubusercontent.com/2401618/156575263-70d00c36-91b6-4177-a0ee-6d38f1b89236.jpg)

![Local WordPress (1)](https://user-images.githubusercontent.com/2401618/156575921-3039ca6f-017c-46db-8a26-8f45dab0462c.jpg)

Learndd is ok. Not sure if it's the changes or maybe I have something local? 

Here is the blcoks' code: 
[block.txt](https://github.com/yeahcan/maxi-blocks/files/8178278/block.txt)

2022-03-03 14:14 UTC, elzadj approved these changes

2022-03-03 15:16 UTC, merged