Text font reset button #2574
maxi-blocks/maxi-blocks pull request #2580
Opened 2022-02-16 13:46 UTC by FitseTLT

2022-02-20 20:32 UTC, bilouStrike approved these changes

2022-03-04 07:50 UTC, Alejandro9kgm approved these changes
works fine, do you think it would be better if it returned your old selection instead of the default selection?🤔

2022-03-07 09:31 UTC, Marko64 approved these changes

2022-03-08 09:35 UTC, Naaaaiix requested changes
Instead of implement the reset button on TypographyControl, please, add it on FontFamilySelector. That way will be reusable on different situations. Right now, there are places like this one where the implementation scope is not arriving:
<img width="1232" alt="Captura de pantalla 2022-03-08 a las 10 35 04" src="https://user-images.githubusercontent.com/50477222/157209214-b90c96ca-4d7c-4793-a497-1e6645398882.png">

2022-03-08 13:15 UTC, Naaaaiix approved these changes
Cool, good job! 👍 

Fixed the tests; onces merged, please @Alejandro9kgm , do a test for it 👍

2022-03-10 08:34 UTC, merged