issue-2518 fix border style helper
maxi-blocks/maxi-blocks pull request #2592
Opened 2022-02-17 20:28 UTC by bilouStrike

Fixes: #2518 

Replaces #2523, check [this comment](https://github.com/yeahcan/maxi-blocks/pull/2523#issuecomment-1043268764)

2022-02-18 10:25 UTC, Marko64 approved these changes

2022-02-18 12:18 UTC, Alejandro9kgm approved these changes

2022-02-21 09:13 UTC, FitseTLT approved these changes

2022-02-21 11:18 UTC, Naaaaiix requested changes
The implementation adds 'border-color' property even when there's no border selected. Just creating a block it adds directly; I think this shouldn't be happening 👍

2022-02-23 12:30 UTC, Naaaaiix approved these changes
Well done 😸

2022-02-25 13:45 UTC, merged