transform in sidebar
maxi-blocks/maxi-blocks pull request #2594
Opened 2022-02-18 13:23 UTC by Rustam198804

Fix transform styles in sidebar and some styles for sidebar

2022-02-18 15:47 UTC, Marko64 approved these changes

2022-02-21 09:47 UTC, Alejandro9kgm approved these changes

2022-02-21 10:30 UTC, bilouStrike approved these changes

2022-02-22 07:52 UTC, bilouStrike approved these changes

2022-02-22 08:38 UTC, FitseTLT approved these changes

2022-02-23 12:16 UTC, Naaaaiix requested changes
Not sure if expected, but range sliders look different from the rest:

<img width="285" alt="Captura de pantalla 2022-02-23 a las 13 16 14" src="https://user-images.githubusercontent.com/50477222/155317719-6f844290-69b9-4264-a222-b70108634d96.png">

2022-03-04 09:01 UTC, Naaaaiix requested changes

2022-03-04 12:15 UTC, Naaaaiix approved these changes
Awesome 🥳 Good job @Rustam198804 😸

2022-03-07 09:02 UTC, merged