Style card 2022
maxi-blocks/maxi-blocks pull request #2605
Opened 2022-02-21 14:24 UTC by Rustam198804

Fixed styles for SC

2022-02-22 07:50 UTC, bilouStrike approved these changes

2022-02-22 07:56 UTC, Alejandro9kgm approved these changes

2022-02-22 08:17 UTC, FitseTLT approved these changes

2022-02-22 11:27 UTC, elzadj approved these changes

2022-02-23 12:41 UTC, Naaaaiix requested changes
Couple of small things 😸

2022-02-25 13:30 UTC, Naaaaiix approved these changes

2022-02-25 13:30 UTC, merged