Issue 2639 - CustomCSS doesn't save values
maxi-blocks/maxi-blocks pull request #2642
Opened 2022-03-01 18:40 UTC by bilouStrike

Fixes: #2639 
- In case the validator failed to check, either wrong css or network issue, the custom css content shoudn't updated to empty.
- the user might write a lot of css, so not good to remove all the css if he make some wrong one 😸

2022-03-02 11:38 UTC, Marko64 approved these changes

2022-03-03 07:36 UTC, Alejandro9kgm approved these changes

2022-03-03 09:43 UTC, FitseTLT approved these changes

2022-03-03 09:47 UTC, Naaaaiix requested changes
Small change 😸

2022-03-03 11:10 UTC, elzadj approved these changes
Great, just fix that one translation please :+1:

2022-03-03 11:54 UTC, merged