Issue 2658
maxi-blocks/maxi-blocks pull request #2679
Opened 2022-03-09 15:13 UTC by FitseTLT

fixes #2658

2022-03-10 11:35 UTC, Marko64 approved these changes

2022-03-10 13:57 UTC, Alejandro9kgm approved these changes

2022-03-13 20:48 UTC, bilouStrike approved these changes

2022-03-14 08:36 UTC, Naaaaiix requested changes
Looks everything works good but the background of the icon on hover. If you give a value it responds good, but after reloading the page then is not working anymore 👍

2022-03-18 08:52 UTC, Naaaaiix requested changes
https://user-images.githubusercontent.com/50477222/158968100-f10231ff-6558-406f-bcf8-bdc977e930f3.mp4

2022-03-22 12:22 UTC, Naaaaiix requested changes

2022-03-23 11:32 UTC, Naaaaiix requested changes

2022-03-28 11:55 UTC, Naaaaiix requested changes

2022-03-30 15:06 UTC, Naaaaiix approved these changes

2022-03-31 11:27 UTC, Naaaaiix reviewed
Why [src/blocks/button-maxi/copy-paste-mapping.js](https://github.com/yeahcan/maxi-blocks/pull/2679/files/6264b6ed16e58ad249f8a162dc8f7a0faa39bb61..7e1d60a3deffad992ddeba55649fc9de724747c8#diff-306d761e957d76cdbc796a213066ba67cab4836664f8ec1e4fee686dd217aec4) is on this PR? 🤔 

Tests need update 👍

2022-04-01 15:15 UTC, merged