issue-2694
maxi-blocks/maxi-blocks pull request #2700
Opened 2022-03-14 22:18 UTC by FitseTLT

fixes #2694

2022-03-15 12:37 UTC, Marko64 approved these changes

2022-03-16 12:04 UTC, Alejandro9kgm approved these changes

2022-03-18 08:58 UTC, Naaaaiix requested changes
Please, check the tests to don't break and update them 👍

2022-03-21 08:43 UTC, Naaaaiix approved these changes

2022-03-21 08:43 UTC, merged