Issue-2649: ClipPathControl fixes and improvements
maxi-blocks/maxi-blocks pull request #2715
Opened 2022-03-16 11:52 UTC by bilouStrike

Fixes: #2649

2022-03-16 12:40 UTC, Marko64 approved these changes

2022-03-16 14:17 UTC, Alejandro9kgm approved these changes

2022-03-17 09:51 UTC, FitseTLT approved these changes

2022-03-18 07:34 UTC, Naaaaiix requested changes
Good implementation, it works good, but we might need to simplify it. If every time we need to instance ClipPathControl we have to write this amount of code is going to be insane and a weak point where we'll make mistakes; I mean, half of the props of the component shouldn't be there. As the rest of the components, ClipPath should be able to receive all the `clipPath` attributes using:
```
{...getGroupAttributes(
	attributes,
	'clipPath',
	false,
	prefix
)}
```

and then, combining the breakpoint and the prefix, return a simple `onChange` with all the new attributes. Delegating the responsibility of this conditional to every instance of the component is not a good practice:
```
					onToggleClipPath={val => {
						onChange({
							[getAttributeKey(
								'background-image-clip-path-active',
								isHover,
								prefix,
								breakpoint
							)]: val,
							...(!val && {
								[getAttributeKey(
									'background-image-clip-path',
									isHover,
									prefix,
									breakpoint
								)]: null,
							}),
						});
					}}
```

It should be done on the same component 👍

2022-03-18 07:35 UTC, Naaaaiix requested changes

2022-03-30 15:27 UTC, Naaaaiix requested changes

2022-03-31 09:35 UTC, Naaaaiix requested changes

2022-03-31 11:34 UTC, Naaaaiix approved these changes
Fantastic! 🤟

2022-03-31 12:15 UTC, merged