Issue 2711 - RTL margin on lists
maxi-blocks/maxi-blocks pull request #2718
Opened 2022-03-16 15:53 UTC by Fybex

Fixes #2711.

Add margin left-right swap when RTL is on.

Before -> After
![image](https://user-images.githubusercontent.com/46112160/158631222-e8b98aa3-e5c3-4952-8076-f55537d3ec32.png)

2022-03-17 07:18 UTC, Alejandro9kgm approved these changes

2022-03-17 09:28 UTC, FitseTLT approved these changes

2022-03-17 12:35 UTC, Naaaaiix requested changes
Good job 👍  Some options doesn't work correctly; at least I've found list-gap (affects the left side, should affect right on) and marker-indent

2022-03-24 09:21 UTC, Alejandro9kgm approved these changes

2022-03-24 10:06 UTC, FitseTLT approved these changes

2022-03-24 11:58 UTC, Naaaaiix approved these changes
Bravo 🎉

2022-03-24 11:58 UTC, merged