Issue 2667 - Responsive not working for 's' and 'xs'
maxi-blocks/maxi-blocks pull request #2740
Opened 2022-03-21 17:30 UTC by Naaaaiix

Fixes #2667

2022-03-22 07:32 UTC, Alejandro9kgm reviewed
With the icons this happens

https://user-images.githubusercontent.com/58038966/159429556-ba7e5f92-58be-4501-89a9-0416ddeee69f.mp4

2022-03-22 09:26 UTC, Fybex approved these changes

2022-03-22 09:55 UTC, Fybex requested changes
Svg resize bug(in different responsive breakpoints bug comes out as well).

https://user-images.githubusercontent.com/46112160/159454120-510616c6-94ae-4533-af3a-af497bd0cc27.mp4

2022-03-22 12:15 UTC, Fybex approved these changes

2022-03-23 16:09 UTC, bilouStrike approved these changes

2022-03-24 08:09 UTC, Alejandro9kgm approved these changes

2022-03-24 12:12 UTC, elzadj approved these changes

2022-03-24 13:11 UTC, merged