issue-2737 fixed icon fill issue on button-maxi
maxi-blocks/maxi-blocks pull request #2748
Opened 2022-03-22 13:26 UTC by FitseTLT

fixes #2737 
@Naaaaiix Don't you think we should give the users to change the icon fill color on button-maxi? Now, I made it to have the icon's default fill when the icon inherit is false, and when it's true fill will be none. I think it's quite logical.

2022-03-29 09:25 UTC, Alejandro9kgm approved these changes

2022-03-29 10:23 UTC, Marko64 approved these changes
Works good. Just a different icon here :) 
![Screenshot_1](https://user-images.githubusercontent.com/19425503/160590998-b93ef7e4-f05f-442f-96fa-f511d19992ae.jpg)

2022-03-30 09:49 UTC, Marko64 approved these changes

2022-04-07 09:20 UTC, Naaaaiix requested changes
Need to fix the tests @FitseTLT , there are some that just need update, but there are other that seem is showing that we might have an error on the implementation 👍

2022-04-11 07:12 UTC, Naaaaiix approved these changes

2022-04-11 12:25 UTC, elzadj approved these changes

2022-04-13 06:40 UTC, merged