New scroll effects
maxi-blocks/maxi-blocks pull request #2759
Opened 2022-03-24 12:41 UTC by Marko64

Added effect shortcuts from this document:
https://docs.google.com/spreadsheets/d/1voZ4zmKmZ3ydh3dHBSK3FBP_Oz4AwA6qr5s183lOrMA/edit#gid=0

2022-03-24 17:24 UTC, Fybex approved these changes

2022-03-24 19:02 UTC, FitseTLT approved these changes

2022-03-25 11:22 UTC, elzadj requested changes
@Marko64 great job! I don't think we need the old test effects, so remove them please. Maybe leave 'Disable all' in place, it's really useful. Thanks!

2022-03-25 14:19 UTC, elzadj approved these changes

2022-03-25 14:19 UTC, merged