Issue 2758
maxi-blocks/maxi-blocks pull request #2783
Opened 2022-03-30 13:51 UTC by myroslavve

Fixes #2758 

SettingTabsControl tab now updates with state from wp/data store
Added tab prop to ToolbarPopover so it knows on which tab to switch

2022-03-30 14:47 UTC, Marko64 approved these changes

2022-03-31 07:30 UTC, Naaaaiix reviewed
Good job! 😄 which toolbar popover can we test to see it works? 🤔

2022-03-31 08:34 UTC, bilouStrike approved these changes

2022-04-01 11:56 UTC, elzadj requested changes
I'm getting 

```
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'querySelector')
    at openSidebar (index.js:333:32)
    at index.js:100:24

```

For a Button: 


https://user-images.githubusercontent.com/2401618/161258714-a834d3c2-5e10-4e20-9e45-a9f035d88605.mp4

2022-04-05 07:38 UTC, Naaaaiix approved these changes

2022-04-05 14:06 UTC, elzadj approved these changes

2022-04-05 14:19 UTC, merged