issue-2791 : Add flexible unit settings
maxi-blocks/maxi-blocks pull request #2808
Opened 2022-04-05 09:53 UTC by bilouStrike

Fixes: #2791

2022-04-05 10:14 UTC, Marko64 approved these changes

2022-04-05 10:23 UTC, FitseTLT approved these changes

2022-04-06 08:53 UTC, Naaaaiix requested changes
E2e tests need some fixes also 😄

2022-04-06 09:57 UTC, elzadj requested changes
Visually works fine, but need to check the tests, there are some weird errors + ```undefined```

2022-04-08 07:20 UTC, Naaaaiix requested changes
About test:

1. `e2e-tests/editor/responsive.spec.js`: margin values are returned as number and not strings. Is necessary to be strings to be able to deal with `auto` 👍 
2. `e2e-tests/components/axis-control/index.spec.js`: set `.skip` on the description (`describe.skip(...`) and @Alejandro9kgm will fix it after the merging 👍 
3. `e2e-tests/blocks/button-maxi/index.spec.js`: shows that `button-padding-unit-xxl` is still part of the `default.js` file of Button Maxi. Needs to be cleaned 👍 
4. `e2e-tests/components/indicators/index.spec.js`: do same than 2

@Alejandro9kgm please, consider this couple of skipped tests as a priority onces this branch will be merged. Thanks 😸

2022-04-11 07:05 UTC, Naaaaiix requested changes

2022-04-15 08:40 UTC, elzadj approved these changes

2022-04-18 10:28 UTC, merged