Issue 2719 - Map-maxi update
maxi-blocks/maxi-blocks pull request #2820
Opened 2022-04-06 12:37 UTC by Fybex

## Important
To merge the map, you must wait for merge #3517
For test, you need to install new dependencies: `npm ci`

# Description

### Map-maxi is ready 🎉 

Now we have two map providers:
- open street maps (by default)
- google maps
Both of them have the same functionality.

## Functionality
we can put multiply markers which has pop-ups on click, for add marker you can hold mouse on map until alert will appear so add marker, or use search box to put marker in special place, on marker click, pop-up will open, you can set title and description or remove marker.
Also, you can drag marker to change his placement.

On the frontend, map will be positioned as it was on last moment on editor, with zoom the same story.

Fixes #2719 

# How Has This Been Tested?
Checked if new map working good in general with both providers, on frontend and backend.

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test the map-maxi open street maps map provider
-   [ ] Test the map-maxi Google Maps  map provider
-   [ ] Test the map-maxi all other functionality
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type

**_ Pre-Code Testing _**

-   [ ] Test the map-maxi open street maps map provider
-   [ ] Test the map-maxi Google Maps  map provider
-   [ ] Test all other the map-maxi functionality
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [X] My code follows the style guidelines of this project
-   [X] I have performed a self-review of my code
-   [X] I have commented my code, particularly in hard-to-understand areas
-   [X] My changes generate no new warnings/errors
-   [X] I have added/updated tests that prove my fix is effective or that my feature works
-   [X] New and existing unit tests pass locally with my changes

2022-08-03 09:43 UTC, Marko64 approved these changes
Worked wonderfully. Going to approve, but I do have a few small comments:

1. Not a big deal if we leave it as is, but the _min_ can be greater than the _max_ zoom level.
![Screenshot_4](https://user-images.githubusercontent.com/19425503/182574897-e0c7f6e5-157b-48e7-99df-04ffb0030663.jpg)

2. When you enter the wrong Google maps API key, the map is just grey. Is it possible to show a warning message in this case? Something like what Google says in the console: "Invalid map API key".

3. Can't increase width above 600px or similar. 
Set width to fit content may not be needed for the map.

4. Interactions:
Dragging works on the frontend only. Other settings work on the backend too. Not a big deal as well, but mentioning just in case.

2022-08-04 12:08 UTC, myroslavve requested changes

2022-08-05 09:38 UTC, myroslavve approved these changes

2022-08-10 12:14 UTC, Naaaaiix reviewed
I'm running out of sentences saying how great is a PR and implementation, so going to start using gifs:
![](https://media.giphy.com/media/czubJ08i7deuKGJE9A/giphy.gif)

Some comments, but in general is a 10. Congrats @Fybex 🎉 

- On the `components` folder inside of blocks replace the folder for files directly. We don't need, for example, a path like `src/blocks/map-maxi/components/search-box/index.js`; would be better, IMO, to have something like `src/blocks/map-maxi/components/search-box.js` 👍

2022-08-18 07:40 UTC, Naaaaiix approved these changes
Let's fix these e2e tests and merge this beauty 😜

2022-08-18 13:56 UTC, merged