Issue 2812 svg hover
maxi-blocks/maxi-blocks pull request #2887
Opened 2022-04-20 14:54 UTC by elzadj

Fixes #2812
Fixes #2865 
Fixes #2867

2022-04-22 07:07 UTC, Marko64 approved these changes
Works good now.

The arrow issue is on Firefox only, just checked.

2022-04-22 13:15 UTC, Alejandro9kgm approved these changes

2022-04-23 13:45 UTC, bilouStrike approved these changes

2022-04-25 11:12 UTC, FitseTLT requested changes
SVG Fill hover color doesn't work for all fills in the Icon
Last time I was working on Icon colors on button maxi I found out that 
https://github.com/yeahcan/maxi-blocks/blob/37c37f42cf95e1b6586d756c9443bcca0b0d357e/src/blocks/svg-icon-maxi/styles.js#L221
doesn't work perfectly, like in these case it doesn't apply the colors to all elements under the svg.

https://user-images.githubusercontent.com/38649957/165077591-70841cf1-ea80-4aae-b339-f52c8697089d.mp4

2022-04-25 11:15 UTC, Naaaaiix approved these changes
Cool! 

Just one last detai: we may need to abstract `changeSVGStrokeWidth`, `changeSVGContentWithBlockStyle`, `changeSVGContent`, `changeSVGContentHover` and the rest of repeated SVG methods (most of them inside the `withDispatch`). If you agree with it do it on this same branch or create an issue to do it after merging 😸

2022-04-26 21:07 UTC, kyrapieterse approved these changes

2022-04-27 12:52 UTC, bilouStrike approved these changes

2022-04-28 09:01 UTC, Naaaaiix approved these changes

2022-04-28 09:08 UTC, merged