Issue 2839 move Number Counter replay button to the toolbar
maxi-blocks/maxi-blocks pull request #2912
Opened 2022-04-23 09:17 UTC by Marko64

Fixes #2839

2022-04-23 14:06 UTC, bilouStrike approved these changes

2022-04-25 12:47 UTC, Naaaaiix approved these changes
Yeah 💪 🥳

2022-04-25 12:56 UTC, elzadj approved these changes

2022-04-27 13:44 UTC, elzadj requested changes
Sorry, noticed a bug - it replays from the previous Start number. See the video: 


https://user-images.githubusercontent.com/2401618/165532723-20d6f1bd-b199-4eaf-98ea-5e9397b1c180.mp4



The old replay button does not have this bug. Need a state, I guess.

2022-05-02 09:04 UTC, elzadj approved these changes
Works great! Let's merge?

2022-05-02 09:32 UTC, merged