Issue 2895 - Box shadow add units
maxi-blocks/maxi-blocks pull request #2919
Opened 2022-04-25 08:29 UTC by myroslavve

Fixes #2895

2022-04-25 08:58 UTC, Marko64 approved these changes

2022-04-25 09:12 UTC, bilouStrike reviewed
"general": Object {
-     "box-shadow": "1px 2px 3px 4px rgb(255, 99, 71)",
+     "box-shadow": "1undefined 2undefined 3undefined 4undefined rgb(255, 99, 71)",
}
check the getBoxShadowStyles test

2022-04-25 10:32 UTC, bilouStrike approved these changes

2022-04-25 13:11 UTC, elzadj requested changes
When I change the Box Shadow Hover units, they are changing in the Normal state:

https://user-images.githubusercontent.com/2401618/165095779-92f31609-f658-4526-9a30-49681eb5f283.mp4

2022-04-27 14:43 UTC, elzadj approved these changes

2022-04-28 08:35 UTC, elzadj approved these changes

2022-04-28 08:35 UTC, merged