Fixes #2851 - Loading proper SC fonts from google
maxi-blocks/maxi-blocks pull request #2952
Opened 2022-04-28 18:06 UTC by Naaaaiix

# Description

Font loader wasn't ready to deal with changes on SC. An example: a creator does post-1 with a `Roboto` SC font-family for paragraph, and publishes it. Then, in post-2 changes the font-family for the paragraph to `Montserrat` and publishes it. If we check post-1 is going to stay on Roboto, but being a SC value should affect all pages.
Other issue found was that `getAllFonts` just get one font for every block, so it means it wasn't able to get different fonts for every responsive stage.

What has been done is create an alternative name for the elements which font-family relies on SC that is used on the server side to request for the SC value. Also has breakpoint support, but then I found is not necessary as Font Family is just shown on general responsive stage on the SC lol

Also implemented php linter standard on the code settings 👍 

PS: we need unit and e2e for this implementation, is too important and delicate 👍 

Fixes #2851 

# How Has This Been Tested?

To test it we've got 2 different situations: with local fonts activate/deactivate, so test next steps with both situations:
1. Create a post, and set different blocks, like text (with different headings), button or image (the ones that have text part)
2. Publish the post and check frontend
3. Create a new post, do the same than step 1
4. Change SC font-family for some things and then apply the SC.
5. Publish the post, check frontend and then check the frontend of the first post after reloading: it should get the new font 👍 

# Test checklist

**_ Front/Back Testing _**

-   [x] Test the component in normal state in sidebar
-   [x] Test the component in hover state in sidebar (if hover exists)
-   [x] Check that the settings work on frontend
-   [x] Check that backend works and saves the settings after the editor reload
-   [x] Duplicate the block, test that the settings of the first do not affect the second
-   [x] Test with 2 blocks of the same type

**_ Pre-Code Testing _**

-   [x] Test the component in normal state in sidebar
-   [x] Test the component in hover state in sidebar (if hover exists)
-   [x] Check that the settings work on frontend
-   [x] Check that backend works and saves the settings after the editor reload
-   [x] Duplicate the block, test that the settings of the first do not affect the second
-   [x] Test with 2 blocks of the same type
-   [x] Check no commented code and no unnecessary imports
-   [x] Standards of the project have been followed
-   [x] No errors/warnings on console

# Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [x] New and existing unit tests pass locally with my changes

2022-05-02 10:03 UTC, Alejandro9kgm approved these changes

2022-05-03 12:52 UTC, Fybex approved these changes

2022-05-04 10:15 UTC, elzadj requested changes
Great work! 

I've noticed that the 
```sc_font_light_p_general```
and 
```sc_font_maxi-light_button_general```

stay in DB even if I change the fonts to custom (i.e. do not use the SC's font anymore). And the SC font is still loading on the pages where we do not use it anymore.

```sc_font_maxi-light_button_general``` stays in the DB even after I remove the button and the text blocks from the page.

2022-05-09 08:14 UTC, elzadj approved these changes
Works great, one small thing, I see doubled 400 and 'normal' for p:

```{"sc_font_light_p":{"fontWeight":"400,400","fontStyle":"normal,normal"},"sc_font_light_button":{"fontWeight":"400","fontStyle":"normal"},"Lexend Peta":{"fontWeight":"400","fontStyle":"normal"},"Averia Gruesa Libre":{"fontWeight":"500","fontStyle":"normal"},"Odibee Sans":{"fontWeight":"500","fontStyle":"normal"}}```

Here is the blocks code: 
[doubled-p-400-normal.txt](https://github.com/yeahcan/maxi-blocks/files/8649812/doubled-p-400-normal.txt)

If I change the SC p font to 200 / italic, it doubles too:

```{"sc_font_light_p":{"fontWeight":"200,200","fontStyle":"italic,italic"},"sc_font_light_button":{"fontWeight":"400","fontStyle":"normal"},"Lexend Peta":{"fontWeight":"400","fontStyle":"normal"},"Averia Gruesa Libre":{"fontWeight":"500","fontStyle":"normal"},"Odibee Sans":{"fontWeight":"500","fontStyle":"normal"}}```

Also the italic does not work on backend (can be a new issue).

2022-05-09 09:29 UTC, merged