issue-2937-button-text-select-error
maxi-blocks/maxi-blocks pull request #2974
Opened 2022-04-29 19:48 UTC by Marko64

# Description

Problem: _Text direction_ is causing an error. It needs a default value.
I'm not sure if this is the correct way to fix it. If not, please suggest where else can I define the defaults.

Fixes #2937

# How Has This Been Tested?

Insert the text or the button block and select it. Check the console for errors. 

# Test checklist

**_ Front/Back Testing _**

-   [ ] Inset the text block. Select it. Check the console for errors.
-   [ ] Select the Typography panel from the sidebar and test all the settings that use SelectControl. 
-   [ ] Repeat the same for the button block.

**_ Pre-Code Testing _**

-   [x] Inset the text block. Select it. Check the console for errors.
-   [x] Select the Typography panel from the sidebar and test all the settings that use SelectControl. Make sure they work and don't throw any errors in the console.
-   [x] Repeat the same for the button block.

# Checklist

-   [x] I have performed a self-review of my code
-   [x] My changes generate no new warnings/errors

2022-05-02 07:28 UTC, Alejandro9kgm approved these changes

2022-05-02 08:25 UTC, Naaaaiix reviewed
This implementation 'fixes' partly the issue, the problem is that can generate a new one. Adding a default attribute we create the CSS, which can go against the creators interests when is rtl website. A better fix would be, on:
https://github.com/yeahcan/maxi-blocks/blob/e489d3e3d300646b2a55f080a3108946d18f9955/src/components/typography-control/index.js#L876

replace for:
```
			<SelectControl
				label={__('Text direction', 'maxi-blocks')}
				className='maxi-typography-control__direction'
				value={getValue(
					`${prefix}text-direction`,
					breakpoint,
					false,
					true
				)}
[...]
````

2022-05-05 13:34 UTC, Alejandro9kgm approved these changes

2022-05-05 20:53 UTC, FitseTLT approved these changes

2022-05-06 07:29 UTC, Naaaaiix requested changes

2022-05-09 07:38 UTC, Naaaaiix reviewed
Tests need an update 😸

2022-05-13 15:05 UTC, merged