Issue 2964 - make resizer not affect the grid
maxi-blocks/maxi-blocks pull request #2975
Opened 2022-05-02 09:49 UTC by myroslavve

# Description
Added position: absolute to the div containing resizers, so it won't affect the grid

Fixes #2964 

# How Has This Been Tested?
Insert two blocks in column maxi and set Vertical align to ```space-between``` they should position on top and bottom of the column

# Test checklist

**_ Front/Back Testing _**

-   [x] Check if positioning works right
-   [x] Same on responsive
-   [x] Check if resizer works
-   [x] Check that the settings work on frontend

**_ Pre-Code Testing _**

-   [ ] Check if positioning works right
-   [ ] Same on responsive
-   [ ] Check if resizer works
-   [ ] Check that the settings work on frontend
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [x] New and existing unit tests pass locally with my changes

2022-05-02 10:18 UTC, Naaaaiix requested changes
The manual resizer doesn't work:

<img width="1108" alt="Captura de pantalla 2022-05-02 a las 12 18 20" src="https://user-images.githubusercontent.com/50477222/166219510-661c204b-6a83-43c6-8479-c9c6345c388b.png">

2022-05-02 15:06 UTC, Naaaaiix approved these changes

2022-05-03 06:48 UTC, Marko64 approved these changes

2022-05-03 11:40 UTC, FitseTLT approved these changes

2022-05-03 11:50 UTC, merged