issue 2981 container width
maxi-blocks/maxi-blocks pull request #2989
Opened 2022-05-02 15:04 UTC by Marko64

# Description

Container needs width option to display in the sidebar if full-width is disabled.

Fixes yeahcan/maxi-blocks#2981 

# How to test?

Add a container and try enabling/disabling full-width from the sidebar. Width option should show only if full-width is disabled.

# Test checklist

**_ Front/Back Testing _**

-   [x] Test the component in normal state in sidebar
-   [x] Check that the settings work on frontend
-   [x] Check that backend works and saves the settings after the editor reload
-   [x] Same 1-4 points on responsive

**_ Pre-Code Testing _**

-   [x] Test the component in normal state in sidebar
-   [x] Same 1-4 points on responsive
-   [x] Check no commented code and no unnecessary imports
-   [x] Standards of the project have been followed
-   [x] No errors/warnings on console

# Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my code
-   [] I have commented my code, particularly in hard-to-understand areas
-   [x] My changes generate no new warnings/errors
-   [] I have added/updated tests that prove my fix is effective or that my feature works
-   [x] New and existing unit tests pass locally with my changes

2022-05-05 09:30 UTC, Rustam198804 approved these changes

2022-05-05 21:06 UTC, FitseTLT approved these changes

2022-05-09 07:09 UTC, Naaaaiix requested changes
Code need a big check, not because this implementation has made any mistake, because the code was probably corrupted before and right now has many incongruences. Also, the pretended implementation doesn't work on my local:

https://user-images.githubusercontent.com/50477222/167358204-71465175-c931-4499-99ee-768a0413ac5e.mp4

2022-05-13 07:55 UTC, Naaaaiix reviewed
Seems something has gotten out of hand with 120 files changed lol

<img width="723" alt="Captura de pantalla 2022-05-13 a las 9 54 22" src="https://user-images.githubusercontent.com/50477222/168237447-3c2a6215-1713-4481-9476-32cb7af94256.png">

2022-05-13 14:24 UTC, closed without merging