Issue 2942 - Image Maxi enhance
maxi-blocks/maxi-blocks pull request #2996
Opened 2022-05-03 10:08 UTC by Naaaaiix

# Description

As commented on #2942 found in library some Image Maxi with a `display: none` on the images and showing the background. That shows we are not covering a necessity creators have. This PR tries to solve it

Fixes #2942 

# How Has This Been Tested?

Get some patterns and check they show the same after allowing image again and removing background

https://user-images.githubusercontent.com/50477222/166435958-aa21fdc1-cac8-4660-adcb-48e4f8ea06e5.mp4

Please @Rustam198804 and @Olekrut you're the ones with more experience on builders and in Maxi editing, let us know if this fix helps you and if it doesn't break anything 😸 

# Test checklist

**_ Front/Back Testing _**

-   [x] Test Image Maxi with different sizes
-   [x] Test Image Maxi with ratio size
-   [x] Test Image Maxi with clip-path
-   [x] Test Image Maxi with hover effects
-   [x] Test Image Maxi with shape mask
-   [x] Test Image Maxi with canvas size modified

**_ Pre-Code Testing _**

-   [x] Test Image Maxi with different sizes
-   [x] Test Image Maxi with ratio size
-   [x] Test Image Maxi with clip-path
-   [x] Test Image Maxi with hover effects
-   [x] Test Image Maxi with shape mask
-   [x] Test Image Maxi with canvas size modified
-   [x] Check no commented code and no unnecessary imports
-   [x] Standards of the project have been followed
-   [x] No errors/warnings on console

# Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] My changes generate no new warnings/errors
-   [x] I have added/updated tests that prove my fix is effective or that my feature works
-   [x] New and existing unit tests pass locally with my changes

2022-05-03 14:12 UTC, Marko64 approved these changes

2022-05-04 10:10 UTC, FitseTLT approved these changes

2022-05-04 10:57 UTC, elzadj requested changes
weird, it looks like the icon was changed for the ```maxi-blocks/column-maxi```?

I still see the bug.

2022-05-06 11:43 UTC, elzadj approved these changes

2022-05-06 11:43 UTC, merged