Issue 2940
maxi-blocks/maxi-blocks pull request #3004
Opened 2022-05-03 21:06 UTC by FitseTLT

# Description
Added SVG hover colors for Style Card

Fixes #2940 

# How Has This Been Tested?
For the moment b/c the stylecards don't include hover svg colors, I just check if the hover colors are applying to all svgs after making the 'use Global fill/line color' checkbox on in the Style card.

# Test checklist

**_ Front/Back Testing _**

-   [x] Test the component in normal state in sidebar
-   [x] Test the component in hover state in sidebar (if hover exists)
-   [x] Check that the settings work on frontend

**_ Pre-Code Testing _**

-   [x] Test the component in normal state in sidebar
-   [x] Test the component in hover state in sidebar (if hover exists)
-   [x] Check that the settings work on frontend
-   [x] Check no commented code and no unnecessary imports
-   [x] Standards of the project have been followed
-   [x] No errors/warnings on console

# Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my code
-   [x] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works

2022-05-04 10:30 UTC, elzadj requested changes
The palette works, nice work! 

The custom colours do not work tho: 

https://user-images.githubusercontent.com/2401618/166664984-8f1aadaa-6326-44df-a1fd-8cb099695855.mp4

2022-05-04 11:39 UTC, Marko64 approved these changes

2022-05-05 13:18 UTC, Fybex approved these changes

2022-05-05 14:50 UTC, Naaaaiix approved these changes
In terms of code it looks good for me 👍

2022-05-06 08:29 UTC, elzadj requested changes
Please test on the Cruise icon (not the broken one) - it has some bugs with Line Colour for sure.

2022-05-09 08:39 UTC, elzadj approved these changes

2022-05-09 08:43 UTC, merged