add test for force aspect ratio
maxi-blocks/maxi-blocks pull request #3010
Opened 2022-05-04 14:06 UTC by Alejandro9kgm

2022-06-27 09:42 UTC, FitseTLT approved these changes

2022-06-27 10:23 UTC, Naaaaiix requested changes

2022-07-01 11:30 UTC, Naaaaiix requested changes

2022-07-06 11:11 UTC, Naaaaiix requested changes

2022-07-12 08:54 UTC, Naaaaiix requested changes
@Alejandro9kgm please, check the comments. Not sure why, but I requested the same changes 4 times and haven't been implemented; is there any reason they are not implemented? Are the comments hidden to you or something? Please, let us know why the requested changes haven't been applied 👍

2022-07-12 14:24 UTC, merged