Issue 3012 - SVG resizing bug
maxi-blocks/maxi-blocks pull request #3023
Opened 2022-05-05 12:33 UTC by Fybex

# Description

The problem with SVG was that we also get the svg-icon-maxi size attribute in the "number" type from Resizer and AdvancedNumberControl.
This has been fixed, now we get the 'string' type.
After #2988 we need to get 'string' to size attributes and it is what was fixed in this PR in Resizer and AdvancedNumberControl.

Fixes #3012 

# How Has This Been Tested?

Add SVG-icon-maxi and test its resizing after saving with resizer or toolbar, also test other size attributes correct work in other blocks (now we have in AdvancedNumberControl new prop - optionType which can be 'number' or 'string'(for size attributes))

# Test checklist

**_ Front/Back Testing _**

-   [x] Test the SVG icon maxi resizing work after reload
-   [x] Test the SVG icon maxi resizing from the toolbar after reload
-   [x] Test other components which contain size attributes
-   [x] Check that the settings work on frontend
-   [x] Same 1-4 points on responsive

**_ Pre-Code Testing _**

-   [ ] Test the SVG icon maxi resizing work after reload
-   [ ] Test the SVG icon maxi resizing from the toolbar after reload
-   [ ] Test other components which contain size attributes
-   [ ] Check that the settings work on frontend
-   [ ] Same 1-4 points on responsive
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [X] My code follows the style guidelines of this project
-   [X] I have performed a self-review of my code
-   [X] My changes generate no new warnings/errors
-   [X] New and existing unit tests pass locally with my changes

2022-05-05 13:00 UTC, Marko64 approved these changes

2022-05-06 07:32 UTC, Marko64 approved these changes

2022-05-06 09:07 UTC, FitseTLT requested changes
In the backend, icon size from the toolbar doesn't work for non-general breakpoints.

2022-05-06 14:18 UTC, FitseTLT approved these changes

2022-05-06 14:31 UTC, merged