Issue 3013  - dashboard settings
maxi-blocks/maxi-blocks pull request #3055
Opened 2022-05-10 13:36 UTC by elzadj

# Description

Adds 3 new dashboard's settings functionality:

- allow SVG / JSON upload
- Hide interface tooltips
- Responsive design breakpoints

Fixes #3013 )

# How Has This Been Tested?

- allow SVG / JSON upload
Check that it's working in general. Note that wordpress still does not allow svg with js code inside.
- Hide interface tooltips
Check the toolbar's tooltips.
- Responsive design breakpoints
Affects the responsive mode. 

# Test checklist

**_ Front/Back Testing _**

-   [x] Enable and test 'allow SVG / JSON upload'
-   [x] Disable and test  'allow SVG / JSON upload'
-   [x] Enable and test 'Hide interface tooltips'
-   [x] Disable and test 'Hide interface tooltips'
-   [x] Change and test 'Responsive design breakpoints'

**_ Pre-Code Testing _**

-   [ ] Enable and test 'allow SVG / JSON upload'
-   [ ] Disable and test  'allow SVG / JSON upload'
-   [x] Enable and test 'Hide interface tooltips'
-   [x] Disable and test 'Hide interface tooltips'
-   [x] Change and test 'Responsive design breakpoints'

# Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [x] New and existing unit tests pass locally with my changes

2022-05-10 15:15 UTC, Marko64 approved these changes
Works great.

2022-05-11 12:33 UTC, FitseTLT requested changes
I don't know what we should do but once there is for eg image maxi using svg as its content if U disable uploading svg setting the block will break!!!

2022-05-13 14:33 UTC, FitseTLT approved these changes

2022-05-13 15:21 UTC, Naaaaiix approved these changes

2022-05-13 15:21 UTC, merged