Issue 3042 - image caption
maxi-blocks/maxi-blocks pull request #3057
Opened 2022-05-10 14:42 UTC by myroslavve

# Description
#2996 caused the first problem, did the same thing as in there, but with flex. And changed caption toolbar position to bottom.

Fixes #3042
# How to test?
Check the patterns from #2996 still work, and check bugs reported in the issue.

# Test checklist

**_ Front/Back Testing _**

-   [x] Check caption top toolbar doesn't overflow block toolbar
-   [x] Check caption is inside image block
-   [x] Check that patterns work 
-   [x] Check that the settings work on frontend

**_ Pre-Code Testing _**

-   [x] Check caption top toolbar doesn't overflow block toolbar
-   [x] Check caption is inside image block
-   [ ] Check that patterns work 
-   [x] Check that the settings work on frontend
-   [x] Check no commented code and no unnecessary imports
-   [x] Standards of the project have been followed
-   [x] No errors/warnings on console

# Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] My changes generate no new warnings/errors
-   [x] New and existing unit tests pass locally with my changes

2022-05-10 15:29 UTC, Marko64 approved these changes

2022-05-10 20:55 UTC, FitseTLT approved these changes

2022-05-11 08:53 UTC, Naaaaiix requested changes
Didn't check the code yet, just opened and found:
<img width="1218" alt="Captura de pantalla 2022-05-11 a las 10 53 01" src="https://user-images.githubusercontent.com/50477222/167810404-4ffdaaa4-fd77-4dff-9128-37b6f1c770a3.png">

is it jut me? 🤔

2022-05-13 15:28 UTC, Naaaaiix requested changes
https://user-images.githubusercontent.com/50477222/168316654-39f246f1-d9b7-434c-8d8b-959a7888e911.mp4

2022-05-17 13:16 UTC, Naaaaiix approved these changes
Good job @TeksPeks ! Not going to hide I'm a bit afraid of changing the target of the size on Image Maxi, but I've tested everything I could and seems is working good.

Please, fix tests and let's merge this little baby!

2022-05-17 15:40 UTC, merged