Issue 3011: Style Card editor disappears when opening the Advanced tab
maxi-blocks/maxi-blocks pull request #3060
Opened 2022-05-10 21:03 UTC by FitseTLT

# Description
Fixed: Style Card editor disappears when opening the Advanced tab on foundation blocks with Canvas tab and the automatic closing of accordion of the style card when an accordion is opened in the side-bar.

Fixes #3011 

# How Has This Been Tested?
Check

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test the Style card doesn't disappear when opening Advanced Tab
-   [ ] Test the accordion in SC doesn't close when accordion in side bar is opened

**_ Pre-Code Testing _**

-   [x] Test the Style card doesn't disappear when opening Advanced Tab
-   [x] Test the accordion in SC doesn't close when accordion in side bar is opened
-   [x] Check no commented code and no unnecessary imports
-   [x] Standards of the project have been followed
-   [x] No errors/warnings on console

# Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my code

2022-05-11 12:07 UTC, Rustam198804 approved these changes

2022-05-12 19:17 UTC, Fybex approved these changes

2022-05-13 12:54 UTC, Naaaaiix requested changes

2022-05-13 15:30 UTC, Naaaaiix requested changes
https://user-images.githubusercontent.com/50477222/168317042-eb97e5bb-8c87-48a8-9bc2-cb7ff6138797.mp4

2022-05-13 16:58 UTC, Naaaaiix approved these changes

2022-05-13 16:58 UTC, merged