Issue 3039 - Fix column gap size
maxi-blocks/maxi-blocks pull request #3074
Opened 2022-05-12 13:42 UTC by Fybex

# Description

Changes:
- add `columnNum` to `rowGapProps`
- create separate file for `getClientId` function

Fixes #3039 

# How Has This Been Tested?

Change column gap and check if it works as described in #3039

# Test checklist

**_ Front/Back Testing _**

-   [x] Test the component in normal state in sidebar with all possible column numbers and gaps
-   [x] Check that the settings work on frontend
-   [x] Check that backend works and saves the settings after the editor reload
-   [x] Same 1-4 points on responsive
-   [x] Duplicate the block, test that the settings of the first do not affect the second
-   [x] Test with 2 blocks of the same type

**_ Pre-Code Testing _**

-   [x] Test the component in normal state in sidebar with all possible column numbers and gaps
-   [x] Check that the settings work on frontend
-   [x] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points on responsive
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type
-   [x] Check no commented code and no unnecessary imports
-   [x] Standards of the project have been followed
-   [x] No errors/warnings on console

# Checklist

-   [X] My code follows the style guidelines of this project
-   [X] I have performed a self-review of my code
-   [X] My changes generate no new warnings/errors
-   [X] I have added/updated tests that prove my fix is effective or that my feature works
-   [X] New and existing unit tests pass locally with my changes

2022-05-12 15:30 UTC, FitseTLT approved these changes

2022-05-13 11:47 UTC, Naaaaiix requested changes

2022-05-16 08:44 UTC, Naaaaiix requested changes
There's still a minor bug:

<img width="1407" alt="Captura de pantalla 2022-05-16 a las 10 43 14" src="https://user-images.githubusercontent.com/50477222/168554016-6b854167-a20e-4856-8855-8e34628c950c.png">

to fix it, please, modify `` and replace the lodash function `round` for `floor` 👍 

Onces done, please, start the reviewing again with `front/back` as the main code has been changed and needs to be reviewed again 👍

2022-05-18 09:51 UTC, FitseTLT approved these changes

2022-05-18 11:17 UTC, merged