Issue 3104 block sidebar header ui
maxi-blocks/maxi-blocks pull request #3140
Opened 2022-05-18 13:26 UTC by Marko64

I'm not sure I've added the info icon and the state hook at the right place. If it should be better added somewhere else, let me know.

# Description

Adds more compact style to the block's header in the sidebar.

Fixes #3104

2022-05-19 08:35 UTC, Rustam198804 approved these changes

2022-05-23 09:20 UTC, FitseTLT approved these changes
Nice!!! I like it!!!

2022-05-23 09:49 UTC, Naaaaiix approved these changes
It works good, but as commented, the way `useState` and the way to affect `'.block-editor-block-card__description'` are not the optimal. Have a look to [this file](https://github.com/yeahcan/maxi-blocks/blob/9a223d80e78f99fc88b6ac9e7cc4f2744a52ceb1/src/components/block-styles-control/index.js#L43-L53) to see some suggestions about. If you decide to add them re-request the review, if not, merge directly 👍

2022-05-24 08:32 UTC, elzadj requested changes

2022-05-27 08:16 UTC, closed without merging