Issue:2923 Copy/Paste UI
maxi-blocks/maxi-blocks pull request #3159
Opened 2022-05-19 21:20 UTC by FitseTLT

# Description
Copy paste props are organized (grouped and ordered) similar to the side bar.

Fixes #2923 

# How Has This Been Tested?

# Test checklist

**_ Front/Back Testing _**

-   [x] Check copy paste works for all blocks

**_ Pre-Code Testing _**

-   [x] Check copy paste works for all blocks
-   [x] Check no commented code and no unnecessary imports
-   [x] Standards of the project have been followed
-   [x] No errors/warnings on console

# Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my code

2022-05-26 08:20 UTC, Marko64 approved these changes

2022-05-26 13:45 UTC, myroslavve approved these changes
Now working fine 👍

2022-05-26 14:47 UTC, elzadj approved these changes

2022-05-27 08:21 UTC, Naaaaiix requested changes
Need a bit more of love 😸 

1. `Paste special` appears as available even before I clicked on copy anything 👍 
2. On clicking on any element with the arrow, I was expecting to open it more than to mark it as checked. Also, when setting the cursor over the arrow there's no interaction and shows a normal cursor, not a pointer or clicking one. Strange user experience IMO
3. On changing the tab from `Settings` to `Advanced` sidebar also changes, is it expected?
4. Has been `cleanStyleAttributes` and `getOrganizedAttributes` tests updated with last updated object? Seem is the same 🤔 
5. Is it normal that, on a block where I just set a border, when I copy its styles and want to do a special paste on another block, all the options appears, even when they are the same? Video:

https://user-images.githubusercontent.com/50477222/170660551-9241cd2e-5710-4e5f-8e69-fc3ca85b586a.mp4

2022-05-30 13:19 UTC, elzadj approved these changes

2022-05-30 13:22 UTC, merged