Issue 3216 - indicators not updating
maxi-blocks/maxi-blocks pull request #3229
Opened 2022-05-26 17:12 UTC by myroslavve

# Description
Indicators were not rendering on breakpoint change. Did same fix as [here](https://github.com/yeahcan/maxi-blocks/pull/2880/commits/ca10c9f6f51178e46b6913720e5b32dd78c4dce4)

Fixes #3216 

# How Has This Been Tested?
Change padding and margin on different breakpoints. Switch between them and check if indicators update

# Test checklist

**_Front/Back Testing_**

-   [x] Check that indicators update

**_Pre-Code Testing_**

-   [x] Check that indicators update
-   [x] Check no commented code and no unnecessary imports
-   [x] Standards of the project have been followed
-   [x] No errors/warnings on console

# Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [x] New and existing unit tests pass locally with my changes

2022-05-27 08:29 UTC, Naaaaiix requested changes

2022-05-27 09:19 UTC, Naaaaiix approved these changes
Now it should work better without breaking the optimization. Thanks @TeksPeks 😸

2022-05-27 11:48 UTC, Fybex approved these changes

2022-05-30 12:52 UTC, elzadj approved these changes

2022-05-30 12:52 UTC, merged