Issue 3220 colour reset
maxi-blocks/maxi-blocks pull request #3235
Opened 2022-05-27 14:53 UTC by elzadj

# Description

Fixes various issues with Colour reset. 

Fixes #3220 

# How Has This Been Tested?

Basically, test all resets for Colour Controls.

# Test checklist

**_ Front/Back Testing _**

-   [x] Test the component in normal state in sidebar
-   [x] Test the component in hover state in sidebar
-   [x] Check that the settings work on frontend
-   [x] Check that backend works and saves the settings after the editor reload
-   [x] Same 1-4 points for the toolbar
-   [x] Same 1-4 points on responsive
- 
**_ Pre-Code Testing _**

-   [x] Test the component in normal state in sidebar
-   [x] Test the component in hover state in sidebar (if hover exists)
-   [x] Check that the settings work on frontend
-   [x] Check that backend works and saves the settings after the editor reload
-   [x] Same 1-4 points for the toolbar
-   [x] Same 1-4 points on responsive
-   [x] Check no commented code and no unnecessary imports
-   [x] Standards of the project have been followed
-   [x] No errors/warnings on console

# Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] My changes generate no new warnings/errors
-   [x] I have added/updated tests that prove my fix is effective or that my feature works
-   [x] New and existing unit tests pass locally with my changes

2022-05-28 07:11 UTC, Marko64 approved these changes

2022-05-30 12:00 UTC, myroslavve approved these changes

2022-05-31 11:10 UTC, Naaaaiix requested changes
Found a couple of small things 😸 👍

2022-05-31 13:06 UTC, Naaaaiix approved these changes
Once done with tests, this branch can be merged 👍  Good job 👏

2022-05-31 14:39 UTC, merged