Copy Past UI
maxi-blocks/maxi-blocks pull request #3247
Opened 2022-05-31 08:37 UTC by Rustam198804

# Description

Fixes #3211

2022-06-07 08:24 UTC, Marko64 approved these changes

2022-06-07 13:41 UTC, Fybex requested changes
When hover on text, which has nested options, hover for checkbox doesn't apply, and text colour different from texts without nested options
<img width="994" alt="copypaste-ui" src="https://user-images.githubusercontent.com/46112160/172393676-377dea6e-9b5d-48a4-bf69-a3231742f395.png">

2022-06-10 12:00 UTC, Fybex approved these changes

2022-06-13 08:26 UTC, Naaaaiix approved these changes
Looks good, thanks @Rustam198804 😸 

Found a small tiny thing I'll derive into a new issue, but is more related with the logics of the component than the styles, so is not related with this implementation 👍

2022-06-13 08:26 UTC, merged