issue 3274 max font size and line height
maxi-blocks/maxi-blocks pull request #3281
Opened 2022-06-06 11:48 UTC by Marko64

Updated max values for font size and line height from 99 to 300.
Changed the values in advanced-numer-control/index.js too, because otherwise changing unit wasn't working correctly due to values mismatch.

Fixes #3274

# How Has This Been Tested?

Tested text block, button block and image caption. Made sure font size and line height work. Tested SC too and responsive.

# Test checklist

**_ Front/Back Testing _**

-   [ ] Check all blocks that use typography and test font size and line height inputs. 
-   [ ] Test responsive for font size and line height.
-   [ ] Test that it works in SC settings too.

**_ Pre-Code Testing _**

-   [x] Check all blocks that use typography and test font size and line height inputs. 
-   [x] Test responsive for font size and line height.
-   [x] Test that it works in SC settings too.
-   [x] Check no commented code and no unnecessary imports
-   [x] Standards of the project have been followed
-   [x] No errors/warnings on console

# Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [x] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

2022-06-07 13:24 UTC, Rustam198804 approved these changes

2022-06-08 10:46 UTC, Fybex requested changes
When we are switching unit from 300px to %, unit doesn't change, not sure, maybe it should be fixed here to have correct switch unit work with new `minMaxSettings` straight away

2022-06-10 09:52 UTC, Fybex approved these changes
Amazing, all works, I had some problems with env again, after destroying and creating a new one all good

2022-06-13 11:00 UTC, Naaaaiix requested changes

2022-06-17 12:05 UTC, Naaaaiix approved these changes
There it is! 👏 lol

![](https://media.giphy.com/media/nbvFVPiEiJH6JOGIok/giphy.gif)

2022-06-17 12:05 UTC, merged