Adds transitions support to button's icon
maxi-blocks/maxi-blocks pull request #3296
Opened 2022-06-10 12:11 UTC by Naaaaiix

# Description

As @Olekrut requested, button's icon didn't have transition support. This implementation should deal with it 👍 

# How Has This Been Tested?

Create a Button, add an icon, enable hover options on icon and then play with the transitions on advanced tab 👍 

# Test checklist

**_ Front/Back Testing _**

-   [x] Test the component in normal state in sidebar
-   [x] Test the component in hover state in sidebar (if hover exists)
-   [x] Check that the settings work on frontend
-   [x] Check that backend works and saves the settings after the editor reload
-   [x] Same 1-4 points on responsive
-   [x] Test the block inside the grid (Container + Row + Column)
-   [x] Test the block as a standalone block
-   [x] Duplicate the block, test that the settings of the first do not affect the second
-   [x] Test with 2 blocks of the same type

**_ Pre-Code Testing _**

-   [x] Test the component in normal state in sidebar
-   [x] Test the component in hover state in sidebar (if hover exists)
-   [x] Check that the settings work on frontend
-   [x] Check that backend works and saves the settings after the editor reload
-   [x] Same 1-4 points on responsive
-   [x] Test the block inside the grid (Container + Row + Column)
-   [x] Test the block as a standalone block
-   [x] Duplicate the block, test that the settings of the first do not affect the second
-   [x] Test with 2 blocks of the same type
-   [x] Check no commented code and no unnecessary imports
-   [x] Standards of the project have been followed
-   [x] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

2022-06-10 12:33 UTC, Marko64 approved these changes

2022-06-10 13:00 UTC, Fybex requested changes
I think we need to add to targets `.maxi-button-block__icon` as well to have icon width hover transition

2022-06-13 11:26 UTC, Fybex approved these changes

2022-06-14 08:31 UTC, elzadj requested changes
Looks like need to add ```.maxi-button-block__icon svg``` to the targets, because width transition doesn't work without it:

https://user-images.githubusercontent.com/2401618/173531782-94e151cb-e1fe-40d0-b99a-f31f8ad4f267.mp4

2022-06-15 08:22 UTC, elzadj approved these changes

2022-06-15 08:23 UTC, merged