Issue 2451 php linter
maxi-blocks/maxi-blocks pull request #3298
Opened 2022-06-10 12:44 UTC by elzadj

# Description

Changes a bunch of php code all over the files for phpcs 

Fixes #2451 

# How Has This Been Tested?

Check that the plugin works in general and the debug log doesn't have any warnings / errors. Things to check: DB (especially on plugin activation), saving a post, changing SCs, adding blocks, the dashboard, fonts, styles on frontend

Please note that Image Crop doesn't seem to work on master too: https://github.com/yeahcan/maxi-blocks/issues/3295

# Test checklist

I recommend to clean your wp-env or remove the maxi tables manually, and them re-activate the plugin manually.

**_ Front/Back Testing _**

-   [x] Test adding maxi blocks
-   [x] Test saving a page 
-   [x] Test maxi blocks on frontend
-   [x] Test SCs (change the current one, load new, change the settings, etc.)
-   [x] Test SC on frontent
-   [x] Change various fonts (Text block, button, SC, etc.)
-   [x] Check fonts on frontend
-   [x] Check the Maxi's Dashboard (UI, settings)
-   [x] Check the debug.log for warnings / errors from maxi php files

**_ Pre-Code Testing _**

-   [x] Test adding maxi blocks
-   [x] Test saving a page 
-   [x] Test maxi blocks on frontend
-   [x] Test SCs (change the current one, load new, change the settings, etc.)
-   [x] Test SC on frontent
-   [x] Change various fonts (Text block, button, SC, etc.)
-   [x] Check fonts on frontend
-   [x] Check the Maxi's Dashboard (UI, settings)
-   [x] Check the debug.log for warnings / errors from maxi php files
-   [x] Check no commented code and no unnecessary imports
-   [x] Standards of the project have been followed
-   [x] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

2022-06-13 06:48 UTC, Marko64 requested changes
Tried everything from the checklist (adding blocks, changing settings, applying and changing SCs, changing dashboard settings), and everything seems to be OK. Had only one thing in the debug.log:

[11-Jun-2022 09:58:29 UTC] PHP Notice:  Undefined offset: 2 in /var/www/html/wp-content/plugins/maxi-blocks/core/class-maxi-local-fonts.php on line 152

The notice shows you enable "Serve Google fonts locally".

2022-06-14 07:08 UTC, Marko64 approved these changes
The local fonts option doesn't give the warning anymore. Tested changing fonts and typography on different screen sizes - works good (tested from SC settings and block settings).

2022-06-14 08:35 UTC, Fybex approved these changes

2022-06-14 14:58 UTC, Naaaaiix approved these changes
Coooooool! 😸

2022-06-15 08:21 UTC, merged