Issue 2935 - Interaction builder effects and new block selector
maxi-blocks/maxi-blocks pull request #3299
Opened 2022-06-10 13:17 UTC by Fybex

# Description

Changes:
- new block selector: block need to has custom Block name to be in the block selector dropdown
- added effects based on `TransitionControl`
- change `getClientIdFromUniqueId` function, not does not rely on DOM (had some problems with it on responsive, now fixed)

Fixes #

# How Has This Been Tested?

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test the effects
-   [ ] Test the block selector
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points on responsive (responsive on frontend works after reload!)

**_ Pre-Code Testing _**

-   [x] Test the effects
-   [x] Test the block selector
-   [x] Check that the settings work on frontend
-   [x] Check that backend works and saves the settings after the editor reload
-   [x] Same 1-4 points on responsive (responsive on frontend works after reload!)
-   [x] Check no commented code and no unnecessary imports
-   [x] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [X] My code follows the style guidelines of this project
-   [X] I have performed a self-review of my code
-   [X] I have commented my code, particularly in hard-to-understand areas
-   [X] My changes generate no new warnings/errors
-   [X] New and existing unit tests pass locally with my changes

2022-06-16 07:01 UTC, Marko64 approved these changes
I think this one can move forward. Looking forward seeing that other PR soon with the new implemenations.

2022-06-16 14:00 UTC, myroslavve requested changes

2022-06-17 07:05 UTC, myroslavve approved these changes

2022-06-17 11:16 UTC, Naaaaiix requested changes
Amazing! 👏  I love the way you use the `reduce` method on Arrays, is so clean and clever; I'll implement on my future code for sure! 🥳 

One thing I found:
On the frontend, js file doesn't adapt to the size of the screen. I mean, imagine visitors open the website on XL responsive stage, so the transitions created are for that responsive stage. Then, before triggering the effect, reduces the screen width to XS. The transitions, even considering on XS may are different, are going to be the XL ones as the file hasn't the support to change them in case visitors change the window size 👍

2022-06-17 16:34 UTC, Naaaaiix approved these changes
😻

2022-06-17 16:35 UTC, merged