Issue 3269 - FullWidth responsive support
maxi-blocks/maxi-blocks pull request #3312
Opened 2022-06-13 14:50 UTC by Fybex

# Description

Changes:
- `blockFullWidth`  and `fullWidth` attributes were replaced by `${prefix}-full-width-${breakpoint}` which are in `size` attributes group
- [data-align] element attribute was removed, now we are getting full-width from `getSizeStyles`, by setting `min-width: 100%`
- create `fullWidthNonToResponsive` migrator which prevent breaking already created blocks

Fixes #3269

# How Has This Been Tested?
Tested all blocks and their wrappers for correct responsive full width work, tested migrator correct work.

# Test checklist

**_ Front/Back Testing _**

-   [x] Test the component in normal state in sidebar
-   [ ] Test the migrator (create blocks on master, change full width settings, switch to this branch and check if everything if ok)
-   [x] Check that the settings work on frontend
-   [x] Check that backend works and saves the settings after the editor reload
-   [x] Same 1-4 points for the toolbar
-   [x] Same 1-4 points on responsive
-   [x] Test the block inside the grid (Container + Row + Column)
-   [x] Test the block as a standalone block
-   [x] Duplicate the block, test that the settings of the first do not affect the second
-   [x] Test with 2 blocks of the same type

**_ Pre-Code Testing _**

-   [ ] Test the component in normal state in sidebar
-   [ ] Test the migrator (create blocks on master, change full width settings, switch to this branch and check if everything if ok)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [X] My code follows the style guidelines of this project
-   [X] I have performed a self-review of my code
-   [X] My changes generate no new warnings/errors
-   [x] I have added/updated tests that prove my fix is effective or that my feature works
-   [X] New and existing unit tests pass locally with my changes

2022-06-14 09:28 UTC, Marko64 approved these changes

2022-06-14 15:46 UTC, FitseTLT approved these changes

2022-06-16 07:39 UTC, Naaaaiix requested changes
1. Even when we don't have any responsive setting for it, is it necessary? (Reminds me a bit to the situation we talked yesterday with the `transform: scale(1)` 🤔 )
<img width="769" alt="Captura de pantalla 2022-06-16 a las 9 12 35" src="https://user-images.githubusercontent.com/50477222/174013265-361c76b7-5467-47f3-bd3b-d5adedcc1c62.png">

2. Divider is not working correctly:

https://user-images.githubusercontent.com/50477222/174015844-9b6e0987-d04b-4673-9c29-8e080015c556.mp4

3. Full width attribute was a string with values like 'full' and 'normal' as they were related with the `data-align` thing. Maybe we should transform to a boolean, which has more sense now we removed `data-align`. Not sure if is something to implement on this branch as it is not strictly necessary for the moment, but in some moment we should migrate to it. What do you think?

2022-06-16 15:11 UTC, Naaaaiix approved these changes
Yeaaaaaaah! 🥳 Good job @Fybex 💪

2022-06-16 15:11 UTC, merged