Issue:3293 fixed shape scale bug for bg layers
maxi-blocks/maxi-blocks pull request #3314
Opened 2022-06-13 16:23 UTC by FitseTLT

# Description
fixed shape scale bug for bg layers

Fixes #3293 

# How Has This Been Tested?
Added shape bg layer set use bg image and then click down arrow key to decrease shape scale.

# Test checklist

**_ Front/Back Testing _**

-   [x] Test the component in normal state in sidebar
-   [x] Test the component in hover state in sidebar (if hover exists)
-   [x] Check that the settings work on frontend
-   [x] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [x] Same 1-4 points on responsive
-   [x] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type

**_ Pre-Code Testing _**

-   [x] Test the component in normal state in sidebar
-   [x] Test the component in hover state in sidebar (if hover exists)
-   [x] Check that the settings work on frontend
-   [x] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [x] Same 1-4 points on responsive
-   [x] Test the block inside the grid (Container + Row + Column)
-   [x] Test the block as a standalone block
-   [x] Duplicate the block, test that the settings of the first do not affect the second
-   [x] Test with 2 blocks of the same type
-   [x] Check no commented code and no unnecessary imports
-   [x] Standards of the project have been followed
-   [x] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

2022-06-14 06:45 UTC, Marko64 approved these changes
Fixed. 

Noticed that shape doesn't work for containers. Should I make a new issue for that, or you might want to fix it here?
![Screenshot_4](https://user-images.githubusercontent.com/19425503/173510879-b07f46cc-aa6e-4621-910f-e204d4ee74b6.jpg)

2022-06-14 08:16 UTC, myroslavve requested changes

2022-06-14 10:43 UTC, myroslavve approved these changes

2022-06-14 15:11 UTC, Naaaaiix requested changes
With the new implementation I'm finding many `transform: scale(1) ;` created with the `getImageShapeStyles`. I think in case we are having it, we shouldn't display, as it doesn't have much sense, and we can reduce the amount of CSS 👍

2022-06-16 12:49 UTC, Naaaaiix requested changes
Still having this thing with the unnecessary `scale(1)` and problems with the responsive 👍

2022-06-17 16:41 UTC, Naaaaiix approved these changes

2022-06-17 16:41 UTC, merged