Issue 3302: implemented bottom and top icon positions for button maxi
maxi-blocks/maxi-blocks pull request #3316
Opened 2022-06-13 19:09 UTC by FitseTLT

# Description
implemented bottom and top icon positions for button maxi

Fixes #3302

# How Has This Been Tested?
Checked top and bottom icon position and icon spacing.

# Test checklist

**_ Front/Back Testing _**

-   [x] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [x] Check that the settings work on frontend
-   [x] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type

**_ Pre-Code Testing _**

-   [x] Test the component in normal state in sidebar
-   [x] Test the component in hover state in sidebar (if hover exists)
-   [x] Check that the settings work on frontend
-   [x] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [x] Same 1-4 points on responsive
-   [x] Test the block inside the grid (Container + Row + Column)
-   [x] Test the block as a standalone block
-   [x] Duplicate the block, test that the settings of the first do not affect the second
-   [x] Test with 2 blocks of the same type
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

2022-06-14 06:33 UTC, Marko64 requested changes
Good work. A couple of things I noticed:

1. When you place the icon on the bottom, you can't see the text because of the icons' toolbar:
![Screenshot_1](https://user-images.githubusercontent.com/19425503/173508809-3a6440e6-ffd3-449b-b0b4-0c3481c7b3ab.jpg)

2. Toolbar needs the top and bottom options added too:
![Screenshot_2](https://user-images.githubusercontent.com/19425503/173508792-40caf470-b814-4b83-87ca-20165509dd77.jpg)

2022-06-15 10:09 UTC, Marko64 approved these changes
Moving this UI stuff into a new PR.

2022-06-15 12:27 UTC, myroslavve approved these changes

2022-06-16 11:10 UTC, Naaaaiix approved these changes
Cooooooool! 😎 good job @FitseTLT , please, fix the test and we can merge this branch 👍

2022-06-17 08:22 UTC, merged