Issue-3303: fixed minus sign problem on advanced number control
maxi-blocks/maxi-blocks pull request #3317
Opened 2022-06-13 19:50 UTC by FitseTLT

# Description
fixed minus sign problem on advanced number control

Fixes #3303

# How Has This Been Tested?
Tested on text-indent for list type text maxi by entering negative values

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type

**_ Pre-Code Testing _**

-   [x] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [x] Check that backend works and saves the settings after the editor reload
-   [x] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type
-   [x] Check no commented code and no unnecessary imports
-   [x] Standards of the project have been followed
-   [x] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

2022-06-14 06:26 UTC, Marko64 requested changes
Letter spacing in the toolbar isn't working (can't be negative):

![Screenshot_6](https://user-images.githubusercontent.com/19425503/173507903-2e828ff9-fb3c-445a-acad-e234887470bc.jpg)

2022-06-14 12:33 UTC, Marko64 requested changes
If you add a negative number in the sidebar, it gets the correct value in the toolbar too; however, you still can't add a negative number into the toolbar directly. If you use arrows, it want go beyond 0.

2022-06-20 09:35 UTC, Marko64 approved these changes
After today's meeting, we decided to move forward with this one.  Going to approve it and move FF and this decimal thing to a new issue.

2022-06-20 13:56 UTC, myroslavve approved these changes

2022-06-22 13:08 UTC, elzadj approved these changes

2022-06-22 13:09 UTC, merged