issue-3197-caption-input
maxi-blocks/maxi-blocks pull request #3341
Opened 2022-06-19 17:13 UTC by Marko64

- Added hover and focus border as we have in the Text Block
- Added 1px left padding on the backend only, so that the typing cursor is visible. It was currently there but sat behind the handlers border.

Fixes #3197

# How Has This Been Tested?

Add an image module and add a caption. 

# Test checklist

**_ Front/Back Testing _**

-   [ ] Check that the caption works and that it now has a border and the typing cursor.

**_ Pre-Code Testing _**

-   [ ] Check that the caption works and that it now has a border and the typing cursor.
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [x] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

2022-06-21 09:49 UTC, Rustam198804 approved these changes

2022-06-22 14:03 UTC, Fybex approved these changes

2022-06-22 15:02 UTC, elzadj requested changes

2022-06-23 08:46 UTC, elzadj approved these changes
Thank you @Marko64 !

2022-06-23 08:49 UTC, merged