Migrators fix
maxi-blocks/maxi-blocks pull request #3353
Opened 2022-06-21 09:08 UTC by Fybex

# Description

What was fixed:
- disappearing `position` attributes after migrate
- disappearing `position` attributes on reload 

The problem was in the fact that we were developing two migrators at one time, and `fullWidthNonToResponsive` migrator was deleting position old attributes before `positionMigrator`, so now we have one migrator `blockMigrator`, which combines `positionMigrator` and `fullWidthNonToResponsive` migrator. Another problem with disappearing `position` attributes on reload was related with not checking attribute value in `unitChecker`, and because of this migrator was running   after every reload.

# How Has This Been Tested?
Tested if position attributes not disappear after save and reload, tested if migrators works fine(switched to some old branch, created there blocks with position and full width attributes, switched back here and checked if everything fine after one save, and more)

# Test checklist

**_ Front/Back Testing _**

-   [x] Test if we haven't disappearing position attributes on save and reload
-   [x] Test if `blockMigrator` works as it needed (position, full-width)
-   [x] Test migrators with maxi-dress local clone
-   [x] Check that the settings work on frontend
-   [x] Check that backend works and saves the settings after the editor reload
-   [x] Same 1-4 points on responsive
-   [x] Test the block inside the grid (Container + Row + Column)
-   [x] Test the block as a standalone block
-   [x] Duplicate the block, test that the settings of the first do not affect the second
-   [x] Test with 2 blocks of the same type

**_ Pre-Code Testing _**

-   [x] Test if we haven't disappearing position attributes on save and reload
-   [x] Test if `blockMigrator` works as it needed (position, full-width)
-   [x] Test migrators with maxi-dress local clone
-   [x] Test if `blockMigrator` works only when it must
-   [x] Check that the settings work on frontend
-   [x] Check that backend works and saves the settings after the editor reload
-   [x] Same 1-4 points on responsive
-   [x] Test the block inside the grid (Container + Row + Column)
-   [x] Test the block as a standalone block
-   [x] Duplicate the block, test that the settings of the first do not affect the second
-   [x] Test with 2 blocks of the same type
-   [x] Check no commented code and no unnecessary imports
-   [x] Standards of the project have been followed
-   [x] No errors/warnings on console

# Checklist

-   [X] My code follows the style guidelines of this project
-   [X] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [X] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [X] New and existing unit tests pass locally with my changes

2022-06-22 10:41 UTC, Marko64 approved these changes
Ah, as it has happened before, now it works for me too. I think I tried 3 times before this and wasn't working and now it works lol

2022-06-22 12:07 UTC, Rustam198804 approved these changes

2022-06-22 12:24 UTC, FitseTLT approved these changes

2022-06-22 12:46 UTC, elzadj approved these changes

2022-06-22 13:09 UTC, myroslavve requested changes
Everything works fine for me 👍 . Just one little thing

2022-06-22 13:49 UTC, myroslavve approved these changes

2022-06-23 08:38 UTC, Naaaaiix approved these changes
Yeaaaaah! 👏

2022-06-23 08:39 UTC, merged