Issue-2900: fixed font-weight issue on NC
maxi-blocks/maxi-blocks pull request #3361
Opened 2022-06-21 19:42 UTC by FitseTLT

# Description
fixed font-weight issue on Number Counter

Fixes #2900

# How Has This Been Tested?
Checked font weight for number counter (also responsive).

# Test checklist

**_ Front/Back Testing _**

-   [x] Test the component in normal state in sidebar
-   [x] Test the component in hover state in sidebar (if hover exists)
-   [x] Check that the settings work on frontend
-   [x] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [x] Same 1-4 points on responsive
-   [x] Test the block inside the grid (Container + Row + Column)
-   [x] Test the block as a standalone block
-   [x] Duplicate the block, test that the settings of the first do not affect the second
-   [x] Test with 2 blocks of the same type

**_ Pre-Code Testing _**

-   [ ] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

2022-06-22 12:48 UTC, Marko64 approved these changes

2022-06-22 13:46 UTC, Fybex requested changes
Displayed font-weight in sidebar 100 by default, but NC text hasn't font-weight by default. So I think it should display in sidebar 400 by default 🤔

2022-06-23 11:27 UTC, Fybex requested changes
It should display 400 by default, as it does now, but I think we shouldn't add this unnecessary CSS code if font-weight default.

2022-06-23 12:10 UTC, Fybex approved these changes

2022-06-27 10:10 UTC, merged