Issue 3364 - Transform origin fix
maxi-blocks/maxi-blocks pull request #3369
Opened 2022-06-22 11:19 UTC by Fybex

# Description

Fixes #3364 

# How Has This Been Tested?
Changed transition-origin settings and checked if it works fine

# Test checklist

**_ Front/Back Testing _**

-   [x] Test the component in normal state in sidebar
-   [x] Check that the settings work on frontend
-   [x] Check that backend works and saves the settings after the editor reload
-   [x] Same 1-4 points on responsive
-   [x] Test the block inside the grid (Container + Row + Column)
-   [x] Test the block as a standalone block

**_ Pre-Code Testing _**

-   [x] Test the component in normal state in sidebar
-   [x] Check that the settings work on frontend
-   [x] Check that backend works and saves the settings after the editor reload
-   [x] Same 1-4 points on responsive
-   [x] Test the block inside the grid (Container + Row + Column)
-   [x] Test the block as a standalone block
-   [x] Check no commented code and no unnecessary imports
-   [x] Standards of the project have been followed
-   [x] No errors/warnings on console

# Checklist

-   [X] My code follows the style guidelines of this project
-   [X] I have performed a self-review of my code
-   [X] My changes generate no new warnings/errors
-   [x] I have added/updated tests that prove my fix is effective or that my feature works
-   [X] New and existing unit tests pass locally with my changes

2022-06-22 13:15 UTC, Marko64 approved these changes
Works correctly now. Not sure if related and if it's even a bug, but we have no dot in the center:
![Screenshot_3](https://user-images.githubusercontent.com/19425503/175038096-985b058b-6788-43a7-96a2-799b6640604e.jpg)

2022-06-22 13:53 UTC, myroslavve approved these changes

2022-06-22 14:47 UTC, elzadj requested changes
Need the dot in the center, and we've lost units for the custom values, I'm getting 
```
transform-origin: 54null -27.5null;
```

2022-06-22 19:39 UTC, Naaaaiix approved these changes

2022-06-23 08:20 UTC, elzadj approved these changes

2022-06-23 08:20 UTC, merged