Issue:3371 fix range control issue
maxi-blocks/maxi-blocks pull request #3376
Opened 2022-06-22 21:00 UTC by FitseTLT

# Description
Range control was breaking because of changes made in #3207, so reverted that change.

Fixes #3371

# How Has This Been Tested?
Checked the range control is displaying the right value.

# Test checklist

**_ Front/Back Testing _**

-   [x] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [x] Check that the settings work on frontend
-   [x] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [x] Same 1-4 points on responsive
-   [x] Test the block inside the grid (Container + Row + Column)
-   [x] Test the block as a standalone block
-   [x] Duplicate the block, test that the settings of the first do not affect the second
-   [x] Test with 2 blocks of the same type

**_ Pre-Code Testing _**

-   [ ] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

2022-06-23 05:46 UTC, Fybex requested changes
When you set 0 on advanced-number-control with `||` in check, it will ignore 0 value, for example you can check transition-duration:
<img width="287" alt="image" src="https://user-images.githubusercontent.com/46112160/175222201-3d95eff7-1124-4eb5-9038-7c1de01d2574.png">

2022-06-23 12:01 UTC, Marko64 approved these changes

2022-06-23 12:13 UTC, Fybex approved these changes

2022-06-27 08:34 UTC, Naaaaiix approved these changes

2022-06-27 08:34 UTC, merged