Issue 3372 - Overflow responsive default fix
maxi-blocks/maxi-blocks pull request #3379
Opened 2022-06-23 08:18 UTC by Fybex

# Description

All html elements have overflow visible by default, so I've decided to remove default option from options, because it hasn't sense and not working on responsive. Now we have overflow visible by default.

Changes:
- removed default option
- set overflow attributes visible by default
- ensured that we are not adding unnecessary css (because of setting visible overflow as default)
- added unit tests

Fixes #3372 

# How Has This Been Tested?

# Test checklist

**_ Front/Back Testing _**

-   [x] Test the component in normal state in sidebar
-   [x] Check that the settings work on frontend
-   [x] Check that backend works and saves the settings after the editor reload
-   [x] Same 1-4 points on responsive
-   [x] Test the block inside the grid (Container + Row + Column)
-   [x] Test the block as a standalone block

**_ Pre-Code Testing _**

-   [ ] Test the component in normal state in sidebar
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [X] My code follows the style guidelines of this project
-   [X] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [X] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [X] New and existing unit tests pass locally with my changes

2022-06-23 11:52 UTC, Marko64 approved these changes

2022-06-23 15:40 UTC, FitseTLT requested changes
What about following the idea I used here?
https://github.com/yeahcan/maxi-blocks/blob/dd6731615f7026d8f887185b5285490be8ee4857/src/extensions/styles/helpers/getImageShapeStyles.js#L21-L55
It will be more effective then no need for another loop to check if the style is needed and also  for instance M breakpoint style will not affect L screen sizes so no need to add style for L if only M overflow is changed and so on.

2022-06-24 09:55 UTC, FitseTLT requested changes

2022-06-24 11:30 UTC, FitseTLT approved these changes

2022-06-27 09:05 UTC, elzadj requested changes
ignore, was some sort of a weird local glitch 

=============================


All is good, but I think we need to add 
clip;
scroll;

to the options too.
Or maybe just all possible values https://developer.mozilla.org/en-US/docs/Web/CSS/overflow#syntax

2022-06-27 11:16 UTC, elzadj approved these changes

2022-06-27 11:16 UTC, merged