WP 6.0
maxi-blocks/maxi-blocks pull request #3387
Opened 2022-06-23 14:00 UTC by Naaaaiix

# Description

This branch updates wp-env WP version to 6.0

# How Has This Been Tested?

We've been already using Maxi on WP 6.0 (learndd and maxidress); this implementation deals more with the e2e tests

# Test checklist

**_ Front/Back Testing _**

-   [x] Test current patterns doesn't break and Maxi works good in general

**_ Pre-Code Testing _**

-   [ ] Test current patterns doesn't break and Maxi works good in general
-   [x] Check no commented code and no unnecessary imports
-   [x] Standards of the project have been followed
-   [x] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

2022-06-28 11:39 UTC, Marko64 approved these changes

2022-06-28 12:08 UTC, myroslavve requested changes
Hero light 34 gives validation error: 
```
Block validation: Expected attributes 
(2) [Array(3), Array(3)]
0: (3) ['class', 'wp-block-maxi-blocks-container-maxi maxi-block max…er-maxi-1331342 maxi-light container-maxi-1331342', true]
1: (3) ['id', 'container-maxi-1331342', true]
, instead saw 
(3) [Array(3), Array(3), Array(3)]
0: (3) ['class', 'wp-block-maxi-blocks-container-maxi maxi-block max…er-maxi-1331342 maxi-light container-maxi-1331342', true]
1: (3) ['data-align', 'full', true]
2: (3) ['id', 'container-maxi-1331342', true]
```

![image](https://user-images.githubusercontent.com/53875005/176173760-6fa675cc-6ea6-4cc9-9c92-2752368f3646.png)

On wp 5.9 migrator works fine, something with wp 6

2022-07-05 11:19 UTC, myroslavve approved these changes

2022-07-05 12:05 UTC, elzadj approved these changes

2022-07-05 12:06 UTC, merged