Issue3386 set rotation range to be -360 to 360
maxi-blocks/maxi-blocks pull request #3395
Opened 2022-06-24 20:25 UTC by FitseTLT

# Description
For transform control set rotation range to be -360 to 360

Fixes #3386 

# How Has This Been Tested?
checked the transform control rotation works with the new range.

# Test checklist

**_ Front/Back Testing _**

-   [x] Test the component in normal state in sidebar
-   [x] Test the component in hover state in sidebar (if hover exists)
-   [x] Check that the settings work on frontend
-   [x] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [x] Same 1-4 points on responsive
-   [x] Test the block inside the grid (Container + Row + Column)
-   [x] Test the block as a standalone block
-   [x] Duplicate the block, test that the settings of the first do not affect the second
-   [x] Test with 2 blocks of the same type

**_ Pre-Code Testing _**

-   [ ] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [x] Check that the settings work on frontend
-   [x] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

2022-06-27 06:58 UTC, Marko64 approved these changes

2022-06-27 08:44 UTC, myroslavve requested changes
I can't type in negative numbers

https://user-images.githubusercontent.com/53875005/175898076-3007af9b-e8c6-4389-b65e-aa785d554cf5.mp4

2022-06-27 12:53 UTC, myroslavve approved these changes

2022-06-28 10:40 UTC, elzadj approved these changes

2022-06-28 10:40 UTC, merged