Issue 3384 added inset for box-shadow
maxi-blocks/maxi-blocks pull request #3402
Opened 2022-06-27 21:24 UTC by FitseTLT

# Description
added inset option for box-shadow

Fixes #3384

# How Has This Been Tested?
Tested inset for box-shadow both hover and responsiveness.

# Test checklist

**_ Front/Back Testing _**

-   [x] Test the component in normal state in sidebar
-   [x] Test the component in hover state in sidebar (if hover exists)
-   [x] Check that the settings work on frontend
-   [x] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [x] Test the block inside the grid (Container + Row + Column)
-   [x] Test the block as a standalone block
-   [x] Duplicate the block, test that the settings of the first do not affect the second
-   [x] Test with 2 blocks of the same type

**_ Pre-Code Testing _**

-   [ ] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

2022-06-28 06:51 UTC, Marko64 requested changes
https://user-images.githubusercontent.com/19425503/176112607-7726c2c9-270a-45d7-bb18-efffc8bb29e8.mp4

2022-06-28 11:44 UTC, Marko64 approved these changes

2022-06-28 13:03 UTC, Fybex requested changes
Would be great to have unit test updated with new box-shadow features 👍🏿

2022-06-29 07:14 UTC, Fybex approved these changes
Better now

2022-06-29 12:28 UTC, elzadj approved these changes

2022-06-29 12:29 UTC, merged