Issue 3377 - fix line radius switch
maxi-blocks/maxi-blocks pull request #3403
Opened 2022-06-28 07:55 UTC by myroslavve

# Description

Fixes #3377 

# How Has This Been Tested?
Turn that switch on and off check if it works.

# Test checklist

**_Front/Back Testing_**

-   [x] Test the component in normal state in sidebar
-   [x] Check that the settings work on frontend
-   [x] Check that backend works and saves the settings after the editor reload
-   [x] Same 1-3 points on responsive

**_Pre-Code Testing_**

-   [ ] Test the component in normal state in sidebar
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-3 points on responsive
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [x] New and existing unit tests pass locally with my changes

2022-06-28 08:12 UTC, Marko64 requested changes
The issue has been fixed. Noticed that the radius doesn't work on responsive. The toggle switch saves, but the line doesn't change.

2022-06-28 11:48 UTC, Marko64 approved these changes

2022-06-28 20:19 UTC, FitseTLT approved these changes

2022-06-29 12:03 UTC, elzadj approved these changes

2022-06-29 12:03 UTC, merged