Issue 3381 - Blinking transitions
maxi-blocks/maxi-blocks pull request #3411
Opened 2022-06-29 06:19 UTC by Fybex

# Description

Added `-webkit-transform: translate3d(0,0,0)` on image layer opacity

Fixes #3381 

# How Has This Been Tested?
Tested image layer functions on this [code_editor](https://github.com/yeahcan/maxi-blocks/files/9007668/blinking.txt), if they work as before, but without blinking on hover

# Test checklist

**_ Front/Back Testing _**

-   [x] Test if we haven't blinking any more
-   [x] Test if other image layers functions works as they were
-   [x] Check that the settings work on frontend
-   [x] Check that backend works and saves the settings after the editor reload
-   [x] Same 1-4 points on responsive
-   [x] Test the block inside the grid (Container + Row + Column)
-   [x] Test the block as a standalone block

**_ Pre-Code Testing _**

-   [ ] Test if we haven't blinking any more
-   [ ] Test if other image layers functions works as they were
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [X] My code follows the style guidelines of this project
-   [X] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [X] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [X] New and existing unit tests pass locally with my changes

2022-06-29 07:23 UTC, Marko64 approved these changes
I think this is worth re-checking one day when we have more time to deal with it. It is fine for now.

2022-06-29 10:07 UTC, FitseTLT requested changes
Still happening for me in frontend.
https://user-images.githubusercontent.com/38649957/176410965-cf962e58-a3fa-4d83-8a3b-c36d555a5b64.mp4

2022-06-30 14:11 UTC, FitseTLT approved these changes

2022-06-30 15:07 UTC, Naaaaiix reviewed
Going to say something that maybe is ridiculously simple and I didn't see it, but... why don't we add this `-webkit-transform: translate3d(0,0,0);` property directly in the static CSS instead of creating it dynamically when creating the styles? Don't kill me if it's so obvious lol 

In other order of things: yesterday on the meeting I said I remember some article about this glitch and found it. Here it talks about [this flickering error](https://maximelafarie.com/avoid-css-flickering) that I couldn't reproduce (on the website shared they say that if you hover on the images you can experience it: I can't! lol)
As I've been reading, is related with the computer performance. CSS property like `will-change` are used to prepare/notify to the hardware that a change is coming so need can optimize the resource for that action. [This stackoverflow answer](https://stackoverflow.com/a/43046569) talks about other options, and I think we need to think in terms of performance in this concrete case, as seems a problem with [GPU and WebGPU pergormance](https://bugs.chromium.org/p/chromium/issues/detail?id=961777&q=flick%20transition&can=2). 👍

2022-07-01 11:18 UTC, merged