Issue 3333 - video take 2
maxi-blocks/maxi-blocks pull request #3420
Opened 2022-07-01 07:45 UTC by myroslavve

# Description
Added icon hover, icon position for close button, moved settings to new tabs, moved image upload from inspector to block. 

Fixes #3333 

# How Has This Been Tested?
Test icon hover, icon position, and check other settings work as they should.

# Test checklist

**_Front/Back Testing_**

-   [ ] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type

**_Pre-Code Testing_**

-   [ ] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

2022-07-01 08:20 UTC, Marko64 requested changes
- Sidebar block info is messed up:
![Screenshot_1](https://user-images.githubusercontent.com/19425503/176853649-c6b88706-9f2e-4cda-bc9e-51385a95adc2.jpg)

- When the video is pop-up, the cursor is the pointer even the entire video is clickable. Let's change to the hand cursors instead.

- The close button is constantly in the hover colour.

2022-07-01 13:23 UTC, Marko64 approved these changes

2022-07-04 10:39 UTC, FitseTLT approved these changes

2022-07-04 11:12 UTC, Naaaaiix reviewed
Please @TeksPeks, fix the tests 🙏

2022-07-05 11:51 UTC, Naaaaiix approved these changes
Awesome; just a movement of a line and can be merged 👏 🥳

2022-07-05 14:56 UTC, merged