Add video-overlay-control test
maxi-blocks/maxi-blocks pull request #3421
Opened 2022-07-01 10:03 UTC by Alejandro9kgm

In this pr the tests for video-overlay-control are added.

2022-07-04 08:01 UTC, Fybex requested changes
All good, just one minor thing

2022-07-04 10:55 UTC, Fybex approved these changes

2022-07-05 15:00 UTC, Naaaaiix requested changes

2022-07-11 09:59 UTC, Naaaaiix requested changes

2022-07-12 10:47 UTC, Naaaaiix approved these changes

2022-07-12 10:47 UTC, merged