Issue 3266 transitions info box
maxi-blocks/maxi-blocks pull request #3427
Opened 2022-07-03 21:28 UTC by Marko64

Added a link to the transition panel for every hover setting in the sidebar. 
![Screenshot_1](https://user-images.githubusercontent.com/19425503/177057698-2a25fbe8-5686-4df9-a5ee-f31072cafc63.jpg)

Fixes #3266

# How Has This Been Tested?

Checked that all hover settings have the link and that the link works.

# Test checklist

**_ Front/Back Testing _**

-   [ ] Check every block and make sure that every hover option has the link that takes to the advanced tab > hover transitions.
-   [ ] Check that remembering the last opened settings tab/panel still works. Add a block, open a random settings panel, then navigate off the block and click on it again. It needs to show the settings you had opened previously. Add multiple blocks and ensure the same.

**_ Pre-Code Testing _**

- [ ] Check every block and make sure that every hover option has the link that takes to the advanced tab > hover transitions.
-   [ ] Check that remembering the last opened settings tab/panel still works. Add a block, open a random settings panel, then navigate off the block and click on it again. It needs to show the settings you had opened previously. Add multiple blocks and ensure the same.
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

2022-07-06 07:40 UTC, Rustam198804 approved these changes

2022-07-07 13:29 UTC, FitseTLT approved these changes
It would make sense if U click on the manage transition option on a specific style like border it will open the transition options for the border. maybe for the future.

2022-07-11 08:15 UTC, elzadj requested changes

2022-07-11 14:34 UTC, elzadj approved these changes

2022-07-12 11:24 UTC, merged