Automatic labels to blocks #3351
maxi-blocks/maxi-blocks pull request #3455
Opened 2022-07-06 19:32 UTC by FitseTLT

# Description
Added automatic labels to blocks

Fixes #3351

# How Has This Been Tested?
Checked automatic labels in these cases: Added new blocks, duplicate a block, added row patterns in container maxi and check the labels for columns.

# Test checklist

**_ Front/Back Testing _**

-   [x] Checked automatic labels in these cases: Added new blocks, duplicate a block, added row patterns in container maxi and check the labels for columns.

**_ Pre-Code Testing _**

-   [ ] Checked automatic labels in these cases: Added new blocks, duplicate a block, added row patterns in container maxi and check the labels for columns.
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

2022-07-07 07:24 UTC, Marko64 reviewed
This works. 

One question only: are we now just randomizing the number added to the label? Feels a bit odd that when you insert a module it has a label _420 or something. But if that's the easiest/best we can do for now, it's ok.

2022-07-07 07:25 UTC, Marko64 approved these changes

2022-07-07 13:07 UTC, Fybex requested changes
the customLabel attribute is now the same in all blocks, so we can move it to global to avoid unnecessary repetition

2022-07-08 12:01 UTC, Fybex requested changes
Sorry, that I didn't write it in first review, one more minor thing

2022-07-11 11:48 UTC, Fybex approved these changes

2022-07-12 11:53 UTC, elzadj approved these changes

2022-07-12 11:55 UTC, merged