issue-3374-caption
maxi-blocks/maxi-blocks pull request #3456
Opened 2022-07-07 09:05 UTC by Marko64

- Removed link from the caption toolbar and link options from the sidebar.
- Increased the new format value timeout to fix the speed of typing and deleting. If I understand the code, we are setting the new caption value when you stop typing. Is that how it must work or we can trigger the change on a different event?

Fixes #3374

# Test checklist

**_ Front/Back Testing _**

-   [ ] Make sure the caption toolbar doesn't have the link option anymore and that the link options do not show in the sidebar.
-   [ ] Compare with master and make sure caption speed is better. Try top and bottom caption.

**_ Pre-Code Testing _**

-   [ ] Make sure the caption toolbar doesn't have the link option anymore and that the link options do not show in the sidebar.
-   [ ] Compare with master and make sure caption speed is better. Try top and bottom caption.
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [x] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

2022-07-07 10:38 UTC, Rustam198804 approved these changes

2022-07-07 13:16 UTC, FitseTLT approved these changes

2022-07-11 08:24 UTC, elzadj requested changes
The speed is much better, but it's still noticeably slower than the Text's. Maybe @Naaaaiix has some recommendations?

2022-07-12 08:03 UTC, elzadj approved these changes

2022-07-12 08:03 UTC, merged