Number Counter Enhancements #2982
maxi-blocks/maxi-blocks pull request #3463
Opened 2022-07-08 20:09 UTC by FitseTLT

# Description
- Re-implemented NC animation both in backend and frontend. The previous implementation was wrong.
- Implemented the Offset option for view on scroll animation option which will decide what percent of the window the NC top should reach to trigger the animation.
- Also changed the range of the end number to be 9999999999 b/c in most practical cases in websites I see people use NC for showing likes, follows, subscribers etc which is a large in number.

Fixes #2982

# How Has This Been Tested?
Tested NC both for animation options and offset

# Test checklist

**_ Front/Back Testing _**

-   [x] Tested NC both for animation options and offset
-  [x] Test the component in normal state in sidebar
-   [x] Check that the settings work on frontend

**_ Pre-Code Testing _**

-   [ ] Tested NC both for animation options and offset
-  [ ] Test the component in normal state in sidebar
-   [ ] Check that the settings work on frontend
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

2022-07-11 10:47 UTC, Marko64 approved these changes

2022-07-12 12:00 UTC, Fybex requested changes
Replay button works only one time, every time when I reach offset value number-counter replays, should it like this? Video:

https://user-images.githubusercontent.com/46112160/178485094-9b11c3c6-1d84-4677-9ac6-84458b525db4.mp4

2022-07-13 13:47 UTC, Fybex requested changes
Replay button from toolbar still works only once

2022-07-14 08:49 UTC, Fybex approved these changes

2022-07-19 09:08 UTC, elzadj approved these changes

2022-07-19 09:36 UTC, merged