Box-shadow is working, not correct. #3468
maxi-blocks/maxi-blocks pull request #3470
Opened 2022-07-11 20:00 UTC by FitseTLT

# Description
Fixed Box-shadow issues for clip-path and image shape
Allowed negative values for box-shadow settings

Fixes #3468 

# How Has This Been Tested?
Checked box-shadow for normal and hover state is working right for image with clip-path and SVG mask.

# Test checklist

**_ Front/Back Testing _**

-   [x] Check box-shadow for normal and hover state is working right for image with clip-path and SVG mask.
-   [x] Test the component in normal state in sidebar
-   [x] Test the component in hover state in sidebar (if hover exists)
-   [x] Check that the settings work on frontend
-   [x] Check that backend works and saves the settings after the editor reload
-   [x] Same 1-4 points for the toolbar
-   [x] Same 1-4 points on responsive
-   [x] Test the block inside the grid (Container + Row + Column)
-   [x] Test the block as a standalone block
-   [x] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type

**_ Pre-Code Testing _**

-   [x] Checked box-shadow for normal and hover state is working right for image with clip-path and SVG mask.
-   [x] Test the component in normal state in sidebar
-   [x] Test the component in hover state in sidebar (if hover exists)
-   [x] Check that the settings work on frontend
-   [x] Check that backend works and saves the settings after the editor reload
-   [x] Same 1-4 points for the toolbar
-   [x] Same 1-4 points on responsive
-   [x] Test the block inside the grid (Container + Row + Column)
-   [x] Test the block as a standalone block
-   [x] Duplicate the block, test that the settings of the first do not affect the second
-   [x] Test with 2 blocks of the same type
-   [x] Check no commented code and no unnecessary imports
-   [x] Standards of the project have been followed
-   [x] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

2022-07-12 06:00 UTC, Marko64 requested changes
Box shadow works with shape, but not with clip path for me:

![Screenshot_1](https://user-images.githubusercontent.com/19425503/178419521-68866ae3-1452-450d-ace4-362b9e7acbb2.jpg)

2022-07-14 08:03 UTC, Marko64 approved these changes
Works. Noticed only that the box-shadow doesn't have a transition. Not sure if it's related to this PR.

2022-07-18 08:21 UTC, myroslavve requested changes

2022-07-18 10:46 UTC, myroslavve approved these changes

2022-07-19 08:53 UTC, elzadj approved these changes

2022-07-19 08:53 UTC, merged