Loading indicator for local fonts #2854
maxi-blocks/maxi-blocks pull request #3477
Opened 2022-07-13 21:01 UTC by FitseTLT

# Description
implemented font download notice

Fixes #2854

# How Has This Been Tested?
Check font downloading notices both in success and fail state.

# Test checklist

**_ Front/Back Testing _**

-   [x] Check font downloading notices both in success and fail state.

**_ Pre-Code Testing _**

-   [x] Check font downloading notices both in success and fail state.

-   [x] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

2022-07-14 11:30 UTC, Marko64 reviewed
I'm not sure what we are getting with this.
- If you select the same font multiple times it will always say "font downloaded". Is that correct?
- As soon as you open SC, it says "font downloaded".
- When you change the font in the SC manager, it has "font downloaded" 2 times.

Thinking out loud, people may be worried if they are downloading something unnecessary and storing it somewhere on the server.

How can I recreate the original issue for which we decided this notice would come in handy?

2022-07-15 07:21 UTC, Marko64 approved these changes
I think that's better, thanks.

2022-07-18 07:32 UTC, myroslavve approved these changes

2022-07-21 11:54 UTC, elzadj requested changes
I don't think the loading indicator works at all. 

When I save a page, it updates right away, and then the frontend fonts are broken for some time, because maxi still downloads them. And I need to w8 and hit f5 several times too see the new fonts.

Ideally the indicator should be shown after user hits Update. And the "Page Updated" messages should be on hold until all the fonts are ready.
[video-10085862-8b4c9aedabf63604dd505a2a7ef0df53.webm](https://user-images.githubusercontent.com/2401618/180207660-d4393c43-9a49-4619-8727-559657a350ea.webm)

2023-09-14 15:39 UTC, closed without merging