Issue 3436: implemented forbidding nested links
maxi-blocks/maxi-blocks pull request #3483
Opened 2022-07-15 16:17 UTC by FitseTLT

# Description
implemented forbidding nested links by disabling to have links on parent blocks when child block has a link.
removed unnecessary imports in attributes.js of all blocks

Fixes #3436

# How Has This Been Tested?
Check that parent block can't have a link when any child has one.

# Test checklist

**_ Front/Back Testing _**

-   [x] implemented forbidding nested links by disabling to have links on parent blocks when child block has a link.

**_ Pre-Code Testing _**

-   [ ] implemented forbidding nested links by disabling to have links on parent blocks when child block has a link.
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

2022-07-16 07:20 UTC, Marko64 approved these changes
This solution is fine with me.

2022-07-19 08:17 UTC, Fybex requested changes
When I set a link to text-maxi, I can set a link for the parent, but I should not, should I? (maybe related with fact that I don't see change of link toolbar icon colour to orange)

Should we also turn off ability of setting link to child if parent has link, what do you think? @FitseTLT, @Naaaaiix, @Marko64

2022-07-26 07:51 UTC, Fybex approved these changes

2022-07-27 09:30 UTC, Olekrut approved these changes

2022-07-29 10:02 UTC, elzadj approved these changes

2022-07-29 10:02 UTC, merged