Text selected when changing settings in the toolbar #3432
maxi-blocks/maxi-blocks pull request #3484
Opened 2022-07-15 21:03 UTC by FitseTLT

# Description
fixed the text selection issue on changing prop from toolbar
fixes on the memory leak warning of the toolbar popover

Fixes #3432 

# How Has This Been Tested?
tested the text is not selected on changing settings from toolbar

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type

**_ Pre-Code Testing _**

-   [ ] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [x] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

2022-07-25 10:00 UTC, Marko64 approved these changes

2022-07-25 10:26 UTC, myroslavve requested changes
Found same thing in caption toolbar of image.

https://user-images.githubusercontent.com/53875005/180755217-271a384c-517a-4cb4-9b5c-809a06dedd0f.mp4

I believe the problem is also with `newFormatValue`, but in this file:
`src\components\toolbar\captionToolbar.js`

2022-07-25 11:22 UTC, myroslavve approved these changes

2022-07-26 07:35 UTC, Naaaaiix reviewed
The fix is correct, but maybe there's a higher optimization. I mean, all the code implemented is a modification of the FormatValue retuned from `setFormat`. Could it be better to modify the function to return the original `start` and `end` instead of modifying the returned object every time we request it? 🤔

2022-07-27 09:28 UTC, Naaaaiix approved these changes

2022-07-27 09:55 UTC, merged