Cloud UI
maxi-blocks/maxi-blocks pull request #3497
Opened 2022-07-20 10:52 UTC by Rustam198804

# Description

Fixed some small UI bugs for template library.  only couldn't repeat the bug related with the close icon

Fixes #3495 

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type

**_ Pre-Code Testing _**

-   [ ] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

2022-07-20 11:47 UTC, Marko64 approved these changes

2022-07-22 09:07 UTC, Fybex approved these changes

2022-07-22 09:40 UTC, elzadj requested changes
The fixes are great, I've found some other small bugs, let's fix that too:

- This is weird:
[video-10105334-09c03981d84ba6cd73ea28a78f134c7a.webm](https://user-images.githubusercontent.com/2401618/180411473-4da0b92b-f529-48f6-a860-5447038afd1e.webm)
 

- This feels off: 
![Edit Page ‹ Local Wordpress — WordPress (37)](https://user-images.githubusercontent.com/2401618/180411512-ef346b53-607a-49e9-bf06-34c7e87775d9.jpg)

-  The placeholder looks broken:
![Edit Page ‹ Local Wordpress — WordPress (38)](https://user-images.githubusercontent.com/2401618/180411650-f836f127-26eb-42fc-8792-a7164fac14bc.jpg)

2022-07-26 12:49 UTC, elzadj reviewed
Just a small change, and we can merge @Rustam198804

2022-07-29 10:45 UTC, elzadj approved these changes

2022-07-29 10:46 UTC, merged