Issue 3480: Fixed button issues
maxi-blocks/maxi-blocks pull request #3505
Opened 2022-07-25 09:47 UTC by FitseTLT

# Description
Fixed both #3480 #3499 
Fixed icon inherit issue for icon stroke both normal and hover state

Fixes #3480 #3499 

# How Has This Been Tested?
Check both issues are fixed and icon inherit is working for icon stroke color.

# Test checklist

**_ Front/Back Testing _**

-   [x] Test the component in normal state in sidebar
-   [x] Test the component in hover state in sidebar (if hover exists)
-   [x] Check that the settings work on frontend
-   [x] Check that backend works and saves the settings after the editor reload
-   [x] Same 1-4 points for the toolbar
-   [x] Same 1-4 points on responsive
-   [x] Test the block inside the grid (Container + Row + Column)
-   [x] Test the block as a standalone block
-   [x] Duplicate the block, test that the settings of the first do not affect the second
-   [x] Test with 2 blocks of the same type

**_ Pre-Code Testing _**

-   [x] Test the component in normal state in sidebar
-   [x] Test the component in hover state in sidebar (if hover exists)
-   [x] Check that the settings work on frontend
-   [x] Check that backend works and saves the settings after the editor reload
-   [x] Same 1-4 points for the toolbar
-   [x] Same 1-4 points on responsive
-   [x] Test the block inside the grid (Container + Row + Column)
-   [x] Test the block as a standalone block
-   [x] Duplicate the block, test that the settings of the first do not affect the second
-   [x] Test with 2 blocks of the same type
-   [x] Check no commented code and no unnecessary imports
-   [x] Standards of the project have been followed
-   [x] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

2022-07-26 10:29 UTC, Marko64 requested changes
Icon responsive colour isn't working; the colour you choose changes for all responsive breakpoints.

2022-07-26 13:05 UTC, Marko64 approved these changes
Ok, in that case ignoring that one. Stroke hover and padding are fixed.

2022-07-26 14:09 UTC, myroslavve approved these changes

2022-07-28 14:58 UTC, Naaaaiix approved these changes
Good job @FitseTLT 👏 😸 

Need to fix the tests 👍

2022-07-29 11:01 UTC, merged