Issue 3184: created getIsOverlowHidden util function
maxi-blocks/maxi-blocks pull request #3510
Opened 2022-07-26 10:25 UTC by FitseTLT

# Description
created getIsOverlowHidden util function to avoid reduce code repetition

Fixes #3184 

# How Has This Been Tested?
Test that overflow hidden for overflow-x and overflow-y works for block resizer.

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type

**_ Pre-Code Testing _**

-   [ ] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

2022-07-26 13:51 UTC, Marko64 approved these changes
Transitions look good

2022-07-27 09:33 UTC, Marko64 reviewed
I'm not sure what's the ideal scenario and do we want to have. But this doesn't look good I think:
If you set overflow hidden for both X and Y, the resizer is visible but unclickable.
![Screenshot_3](https://user-images.githubusercontent.com/19425503/181216566-9a34caf6-30fc-416b-b0ca-58c812dd429e.jpg)

2022-07-28 09:21 UTC, Marko64 approved these changes

2022-07-29 08:47 UTC, Fybex requested changes
All works, but why we put `getIsOverflowHidden` in `src/extensions/styles/getLastBreakpointAttribute.js`, how is this related?

Also, if you want, you can reduce `getIsOverflowHidden`:
```
export const getIsOverflowHidden = (attributes, breakpoint) =>
	['overflow-y', 'overflow-x'].every(
		target =>
			getLastBreakpointAttribute({
				target,
				breakpoint,
				attributes,
			}) === 'hidden'
	);
```

2022-07-29 10:46 UTC, Fybex approved these changes

2022-08-01 11:30 UTC, elzadj approved these changes

2022-08-01 12:05 UTC, merged