Issue 3518 - Column width in IB
maxi-blocks/maxi-blocks pull request #3528
Opened 2022-07-29 12:08 UTC by Fybex

# Description

Added `Column settings` in IB when block to affect: column-maxi, removed width option from `Height / Width` IB settings.

Fixes #3518 

# How Has This Been Tested?
Created container and tested if column width changing is working and applying on frontend. Tested if after some changes in `ColumnSizeControl` column width works good(in `Column settings` in column-maxi)

# Test checklist

**_ Front/Back Testing _**

-   [x] Test if grid is working as usual
-   [x] Test the `Column settings` in column-maxi
-   [x] Test the `Column settings` in IB
-   [x] Test the `Column settings` in IB with multiply nested rows in each other
-   [x] Check that the settings work on frontend
-   [x] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1 point for the toolbar 
-   [x] Same 1-5 points on responsive

**_ Pre-Code Testing _**

-   [x] Test if grid is working as usual
-   [x] Test the `Column settings` in column-maxi
-   [x] Test the `Column settings` in IB
-   [x] Test the `Column settings` in IB with multiply nested rows in each other
-   [x] Check that the settings work on frontend
-   [x] Check that backend works and saves the settings after the editor reload
-   [x] Same 1 point for the toolbar 
-   [x] Same 1-5 points on responsive
-   [x] Check no commented code and no unnecessary imports
-   [x] Standards of the project have been followed
-   [x] No errors/warnings on console

# Checklist

-   [X] My code follows the style guidelines of this project
-   [X] I have performed a self-review of my code
-   [X] I have commented my code, particularly in hard-to-understand areas
-   [X] My changes generate no new warnings/errors
-   [X] New and existing unit tests pass locally with my changes

2022-07-29 14:23 UTC, Olekrut approved these changes

2022-08-01 10:20 UTC, Marko64 approved these changes

2022-08-01 11:30 UTC, myroslavve requested changes
When I changed column width, then deleted, inserted container, the column size wasn't right. 

https://user-images.githubusercontent.com/53875005/182138030-c2c60a20-6557-4bde-bb9d-c8b00a2c0f94.mp4

2022-08-01 11:44 UTC, myroslavve approved these changes

2022-08-01 12:58 UTC, Naaaaiix approved these changes

2022-08-01 12:58 UTC, merged