Issue 3507 - Shape mask in image-maxi IB settings
maxi-blocks/maxi-blocks pull request #3529
Opened 2022-07-29 14:02 UTC by Fybex

# Description

Fixes #3507

# How Has This Been Tested?
Tested if shape mask works in IB

# Test checklist

**_ Front/Back Testing _**

-   [x] Test the component in normal state in sidebar
-   [x] Check that the settings work on frontend
-   [x] Check that backend works and saves the settings after the editor reload
-   [x] Same 1-3 points for the toolbar
-   [x] Test the block inside the grid (Container + Row + Column)
-   [x] Test the block as a standalone block
-   [x] Duplicate the block, test that the settings of the first do not affect the second
-   [x] Test with 2 blocks of the same type

**_ Pre-Code Testing _**

-   [ ] Test the component in normal state in sidebar
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-3 points for the toolbar
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [X] My code follows the style guidelines of this project
-   [X] I have performed a self-review of my code
-   [X] My changes generate no new warnings/errors
-   [X] New and existing unit tests pass locally with my changes

2022-07-29 16:03 UTC, Olekrut approved these changes

2022-08-01 10:29 UTC, Marko64 approved these changes

2022-08-01 12:51 UTC, FitseTLT requested changes
I don't know if U can fix it, but I set some rotation and scale value and when I hover it will be applied but the image vibrates unless I hover out of the trigger.

2022-08-01 13:03 UTC, FitseTLT approved these changes

2022-08-01 13:37 UTC, elzadj approved these changes

2022-08-01 13:37 UTC, merged