Issue 3534 maxi full width template style
maxi-blocks/maxi-blocks pull request #3538
Opened 2022-08-03 10:09 UTC by Marko64

Slightly improved the style of the full-width page template. Fixed the scrollbar and added some spacing for header and footer.

Fixes #3534 

# How Has This Been Tested?

Add some content to the page, and test how it looks like with the full-width page template.

# Test checklist

**_ Front/Back Testing _**

-   [ ] Add some content to the page, and test how it looks like with the full-width page template.
-   [ ] Test responsive too.

**_ Pre-Code Testing _**

-   [x] Add some content to the page, and test how it looks like with the full-width page template.
-   [x] Test responsive too.
-   [x] Check no commented code and no unnecessary imports
-   [x] Standards of the project have been followed
-   [x] No errors/warnings on console

# Checklist

-   [x] My code follows the style guidelines of this project
-   x] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [x] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

2022-08-04 05:52 UTC, Rustam198804 approved these changes

2022-08-08 12:07 UTC, myroslavve approved these changes

2022-08-09 10:37 UTC, elzadj requested changes
Looks like this for me on Astra: 
![download (16)](https://user-images.githubusercontent.com/2401618/183628263-ee974d0d-6aae-491f-b559-08faa46ea2a7.jpeg)

Because of 

```
.site-content .ast-container {
    display: flex;
}
```

2022-08-30 08:57 UTC, elzadj approved these changes

2022-08-30 08:57 UTC, merged