Issue 3537 Modal UI changes
maxi-blocks/maxi-blocks pull request #3541
Opened 2022-08-03 11:00 UTC by Marko64

Modal UI changes

Fixes #3537

# Test checklist

**_ Front/Back Testing _**

-   [ ] Check pattern names in the modal.
-   [ ] Check that 'load' button is changed to 'insert'.
-   [ ] Check that no icons have the text 'line' in the name in modal

**_ Pre-Code Testing _**

-   [x] Check pattern names in the modal.
-   [x] Check that 'load' button is changed to 'insert'.
-   [x] Check that no icons have the text 'line' in the name in modal
-   [x] Check no commented code and no unnecessary imports
-   [x] Standards of the project have been followed
-   [x] No errors/warnings on console

# Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [x] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

2022-08-04 05:42 UTC, Rustam198804 approved these changes

2022-08-08 13:54 UTC, Fybex approved these changes

2022-08-08 14:10 UTC, elzadj requested changes
![download (14)](https://user-images.githubusercontent.com/2401618/183437729-d5e5c6cd-c9c5-47f6-8a3a-8dd05b07513b.png)
just one last left :smile_cat:

2022-08-09 07:35 UTC, elzadj approved these changes

2022-08-09 07:35 UTC, merged