Issue 3522 resizer unclickable when overflow hidden
maxi-blocks/maxi-blocks pull request #3546
Opened 2022-08-08 10:24 UTC by Marko64

# Description
Improved resizer style for Icon and Image blocks, when X and Y overflow is hidden.

Fixes #3522 

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test Icon and Image blocks' resizer with hiding X and Y overflow first. In master, they are either unclickable or hidden/cut off.

**_ Pre-Code Testing _**

-   [ ] Test Icon and Image blocks' resizer with hiding X and Y overflow first. In master, they are either unclickable or hidden/cut off.
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

2022-08-22 08:41 UTC, Olekrut approved these changes

2022-08-22 13:19 UTC, Fybex requested changes
Looks bad when svg width is 10px
![image](https://user-images.githubusercontent.com/46112160/185930772-b170cf1d-67ee-45e3-8721-8f1674fd0ea5.png)

2022-08-22 14:45 UTC, Fybex requested changes
One more thing, quite strange that we are overriding resizer styles in block styles, I think it's possible to do in block resizer styles file `src/components/block-resizer/editor.scss`. Then we also will get rid of `!important` and will have the code in one place 👍

2022-08-23 08:19 UTC, Fybex approved these changes

2022-09-28 09:40 UTC, elzadj approved these changes

2022-10-03 12:23 UTC, merged