Adapt webpack to deal with frontend scripts
maxi-blocks/maxi-blocks pull request #3556
Opened 2022-08-11 12:05 UTC by Naaaaiix

# Description

While working on #3514 I was having issues with the minifier for the frontend scripts, so swap them into webpack to be part of the compiler, so now is easy to debug them while developing, and it minifies it automatically while running the build.

# How Has This Been Tested?

Try `npm start`, so frontend scripts should be able to debug on frontend, and when running `npm build` a `min` folder should appear on `./js` with minified scripts

# Test checklist

⚠️ This PR doesn't need `front/back testing` step ⚠️ 

**_ Pre-Code Testing _**

-   [x] Check no commented code and no unnecessary imports
-   [x] Standards of the project have been followed
-   [x] No errors/warnings on console

# Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] My changes generate no new warnings/errors
-   [x] I have added/updated tests that prove my fix is effective or that my feature works
-   [x] New and existing unit tests pass locally with my changes

2022-08-11 12:58 UTC, Fybex approved these changes
Cool upgrade, works perfect 😄 🎉

2022-08-11 13:36 UTC, myroslavve requested changes
Doesn't work on windows, because `process.cwd()` returns path like `C:\\maxi-blocks\\`.
We can use `path.basename` to get filename, it will work on windows too.

2022-08-11 14:40 UTC, myroslavve requested changes
With `__dirname`, `glob(resolve(__dirname, 'js/*'))` returns `[]` for me. lol. I will try to enable bash for windows later today.

2022-08-12 10:14 UTC, myroslavve approved these changes

2022-08-16 09:05 UTC, elzadj approved these changes

2022-08-16 09:12 UTC, merged