Issue 3514 - IB fixes + hover
maxi-blocks/maxi-blocks pull request #3557
Opened 2022-08-11 13:20 UTC by Naaaaiix

# Description

Fixes the error derivate from #3530 that breaks the IB. To fix it, added a new `data` attribute for elements targeted by IB (`data-maxi-relations`) that ensures no conflicts between the CSS styles.

Fixes #3514 

# How Has This Been Tested?

This is the result on master branch for the next [code editor](https://github.com/yeahcan/maxi-blocks/files/9308953/ibfix.txt) that contains IB actions when hovering the Group for SVG Icon and for the 2 Text:

https://user-images.githubusercontent.com/50477222/184142383-8e6ec57c-dd8e-48d0-b77b-21268cb60c49.mp4

And here's how it should looks on this implementation:

https://user-images.githubusercontent.com/50477222/184142679-d8b56ab5-607f-4a08-8358-242c4ff6e336.mp4

To check it, I recommend using some patterns from devdemo 👍 

# Test checklist

**_ Front/Back Testing _**

-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload

**_ Pre-Code Testing _**

-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

2022-08-11 13:47 UTC, Olekrut approved these changes

2022-08-12 08:46 UTC, Fybex requested changes
It is okay, that on each click the same styles adding, and we have something like this:
<img width="323" alt="image" src="https://user-images.githubusercontent.com/46112160/184318548-2968a8f6-f291-4ab4-860a-40611955b27b.png">

The same thing with hover, after each interaction styles are duplicating:
<img width="322" alt="image" src="https://user-images.githubusercontent.com/46112160/184319083-df519356-fffd-48a7-b6d3-fc3f367c9fd0.png">

2022-08-23 09:22 UTC, Fybex requested changes

2022-08-23 09:28 UTC, Fybex approved these changes

2022-08-23 10:02 UTC, elzadj approved these changes

2022-08-23 10:02 UTC, merged