Issue 3516 - `maxi-version` attribute
maxi-blocks/maxi-blocks pull request #3562
Opened 2022-08-15 11:11 UTC by Fybex

# Description

Resolve #3516 

# How Has This Been Tested?
Tested if blocks have `maxi-version` attribute, if it updates on change. Checked if code editor has `maxi-version` attribute.

# Test checklist

**_  Front/Back Testing _** 

-   [x] Test if `maxi-version` attribute is displayed in code editor

**_ Pre-Code Testing _**

-   [x] Test if new blocks get the `maxi-version` attribute.
-   [x] Test if when `MAXI_VERSION` constant is changed, `maxi-version` attributes are also changed 👍 
-   [x] Test if `maxi-version` attribute is displayed in code editor
-   [x] Check no commented code and no unnecessary imports
-   [x] Standards of the project have been followed
-   [x] No errors/warnings on console

# Checklist

-   [X] My code follows the style guidelines of this project
-   [X] I have performed a self-review of my code
-   [X] My changes generate no new warnings/errors
-   [X] I have added/updated tests that prove my fix is effective or that my feature works
-   [X] New and existing unit tests pass locally with my changes

2022-08-16 08:51 UTC, Marko64 approved these changes

2022-08-16 09:59 UTC, myroslavve approved these changes

2022-08-17 09:02 UTC, elzadj requested changes

2022-08-18 14:22 UTC, Naaaaiix approved these changes
Looks good @Fybex, awesome job 👍 

PS: tests!

2022-08-18 14:34 UTC, elzadj approved these changes
teeeeeeeeeests :D

2022-08-19 09:48 UTC, merged