Issue 3565 - video issues
maxi-blocks/maxi-blocks pull request #3568
Opened 2022-08-17 12:51 UTC by myroslavve

# Description
Moved Video/Popup tabs to sidebar, added hover for overlay, transition for overlay and icons, custom css for icons, interaction builder with all common settings and settings for overlay, and fixed a bunch of other small issues.

Fixes #3565 

# Test checklist

**_Front/Back Testing_**

-   [ ] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type

**_Pre-Code Testing_**

-   [ ] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

2022-08-19 13:18 UTC, Marko64 requested changes
1. If you change the video to popup and preview without adding an image, the video doesn't show. The video should still work, just with the placeholder/default image.

2. Height/width settings do not do anything.

3. Just a suggestion: Do you think if it would be better to have hover colour for play and close icons by default?

2022-08-26 08:28 UTC, Marko64 approved these changes

2022-08-26 13:23 UTC, Fybex requested changes
Great job, a few things:

1. Full width switch mustn't be in settings tab + it's not working
2. https://github.com/maxi-blocks/maxi-blocks/blob/c55137496b2b63fa0dd3ba0fd2c32a80c279ab2b/src/blocks/video-maxi/edit.js#L190 change overlay target to `.maxi-video-block__overlay-background` (inline styles don't work) + it's mustn't change inline colour on in `VideoOverlayControl` when user in hover state 👍 
3. Overlay settings in IB shouldn't have hover state 👍

2022-08-29 10:05 UTC, Fybex approved these changes
Approving 👍 , small thing with props order below.

2022-08-30 09:32 UTC, elzadj approved these changes

2022-08-31 09:14 UTC, Olekrut approved these changes

2022-08-31 09:21 UTC, merged