Issue 3603 - Size and position support in all bg layers types
maxi-blocks/maxi-blocks pull request #3633
Opened 2022-08-31 16:00 UTC by Fybex

# Description

Changes:
- added size and position controls to every layer
- extend unit tests
- wrote e2e tests to check size and position correct work

Fixes #3603 

# How Has This Been Tested?
Checked if the new controls work well in all layer types, checked if the svg size and position attributes don't disappear, checks whether the default attributes of the new controls are also settings in the old blocks.

# Test checklist

**_ Front/Back Testing _**

-   [x] Test the component in normal state in sidebar with all layer types
-   [x] Test the component in hover state in sidebar with all layer types (if hover exists)
-   [x] Test if svg size and position settings, which were set in master, are available in this branch
-   [x] Test if other created layers, which were created in master, have 100% default size
-   [x] Check that the settings work on frontend
-   [x] Check that backend works and saves the settings after the editor reload
-   [x] Same 1-6 points on responsive

**_ Pre-Code Testing _**

-   [x] Test the component in normal state in sidebar with all layer types
-   [x] Test the component in hover state in sidebar with all layer types (if hover exists)
-   [x] Test if svg size and position settings, which were set in master, available in this branch
-   [x] Test if other created layers, which were created in master, have 100% size by default
-   [x] Check that the settings work on frontend
-   [x] Check that backend works and saves the settings after the editor reload
-   [x] Same 1-6 points on responsive
-   [x] Check no commented code and no unnecessary imports
-   [x] Standards of the project have been followed
-   [x] No errors/warnings on console

# Checklist

-   [X] My code follows the style guidelines of this project
-   [X] I have performed a self-review of my code
-   [X] I have commented my code, particularly in hard-to-understand areas
-   [X] My changes generate no new warnings/errors
-   [X] I have added/updated tests that prove my fix is effective or that my feature works
-   [X] New and existing unit tests pass locally with my changes

2022-09-01 07:32 UTC, Marko64 requested changes
When you go to icon background settings for SVG, it says:
_"This block has encountered an error and cannot be previewed."_

2022-09-09 07:43 UTC, Marko64 approved these changes

2022-09-13 15:52 UTC, myroslavve reviewed
Works good 👍. Just two small comments

2022-09-13 16:29 UTC, myroslavve approved these changes

2022-09-14 10:05 UTC, elzadj approved these changes

2022-09-14 10:05 UTC, merged