Issue 3521 - Background attribute coherence
maxi-blocks/maxi-blocks pull request #3638
Opened 2022-09-01 12:42 UTC by Fybex

# Description

Changes:
- renamed all attributes `hover-status` suffixes to `status-hover`
- created `hoverStatusMigrator`
- fixed search-maxi input hover background saving after reload
- fixed inability to open hover state in pane-maxi header

Fixes #3521

# How Has This Been Tested?
Checked if all hover status attributes have suffix `status-hover` in this branch, not `hover-status`, checked if migrator which migrate old type of attributes to new works fine.

# Test checklist

**_ Front/Back Testing _**

-   [x] Test if background hover status is working everywhere
-   [x] Test if background hover status attribute migrate successfully(you can use this code editor [created_on_master_blocks_with_bg_hover.txt](https://github.com/maxi-blocks/maxi-blocks/files/9469778/created_on_master_blocks_with_bg_hover.txt))
-   [x] Test if search-maxi input hover background attributes saves after the editor reload
-   [x] Test if it's possible to open pane-maxi header background hover-state
-   [x] Check that the settings work on frontend
-   [x] Check that backend works and saves the settings after the editor reload

**_ Pre-Code Testing _**

-   [x] Test if background hover status is working everywhere
-   [x] Test if background hover status attribute migrate successfully(you can use this code editor [created_on_master_blocks_with_bg_hover.txt](https://github.com/maxi-blocks/maxi-blocks/files/9469778/created_on_master_blocks_with_bg_hover.txt))
-   [x] Test if search-maxi input hover background attributes saves after the editor reload
-   [x] Test if it's possible to open pane-maxi header background hover-state
-   [x] Check that the settings work on frontend
-   [x] Check that backend works and saves the settings after the editor reload
-   [x] Check no commented code and no unnecessary imports
-   [x] Standards of the project have been followed
-   [x] No errors/warnings on console

# Checklist

-   [X] My code follows the style guidelines of this project
-   [X] I have performed a self-review of my code
-   [X] My changes generate no new warnings/errors
-   [X] I have added/updated tests that prove my fix is effective or that my feature works
-   [X] New and existing unit tests pass locally with my changes

2022-09-02 09:57 UTC, Marko64 requested changes
This one still not working for me:
-  Test if it's possible to open pane-maxi header background hover-state

Does it work for you?

2022-09-02 12:22 UTC, Marko64 approved these changes
Opening a new PR for that 👍

2022-09-02 12:57 UTC, myroslavve approved these changes

2022-09-15 08:47 UTC, elzadj approved these changes

2022-09-15 08:48 UTC, merged