Issue 3635 - choose option for flex control
maxi-blocks/maxi-blocks pull request #3642
Opened 2022-09-01 14:32 UTC by myroslavve

# Description
Added `Choose` option to all dropdowns in Flexbox tab in settings. 

Fixes #3635 

# How Has This Been Tested?
Checked that dropdowns without default value select `Choose` option by default

# Test checklist

**_Front/Back Testing_**

-   [x] Check that dropdowns without default value select `Choose` option by default
-   [x] Check that you can select `Choose` option again after you selected other option

**_Pre-Code Testing_**

-   [ ] Check that dropdowns without default value select `Choose` option by default
-   [ ] Check that you can select `Choose` option again after you selected other option
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

2022-09-02 09:14 UTC, Marko64 approved these changes

2022-09-02 10:57 UTC, Fybex requested changes
1. `flex-direction`, `flex-wrap`, as all others properties doesn't have `none` property, replace `none` with `unset`
2. If users on winBreakpoint has set some values and then switched back to Choose, they shouldn't have any styles in the css, they don't do anything.

2022-09-02 13:49 UTC, Fybex reviewed
What is the logic behind the `Choose` option on a non `winBreakpoint` if it does nothing?

2022-09-02 14:23 UTC, Fybex approved these changes

2022-09-06 07:41 UTC, elzadj approved these changes

2022-09-06 07:41 UTC, merged