Fixes #3641
maxi-blocks/maxi-blocks pull request #3643
Opened 2022-09-01 14:35 UTC by Naaaaiix

# Description

Fixes the 3 issues found after updating devdemo and commented on #3641:
1. Broken grids: have been fixed recovering some lines of CSS that ensure a `flex-direction` CSS property for wrapper blocks.
2. Some IB effects aren't working with the new targets: a new migrator has created for it.
3. Some IB transitions doesn't work correctly on frontend: frontend js file has been fixed.

Fixes #3641 

# How Has This Been Tested?

To check 1:
Check this one is really hard, so we'll do it in a reverse way. The changes done affect to 3 `style.scss` files where the same line has been added: `flex-direction: column`. It should work as a backup of the inner block style created from the attributes, so is basically like it was before. So, to test it, check an icon or footer page of devdemo ([this one is an example](https://devdemo.maxiblocks.com/pure-footers-dark-pfd/)) and look for this CSS boxes to add the commented line `flex-direction: column` (row uses `flex-direction: row`!):
| Container  |  Column | Group  | Row |
|---|---|---|---|
| <img width="498" alt="Captura de Pantalla 2022-09-01 a las 16 51 18" src="https://user-images.githubusercontent.com/50477222/187944820-8d6ee31c-9fc9-454b-a825-0fb0c482bfbf.png">  |  <img width="498" alt="Captura de Pantalla 2022-09-01 a las 16 53 05" src="https://user-images.githubusercontent.com/50477222/187945700-c334f0f1-9bc3-4369-a750-4346b10442db.png"> | <img width="498" alt="Captura de Pantalla 2022-09-01 a las 16 53 21" src="https://user-images.githubusercontent.com/50477222/187945764-9142bdd9-f67e-4267-bb56-594bb6b51583.png">  | <img width="498" alt="Captura de Pantalla 2022-09-01 a las 16 52 50" src="https://user-images.githubusercontent.com/50477222/187945864-6b90198d-4248-4afe-994a-25c258264779.png">

After adding that lines the site should look good and is the same implementation done in this branch 👍 

To check 2:
Using master, copy some of the broken IB Icon Maxi colour interactions or use this [code editor](https://github.com/maxi-blocks/maxi-blocks/files/9471007/broken.IB.txt) and check this is the result:

https://user-images.githubusercontent.com/50477222/187946960-1e4c8b0f-e3d5-4b61-8c44-5e62c61c4010.mp4

Then change to this branch and check it again:

https://user-images.githubusercontent.com/50477222/187948300-f5f7ce9a-ac38-4aa0-ab99-74a2ed7204f1.mp4

To check 3:
It can be tested as the last video (on hovering directly to the element, the transition still works correctly). Also, can be tested with many IB relations using this [code editor](https://github.com/maxi-blocks/maxi-blocks/files/9471070/IB-tests.txt). 

# Test checklist

**_ Front/Back Testing _**

-   [x] Test the 3 checks exposed above

**_ Pre-Code Testing _**

-   [x] Test the 3 checks exposed above
-   [x] Check no commented code and no unnecessary imports
-   [x] Standards of the project have been followed
-   [x] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

2022-09-01 15:41 UTC, myroslavve requested changes
Seems like button icon gets wrong transition on hover.

https://user-images.githubusercontent.com/53875005/187954316-e2fdb998-c244-4030-8d3c-dfd2388621b8.mp4

And IB for button icon works a little weird

https://user-images.githubusercontent.com/53875005/187955588-6293c5e6-8b43-4a05-9c51-1dcaf5d3f838.mp4

Edit: I've just checked it's on master also. Maybe move this to separate issue?

2022-09-01 15:54 UTC, myroslavve approved these changes

2022-09-02 08:46 UTC, Marko64 approved these changes

2022-09-02 10:04 UTC, elzadj approved these changes

2022-09-02 10:07 UTC, merged