Issue 3636 - fix values not saving on unit switch
maxi-blocks/maxi-blocks pull request #3644
Opened 2022-09-01 15:47 UTC by myroslavve

# Description
Didn't work because even with `optionType === 'string'` it used numbers in `onChangevalue`.

Fixes #3636 

# How Has This Been Tested?
Checked that values that were set to not exceed the max value are saved after reload.

# Test checklist

**_ Front/Back Testing _**

-   [x] Check that values that were set to not exceed the max value are saved after reload

**_ Pre-Code Testing _**

-   [x] Check that values that were set to not exceed the max value are saved after reload
-   [x] Check no commented code and no unnecessary imports
-   [x] Standards of the project have been followed
-   [x] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

2022-09-02 08:56 UTC, Marko64 requested changes
This fixes the issue, but we also need to increase the max value for the % unit. Normally texts have somewhere between 100 and 200 line height when % is used. Let's change the limit to 200.

2022-09-02 09:09 UTC, Marko64 approved these changes

2022-09-02 10:58 UTC, Fybex approved these changes

2022-09-05 07:41 UTC, elzadj approved these changes

2022-09-05 07:44 UTC, merged