Issue 3652 - Icon transitions disco effect fix
maxi-blocks/maxi-blocks pull request #3656
Opened 2022-09-05 18:22 UTC by Fybex

# Description

Changes:
- fixed disco effect
- normalized logic of adding icon transitions, created for this `createIconTransitions` helper

Fixes #3652 

# How Has This Been Tested?
Checked if in this [code_editor](https://github.com/maxi-blocks/maxi-blocks/files/9491565/icon-transitions-check.txt), where I've collected all the blocks with icons, transitions are working without disco effect, and if new helper didn't break anything.

# Test checklist

**_ Front/Back Testing _**

-   [x] Test the [code_editor](https://github.com/maxi-blocks/maxi-blocks/files/9491565/icon-transitions-check.txt) blocks for disco effect
-   [x] Test if the blocks svg-icon-maxi, button-maxi icon, video-maxi (search-maxi transitions have been changed, but this block is not used anywhere in the patterns, so the migrator has not been written and transitions from the master will not work 👍 ), which were created in the master with transitions, have transitions after switching to this branch
-   [x] Check that the settings work on frontend

**_ Pre-Code Testing _**

-   [x] Test the [code_editor](https://github.com/maxi-blocks/maxi-blocks/files/9491565/icon-transitions-check.txt) blocks for disco effect
-   [x] Test if the blocks svg-icon-maxi, button-maxi icon, video-maxi (search-maxi transitions have been changed, but this block is not used anywhere in the patterns, so the migrator has not been written and transitions from the master will not work 👍 ), which were created in the master with transitions, have transitions after switching to this branch
-   [x] Check that the settings work on frontend
-   [x] Check no commented code and no unnecessary imports
-   [x] Standards of the project have been followed
-   [x] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

2022-09-06 06:39 UTC, Marko64 approved these changes

2022-09-06 15:01 UTC, myroslavve requested changes
There's also icons in accordion-maxi and pane-maxi

2022-09-08 14:59 UTC, myroslavve approved these changes

2022-09-09 07:40 UTC, elzadj approved these changes

2022-09-09 07:41 UTC, merged