Resizer fix
maxi-blocks/maxi-blocks pull request #3686
Opened 2022-09-14 14:28 UTC by myroslavve

# Description
After #3658 the styles in resizers are cleaned. But they don't need to be cleaned in resizer in TransformControl.
Changes:

- Changed `cleanStyles` to `false` by default, and set it to true on certain blocks, so now styles should be good everywhere.
- Previously styles were cleaned every time ref is set, now they are only cleaned first time, and after resizing stops.

Fixes #3685 

# How Has This Been Tested?
Checked that resizer works and looks good on all blocks, and TransformControl.

# Test checklist

**_ Front/Back Testing _**

-   [x] Check that resizer works and looks good on all blocks
-   [x] Check that resizer works and looks good on TransformControl

**_ Pre-Code Testing _**

-   [x] Check that resizer works and looks good on all blocks
-   [x] Check that resizer works and looks good on TransformControl
-   [x] Check no commented code and no unnecessary imports
-   [x] Standards of the project have been followed
-   [x] No errors/warnings on console

# Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] My changes generate no new warnings/errors
-   [x] I have added/updated tests that prove my fix is effective or that my feature works
-   [x] New and existing unit tests pass locally with my changes

2022-09-16 06:30 UTC, Marko64 approved these changes

2022-09-23 17:23 UTC, Fybex requested changes
Working, just a minor moment

2022-09-23 17:40 UTC, Fybex approved these changes

2022-09-26 09:41 UTC, elzadj approved these changes

2022-09-26 09:41 UTC, merged