Issue 3661 span focus
maxi-blocks/maxi-blocks pull request #3703
Opened 2022-09-21 10:37 UTC by Marko64

Overwritten span focus for the Seedlet theme.

I left _focus-visible_ as is. I don't think that's a glitch but is supposed to be visible if someone prefers.

[span-focus.txt](https://github.com/maxi-blocks/maxi-blocks/files/9615755/span-focus.txt)

Fixes #3661 and Fixes #3592

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test the pattern and make sure that the span doesn't have the focus border.

**_ Pre-Code Testing _**

-   [x] Test the pattern and make sure that the span doesn't have the focus border.
-   [x] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [x] No errors/warnings on console

# Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

2022-09-21 15:03 UTC, Olekrut approved these changes

2022-09-22 16:16 UTC, Fybex requested changes
Works for me, but wrote down a few points which can be optimized

2022-09-23 08:06 UTC, Naaaaiix approved these changes

2022-09-23 17:59 UTC, Fybex requested changes

2022-09-27 17:09 UTC, Fybex requested changes
Sorry, that didn't mention better solution from the start 😆 😅

2022-10-07 10:21 UTC, merged