Issue 3700 - Remove hoverProp from transition attributes
maxi-blocks/maxi-blocks pull request #3712
Opened 2022-09-23 16:55 UTC by Fybex

# Description

Update:
- removed `hoverProp` from transition attributes
- `hoverProp` key now is always required in transition data in data.js of maxi-block
- `limitless: true` → `property: false`
- `ignoreHoverProp: true` → `hoverProp: undefined`
- other small fixes

Fixes #3700 

# How Has This Been Tested?
Checked if all transitions still work, checked if svg background transitions work in [this code editor](https://github.com/maxi-blocks/maxi-blocks/files/9635527/svg-with-old-hover-prop.txt).

# Test checklist

**_ Front/Back Testing _**

-   [x] Test transitions activation when hover state is turned on, deactivation when hover is disabled
-   [x] Test transitions work as usual

**_ Pre-Code Testing _**

-   [ ] Test transitions activation when hover state is turned on, deactivation when hover is disabled
-   [ ] Test transitions work as usual
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [X] My code follows the style guidelines of this project
-   [X] I have performed a self-review of my code
-   [X] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [X] New and existing unit tests pass locally with my changes

2022-09-26 09:18 UTC, Marko64 requested changes
I can't click any of these settings now. There are no errors in the console tho.

![Screenshot_1](https://user-images.githubusercontent.com/19425503/192239964-b56303e5-b534-4b78-96e7-d217ddc4a12e.jpg)

2022-09-29 10:54 UTC, Marko64 approved these changes

2022-09-30 17:54 UTC, myroslavve approved these changes

2022-10-03 08:02 UTC, Naaaaiix approved these changes

2022-10-04 08:48 UTC, merged