Issue 3697 - IB frontend refactoring
maxi-blocks/maxi-blocks pull request #3733
Opened 2022-09-28 11:32 UTC by Naaaaiix

# Description

This PR is part of the strategy created on #3697. The main idea is to refactor the old frontend file for IB/relations into a OOP paradigm under a Class statement to improve in many senses its quality. Some important notes about it:
1. This refactoring might fix some issues from the old file, but is not its intention. As a basic refactoring, what we expect is to cover at least the same cases that were working before.
2. It has considered most of the current or merged PRs related with this file.

Some of the main changes:
1. Added `transitionTrigger`: a target that triggers the native hover transition of the block (removing the IB transition) that sometimes is different from the transitionTarget. For example, on Button Maxi, when affecting the typography we want to remove the IB transition on hovering the button, not the `span` inside of it.
2. Removed `isNestedHoverTransition` as found not necessary.

Known issues: (most of them are already on master version)
1. This implementation won't migrate old IB blocks, so needs a migrator.
2. Button Icon and SVG Icon colour IB settings doesn't work correctly sometimes (mostly on filled SVGs); has been commented on [this commnet](https://github.com/maxi-blocks/maxi-blocks/issues/3697#issuecomment-1259377258) and #3722).
3. Transform targets aren't working correctly also from IB; commented on the code and in [this comment](https://github.com/maxi-blocks/maxi-blocks/issues/3697#issuecomment-1259377258).
4. Background transition for Button Maxi `button` element is not working correctly as commented [here](https://github.com/maxi-blocks/maxi-blocks/issues/3697#issuecomment-1259377258).
5. Left some `console.log` for debugging and some comments to consider; please focus on the refactored file.

Known resolved issues:
1. The hover synchronicity commented on the last point of [this comment](https://github.com/maxi-blocks/maxi-blocks/issues/3697#issuecomment-1259377258) has been fixed on this branch.

# How Has This Been Tested?

On [this comment](https://github.com/maxi-blocks/maxi-blocks/issues/3697#issuecomment-1259359995) you'll find some of the test patterns created for IB. They are basically working on hovering actions, not clicking, as they are the most complex ones. Next to each of the created tests you'll find 2 links: one to learndd where you'll find the test pattern running under `master` version, and a code editor to test with this branch. The test consists on comparing one and other: what is working on learndd should work on this branch, and what's not working on learndd may or may not work on this branch.

How to report an error:
1. Record a video of the action done.
2. Add code editor.

⚠️ You may need to clean cache when using this branch on frontend!!! ⚠️ 

# Test checklist

**_ Front/Back Testing _**

-   [ ] Compare the learndd tests patterns with the same tests patterns on this branch

**_ Pre-Code Testing _**

-   [ ] Compare the learndd tests patterns with the same tests patterns on this branch
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

2022-09-28 17:58 UTC, Fybex requested changes

2022-09-29 14:51 UTC, Fybex approved these changes
Lovely 👍

2022-09-29 16:19 UTC, myroslavve approved these changes

2022-10-03 06:50 UTC, Rustam198804 approved these changes

2022-10-03 07:21 UTC, Olekrut approved these changes

2022-10-03 15:25 UTC, merged