Issue 3617 - error one e2e tests
maxi-blocks/maxi-blocks pull request #3735
Opened 2022-09-28 19:27 UTC by myroslavve

# Description
⚠️ This PR doesn't need front/back testing ⚠️

The error came from `loadFonts` where, we are trying to get iframe of the editor, when on small breakpoints.
The problem was in `changeResponsive` util for e2e tests, we weren't specifying the width of the breakpoint in `setMaxiDeviceType`, so it didn't put an editor in iframe.

Wrote a responsive test for `FontFamilySelector`, to ensure that the error doesn't appear anymore.

Fixes #3617 

# How Has This Been Tested?

# Test checklist

**_ Pre-Code Testing _**

-   [ ] Check that the error doesn't appear on tests anymore
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

2022-09-29 15:05 UTC, Fybex requested changes
Tests are broken after changes

2022-12-01 09:34 UTC, elzadj approved these changes

2022-12-01 17:49 UTC, Naaaaiix reviewed
Awesome @TeksPeks, you've nailed it! 👏 

Just a last detail: use this snippet on the FontFamilySelector e2e test, at the end of the responsive one, to ensure the font has been loaded:
```js
const hasBeenLoaded = await page.evaluate(() => document.fonts.check('12px Montserrat'));

expect(hasBeenLoaded).toBeTruthy();

```

[MDN FontFaceSet.check()](https://developer.mozilla.org/en-US/docs/Web/API/FontFaceSet/check)

2022-12-02 15:49 UTC, Fybex approved these changes

2022-12-05 17:40 UTC, merged