Fix 3506 - Display box shadow control panel always
maxi-blocks/maxi-blocks pull request #3739
Opened 2022-09-29 10:46 UTC by blockchain-web-mobile-dev

Fixes #3506 

# How Has This Been Tested?

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test with image block and video block and button block

**_ Pre-Code Testing _**

-   [ ] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

2022-09-29 14:21 UTC, Marko64 requested changes
That works, but without the active status, we don't have the active tabs indicator too:

![Screenshot_2](https://user-images.githubusercontent.com/19425503/193057174-7247c7cf-78d8-4367-a766-9096b3373fe1.jpg)

Master:
![Screenshot_3](https://user-images.githubusercontent.com/19425503/193057178-0492f135-ba79-4d5e-860b-6c4ef1f34642.jpg)

2022-10-01 15:12 UTC, Marko64 approved these changes

2022-10-03 15:53 UTC, Fybex requested changes
In toolbar box-shadow settings is still disabled

![image](https://user-images.githubusercontent.com/46112160/193621802-743c2d7f-1bed-4520-aefe-78e8a3a65c48.png)

P.S. Will be fixed after applying my recommendations in the comment below 👍

2022-10-10 07:15 UTC, Marko64 approved these changes

2022-10-12 08:08 UTC, elzadj approved these changes

2022-10-13 07:35 UTC, merged