Fix 3552 - Optimize SvgColorControl
maxi-blocks/maxi-blocks pull request #3742
Opened 2022-09-29 12:51 UTC by blockchain-web-mobile-dev

optimize the repeated onChange function in SvgColorControl

Fixes #3552 

# How Has This Been Tested?

# Test checklist

**_ Front/Back Testing _**

-   [x] Check that the settings work on frontend
-   [x] Check that backend works and saves the settings after the editor reload

**_ Pre-Code Testing _**

-   [x] Optimize onChange function repeated
-   [x] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

2022-09-29 14:33 UTC, Marko64 approved these changes

2022-10-03 17:28 UTC, myroslavve requested changes

2022-10-21 07:44 UTC, Naaaaiix approved these changes
👏 

Thanks @TeksPeks 🥳

2022-10-21 13:00 UTC, Fybex approved these changes

2022-10-24 07:22 UTC, merged