Issue 3751 - use wrapper height switch for image maxi
maxi-blocks/maxi-blocks pull request #3784
Opened 2022-10-07 17:30 UTC by myroslavve

# Description

https://user-images.githubusercontent.com/50477222/197506480-91a1fdf5-b0a5-4af0-939c-5bac550eefbd.mp4

Resuming:
This implementation is a MVP to fix the conflict we've got with the use of BG Image Layers instead of Image Maxi blocks. This implementation can have conflicts with other settings and needs also e2e tests to shield it. Both things will be done after merging in master 👍 

Fixes #3751 

# Test checklist

**_Front/Back Testing_**

-   [ ] Check that new settings work

**_Pre-Code Testing_**

-   [x] Check that new settings work
-   [x] Check no commented code and no unnecessary imports
-   [x] Standards of the project have been followed
-   [x] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

2022-10-24 16:10 UTC, Olekrut approved these changes

2022-10-24 16:48 UTC, Fybex requested changes

2022-10-25 09:33 UTC, Marko64 approved these changes
Needs some padding here:
![Screenshot_3](https://user-images.githubusercontent.com/19425503/197738662-13426f33-becf-46c2-82ba-2b2491fb8437.jpg)

2022-10-26 08:45 UTC, elzadj approved these changes

2022-10-26 08:46 UTC, moroz-art-dev approved these changes

2022-10-26 08:47 UTC, merged