Issue 3787 - content is pasted on 'Paste styles - all'
maxi-blocks/maxi-blocks pull request #3789
Opened 2022-10-11 14:02 UTC by myroslavve

# Description
Fixed the content getting pasted on 'Paste styles - all', for `text-maxi`, `button-maxi`, `image-maxi`, `svg-icon-maxi` and `video-maxi`.

Fixes #3787 

# How Has This Been Tested?
Checked on master, on listed blocks the content (media content, text content) is pasted when clicking 'Paste styles - all', on this branch it only gets pasted, when selected in 'Paste special - select'.

# Test checklist

**_ Front/Back Testing _**

-   [x] Check content doesn't get pasted on 'Paste styles - all'
-   [x] Check content does get pasted on 'Paste special - select'

**_ Pre-Code Testing _**

-   [ ] Check content doesn't get pasted on 'Paste styles - all'
-   [ ] Check content does get pasted on 'Paste special - select'
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] My changes generate no new warnings/errors
-   [x] I have added/updated tests that prove my fix is effective or that my feature works
-   [x] New and existing unit tests pass locally with my changes

2022-10-12 06:18 UTC, Marko64 requested changes
All good except the video. I don't see paste special for it. It does show if I change more settings, but if only the URL is different, I don't see it. 

![Screenshot_1](https://user-images.githubusercontent.com/19425503/195264674-0227d017-d4ec-40ed-9e25-e2b76a09003e.jpg)

2022-10-17 08:06 UTC, Marko64 approved these changes

2022-10-21 14:07 UTC, moroz-art-dev approved these changes

2022-10-24 07:28 UTC, Naaaaiix approved these changes

2022-10-24 09:01 UTC, merged