Fixes 3758 - Canvas size breakpoints and attributes saving mechanism
maxi-blocks/maxi-blocks pull request #3796
Opened 2022-10-13 08:29 UTC by Naaaaiix

⚠️ IMPORTANT ⚠️ 

This PR modifies the core of Maxi styling and attributes mechanism. Please, test it deeply; ask questions and share whatever you consider important 👍 

---------------------------

# Description

This PR resolves more than one issue. Based on @Olekrut issue #3758 and his video on the chat:

[XL and L (1).webm](https://user-images.githubusercontent.com/50477222/195545534-4ab2b952-e5fa-4d03-8d49-5890cf1de949.webm)

What we can see is that #3608 implemented a new way responsive stages are triggered: depending on the editor canvas width. Before it, styles and responsive stage were depending on the whole screen size, but as @Fybex noticed, it wasn't the best correlation between what we were rendering (EE) and the real result(FE). That lack of symmetry was fixed with that implementation, but as @Olekrut commented on #3758, it derived into other issues. They were basically 2:
1. Styles (styleGenerator.js) were still based on `@media` CSS rule, so were depending on the size of the screen. It becomes a problem as what we were seeing when canvas editor was getting smaller than shown on #3758 wasn't what creators requested.
2. Saved attributes, mostly the ones changed on `base` responsive stage, weren't saved correctly. Mechanisms weren't strong enough for it, and results into redundancies and conflicts between `base` and responsive stage attributes that were causing confusing rendering of styles and settings. 

To fix it, there have been 2 major changes on Maxi's saving attributes mechanism (`handleSetAttributes`) and on the way is rendering styles (`styleGenerator`):
1. `handleSetAttributes` now is complemented with `cleanAttributes` function that does a flat and clean of not just the saving attributes, also the existing ones, that should reduce these amount of errors, reduce the amount of saved attributes, and avoid possible confusions on editor renderings. Also, should reduce the amount of saved data on code editor and the amount of displayed CSS on frontend. 
2. `styleGenerator` has been simplified and now is not displaying `@media` queries for the styles on editor experience. Instead of it, is displaying responsive stage styles based on canvas main HTML element attribute (`maxi-blocks-responsive`) _**OVER**_ general styles.

This video should resume and clean some doubts about what has been commented above:

https://user-images.githubusercontent.com/50477222/195545028-a5b2e584-93f7-473f-a789-1948e55275c0.mp4

Also, related with these fixes, other things have been implemented while fixing:
1. BG layers resetting was broken. Basically, as BG layer attribute is an object, we weren't returning the correct default value. Now is fixed.
2. On creating a BG layer from non-base responsive stage, it was creating the value for that concrete responsive stage instead of `general`. That was causing errors and conflictive attributes.
3. Added `onReset` function for ColorControl to allow other HOC components instancing it to have control over the resetting actions, as is the case for BGLayersControl.
4. Added state for the ANC value, check the video commented on the same code to see the reason.

PS: These mechanisms hasn't been implemented on IB saving, so the issues of the first video are still there. Will be done after this major implementation 👍 

Fixes #3758 

# How Has This Been Tested?

This implementation has been tested with the current e2e tests and manually. Also added tests for `handleSetAttributes` and `cleanAttributes` that should ensure the correct functionality of that mechanisms. Anyway, please, try testing deep:
1. On creating a block and modify its attributes on different responsive breakpoints, the experience of the saved attribute is good; also for hovers.
2. Styles on backend are correct, not just changing the responsive stage, also opening the `List view` or the `Block inserter` panels on the left side.
3. On checking frontend the styles are displaying correctly for all responsive.
4. SC work correctly on its different responsive stages.

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test different blocks with all the commented steps above

**_ Pre-Code Testing _**

-   [ ] Test different blocks with all the commented steps above
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

2022-10-18 15:19 UTC, elzadj approved these changes

2022-10-18 19:15 UTC, Fybex requested changes
Great job. 
But I have some thoughts about responsive logic:
So my base breakpoint - L, I set bg colour to L, to gray at XL, then I've changed base breakpoint to M and I can't pick on L the same colour as I've picked on base breakpoint 🤔 

https://user-images.githubusercontent.com/46112160/196521894-7a204857-ce3b-4b01-a483-2da7bd5fd967.mp4

But what is I even want to pick other colour on L, not orange? Yes, we should override the general styles by responsive, but we are also just losing one of the breakpoints. I need to do some hack, like set base breakpoint to M to change attributes on L breakpoint.

Maybe when user changes some responsive breakpoint (all except base one) attributes, we should add, if base breakpoint - L, L attributes, and change L and base attributes in next changes on L (base) breakpoint.
It's just an idea, maybe it has some pitfalls I didn't notice.

2022-10-19 08:59 UTC, Olekrut approved these changes

2022-10-19 15:53 UTC, myroslavve requested changes
Typography colour doesn't change for me on responsive (on frontend too).

https://user-images.githubusercontent.com/53875005/196739680-e809db82-d7e7-485d-943f-0558d566300f.mp4

Also, hover values that are the same on responsive and general are duplicated.
Probably, this happens because `getBreakpointFromAttribute` returns `false` for `attribute-general-hover`. But maybe this is expected.

https://user-images.githubusercontent.com/53875005/196740450-6f3816c0-fcd6-481c-9b6e-7ca9dd3b5873.mp4

2022-10-19 15:54 UTC, Olekrut approved these changes

2022-10-19 16:48 UTC, moroz-art-dev approved these changes

2022-10-20 15:07 UTC, Fybex approved these changes

2022-10-20 16:30 UTC, myroslavve approved these changes
Apart from that hover issue, everything seems fine

2022-10-21 07:14 UTC, merged