Issue 3358 - Suspense and block registry update
maxi-blocks/maxi-blocks pull request #3840
Opened 2022-10-28 12:25 UTC by Naaaaiix

# Description

As part of the optimization process, I've tried to use the new [React `Suspense`](https://beta.reactjs.org/apis/react/Suspense) to check if it would help speeding up while setting a Gutenberg `deviceType` equal to `Tablet` or `Mobile`, as Gutenberg reloads everything on an `iframe`. It didn't make the difference, but I like having the spinner loading while the block and its styles are loading. Here on this video we can see the same page loaded first without `Suspense`, and then with it:

https://user-images.githubusercontent.com/50477222/198586129-2b759b7c-0712-42df-8c96-f6449c81586a.mp4

Also, took advantage of this situation to update the Maxi blocks registration with a lighter object and new `apiVersion` 👍 

# How Has This Been Tested?

Load should have same speed, but with spinners on the loading blocks. Once ended the spinner, block should appear perfect with its correct styles. The rest should work as before 😋 

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test the spinner effect

**_ Pre-Code Testing _**

-   [ ] Test the spinner effect
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

2022-10-28 12:30 UTC, kyrapieterse approved these changes

2022-10-31 13:14 UTC, Olekrut approved these changes

2022-10-31 15:33 UTC, myroslavve approved these changes

2022-10-31 15:53 UTC, myroslavve requested changes
Found something right after approving. Editor breaks when I insert block with opened settings sidebar. But if I wait like 5 seconds after page loaded, it doesn't break.

https://user-images.githubusercontent.com/53875005/199049969-89bba652-b676-40d5-800a-b8e186e89c96.mp4

The error: 
```
TypeError: Cannot read properties of null (reading 'forEach')
    at http://localhost:8888/wp-includes/js/dist/block-editor.js?ver=39c7981dd22ec80281080455892940e6:40730:16
    at updateMemo (http://localhost:8888/wp-includes/js/dist/vendor/react-dom.js?ver=17.0.1:15897:21)
    at Object.useMemo (http://localhost:8888/wp-includes/js/dist/vendor/react-dom.js?ver=17.0.1:16443:18)
    at useMemo (http://localhost:8888/wp-includes/js/dist/vendor/react.js?ver=17.0.1:1557:23)
    at __experimentalBlockVariationTransforms (http://localhost:8888/wp-includes/js/dist/block-editor.js?ver=39c7981dd22ec80281080455892940e6:40728:73)
    at renderWithHooks (http://localhost:8888/wp-includes/js/dist/vendor/react-dom.js?ver=17.0.1:15015:20)
    at updateFunctionComponent (http://localhost:8888/wp-includes/js/dist/vendor/react-dom.js?ver=17.0.1:17386:22)
    at beginWork (http://localhost:8888/wp-includes/js/dist/vendor/react-dom.js?ver=17.0.1:19093:18)
    at HTMLUnknownElement.callCallback (http://localhost:8888/wp-includes/js/dist/vendor/react-dom.js?ver=17.0.1:3942:16)
    at Object.invokeGuardedCallbackDev (http://localhost:8888/wp-includes/js/dist/vendor/react-dom.js?ver=17.0.1:3991:18)
```

2022-12-20 15:35 UTC, closed without merging