Issue 3841 - Gap between blocks
maxi-blocks/maxi-blocks pull request #3853
Opened 2022-10-31 10:52 UTC by Marko64

Adds a constant margin of 50px in all blocks that are first on hierarchy (the ones that aren't wrapped by any other block) to allow leaving some space between them and letting the blue button to appear and add new blocks in the middle. Also made Container's indicators just appear when are selected, and added a label on them to difference `margin` and `padding`

Fixes #3841

PS: tests will break for sure, added an inline style for all blocks so snapshots will be like 🎆 

# Test checklist

**_ Front/Back Testing _**

-   [x] Make sure if you can click the block inserter between the blocks.
- [x] Make sure you can click the block inserter after set some margin to the blocks

**_ Pre-Code Testing _**

-   [x] Make sure if you can click the block inserter between the blocks.
- [x] Make sure you can click the block inserter after set some margin to the blocks
-   [x] Check no commented code and no unnecessary imports
-   [x] Standards of the project have been followed
-   [x] No errors/warnings on console

# Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [x] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

2022-11-04 14:46 UTC, Fybex requested changes
https://user-images.githubusercontent.com/46112160/200003305-bd744f61-419b-4403-a817-51b51cc41318.mp4

How we should display inserter is this case(when block isSelected and has margin) 🤔 

Or should we ignore this case for a moment?

2022-11-04 14:50 UTC, Fybex approved these changes

2022-11-04 14:59 UTC, elzadj approved these changes

2022-11-04 15:19 UTC, myroslavve requested changes

2022-11-04 16:25 UTC, Olekrut approved these changes

2022-11-07 08:51 UTC, moroz-art-dev approved these changes

2022-11-07 14:45 UTC, myroslavve approved these changes

2022-11-14 16:00 UTC, closed without merging