Issue 3763 - opacity hover
maxi-blocks/maxi-blocks pull request #3865
Opened 2022-11-01 17:54 UTC by myroslavve

# Description

Fixes #3763 

# How Has This Been Tested?
Checked that opacity hover works on all blocks.
Here are [all the blocks with changed hover opacity](https://github.com/maxi-blocks/maxi-blocks/files/9912806/hoveropacity.txt).

# Test checklist

**_ Front/Back Testing _**

-   [ ] Check that opacity hover works on all blocks

**_ Pre-Code Testing _**

-   [ ] Check that opacity hover works on all blocks
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

2022-11-02 07:48 UTC, Marko64 reviewed
Not sure if it's just me, but the hover doesn't work for most of the blocks. For example:
Icon, Container, Image, Number counter, Video, Accordion.

The hover opacity option is there, but it doesn't work.

2022-11-08 10:11 UTC, Marko64 approved these changes
It works now with all blocks.

2022-11-15 15:50 UTC, Olekrut approved these changes

2022-11-15 17:57 UTC, moroz-art-dev approved these changes

2022-11-16 13:42 UTC, elzadj approved these changes

2022-11-16 15:09 UTC, Naaaaiix requested changes
Tried to make run the migrator, but I couldn't, even using the shared code editor. @TeksPeks any idea of it?

PS: made it work, and yes, is necessary! 👍

2022-11-16 15:38 UTC, elzadj approved these changes

2022-11-17 08:22 UTC, merged