Issue 3820 Popover icon position for blocks with canvas ( video, image, SVG)
maxi-blocks/maxi-blocks pull request #3894
Opened 2022-11-05 22:35 UTC by Marko64

Changed the position of the upload button for the video block. It used to be in the canvas corner, but now it sits in the video corner.

Fixes #3820 

**_ Front/Back Testing _**

-   [ ] Check that the upload button is in the corner of the video and not canvas. Try changing the video width and make sure the button remains in the top right corner.
-   [ ] Make sure other blocks with the upload button (number counter, image, icon..) look as before.

**_ Pre-Code Testing _**

-   [ ] Check that the upload button is in the corner of the video and not canvas. Try changing the video width and make sure the button remains in the top right corner.
-   [ ] Make sure other blocks with the upload button (number counter, image, icon..) look as before.
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [x] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

2022-11-18 18:41 UTC, Olekrut requested changes
responsive support

[responsive.webm](https://user-images.githubusercontent.com/88893350/202778876-d74ab409-7b17-4659-9fad-c490a2a75a51.webm)

P.S.: Sorry, Marko) I guess, it is last one

2022-11-21 08:46 UTC, Olekrut approved these changes

2022-11-21 13:07 UTC, elzadj requested changes

2022-11-25 13:03 UTC, MeltingWings1 approved these changes

2022-12-07 19:58 UTC, Naaaaiix requested changes
As @Olekrut shared in a call, moving it to the right creates this other situation: when the block is next to the edge of the canvas, can't be accessible:

![pasted image 0 (1)](https://user-images.githubusercontent.com/50477222/206282960-baece527-6010-48e8-ac7d-99fd14ea64be.png)

2022-12-22 10:07 UTC, closed without merging