Issue 3900 toolbar UI bugs
maxi-blocks/maxi-blocks pull request #3902
Opened 2022-11-08 13:28 UTC by Marko64

Fixes #3900 

**Front/Back Testing**

-   [ ] Make sure everything from the screenshots has been fixed.
-   [ ] Check the toolbar for all blocks and make sure the inputs look normal (check colours and borders).

**Pre-Code Testing**

-   [ ] Make sure everything from the screenshots has been fixed.
-   [ ] Check the toolbar for all blocks and make sure the inputs look normal (check colours and borders).
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [x] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

2022-11-15 15:04 UTC, Olekrut approved these changes

2022-11-18 14:49 UTC, Olekrut approved these changes

2022-11-21 17:51 UTC, Olekrut approved these changes

2022-11-25 12:51 UTC, MeltingWings1 approved these changes

2022-11-25 14:00 UTC, elzadj requested changes
Great, just fix these and the conflicts please :+1:

2022-11-29 08:57 UTC, Naaaaiix approved these changes

2022-12-02 09:47 UTC, elzadj requested changes
Just the maxi text input selector left :+1:

2022-12-02 14:15 UTC, elzadj approved these changes

2022-12-02 14:56 UTC, merged