Issue 3746 - add height to background size and position control
maxi-blocks/maxi-blocks pull request #3928
Opened 2022-11-11 19:40 UTC by myroslavve

# Description
 - Added height settings to size settings of background layers, and renamed `size` → `width`
 - Added migrator for background size attributes

Fixes #3746

# How Has This Been Tested?
Checked that width and height settings on background control work. Checked that old patterns with bg size settings work.

# Test checklist

**_ Front/Back Testing _**

-   [ ] Check that width and height settings on background control work
-   [ ] Check that migrator works (here is [code editor from master](https://github.com/maxi-blocks/maxi-blocks/files/9992884/code_editor.txt), width of the background should be 62% there).

**_ Pre-Code Testing _**

-   [ ] Check that width and height settings on background control work
-   [ ] Check that migrator works (here is [code editor from master](https://github.com/maxi-blocks/maxi-blocks/files/9992884/code_editor.txt), width of the background should be 62% there).
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

2022-11-14 09:37 UTC, Marko64 requested changes
1. Height unit is undefined:

![Screenshot_1](https://user-images.githubusercontent.com/19425503/201625494-0e585292-e087-4ec4-bf34-b517074d9d22.jpg)

2. We should make the max value smaller for width when % is used.

I think in real situations, most people will use 100% or something around it. I don't see why anyone would want to have 1500% width, for example. Let's limit it to maybe 300%.

![Screenshot_2](https://user-images.githubusercontent.com/19425503/201625639-e4f3ca93-b12d-49d0-a691-470ce48c7036.jpg)

2022-11-21 09:35 UTC, Olekrut approved these changes

2022-11-25 12:07 UTC, MeltingWings1 approved these changes

2022-11-25 12:29 UTC, MeltingWings1 approved these changes

2022-11-29 07:52 UTC, Naaaaiix approved these changes

2022-11-29 09:50 UTC, merged