Issue 3827 and 3809 - default attributes for XXL, XL, L and so on
maxi-blocks/maxi-blocks pull request #3943
Opened 2022-11-16 11:18 UTC by elzadj

# Description

Fixes #3827 
Fixes #3809

# How Has This Been Tested?

Check the button padding on all screen sizes, and defaults for it (reset, etc.)

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type

**_ Pre-Code Testing _**

-   [ ] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

2022-11-18 09:04 UTC, Marko64 requested changes
1. Tested button padding on XXL and XL and resetting to make sure they reset to correct values (XXL to default XXL and XL to default XL values). This one is fixed.

2. It Seems like the container has been fixed for M but still not for S and XS.

M screenshot:
![Screenshot_3](https://user-images.githubusercontent.com/19425503/202663567-9853fbb7-a7f8-4ed0-aebb-3dd5615fafd2.jpg)

S screenshot:
![Screenshot_4](https://user-images.githubusercontent.com/19425503/202663598-6fcc1b71-8b74-470d-8239-545452549a84.jpg)

2022-11-20 08:52 UTC, Marko64 approved these changes

2022-11-21 09:39 UTC, moroz-art-dev approved these changes

2022-11-21 10:55 UTC, Naaaaiix reviewed
Mmmmmhhh... not sure if this is the correct fix for this issue and if it's the expected behaviour for creators. Couple of situations that doesn't look coherent with the rest of attributes situations:
1. On XL screen, the value appears as a placeholder, not as the value. Normally, placeholder is used when it has a default value coming from a different responsive stage:

https://user-images.githubusercontent.com/50477222/203032226-59f17ab8-ab46-45f1-b8f8-2f4f6edbef3d.mp4

2. On XXL screen happens the same: the values appear as placeholders.
3. On a lower responsive stage of XL, the general value is not prevailing and overwritting the default value of XL, so the situations is a different value:

https://user-images.githubusercontent.com/50477222/203032799-d2b05ea0-227d-4102-8df6-cb5cdd80d8ea.mp4

🤔

2022-11-25 11:45 UTC, MeltingWings1 approved these changes

2022-11-30 10:44 UTC, closed without merging