Issue 3950 - Transform control inputs ignore placeholder values on arrow value change
maxi-blocks/maxi-blocks pull request #3973
Opened 2022-11-24 17:09 UTC by MeltingWings1

# Description

Added default values for x and y and set the default value on square control to defaultX + defaultY instead of empty

Fixes #3950 

# How Has This Been Tested?

1. Add an icon maxi to any editor and test the transform scale X and Y.

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type

**_ Pre-Code Testing _**

-   [ ] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

2022-11-24 17:36 UTC, Marko64 approved these changes

2022-11-25 12:20 UTC, Olekrut requested changes
Transform
1) for scale is not working correct
2) translate - arrow control is not working, I guess, should work as like after we click reset
3) origin - values in inputs are not changing

[trsndform .webm](https://user-images.githubusercontent.com/88893350/203984314-594e5a8c-6c31-4d02-83c1-7edcd2a87e39.webm)

2022-11-26 06:54 UTC, Olekrut requested changes
1) scale - wrong position for control dot 

[control dot for scale.webm](https://user-images.githubusercontent.com/88893350/204075899-453df8bc-6425-43d9-86ba-13e81934d81d.webm)

2) scale - dot control when you are going to = 0

[control dot for = 0.webm](https://user-images.githubusercontent.com/88893350/204076029-9091619d-7659-4d19-9e9a-684bd89aec34.webm)

3) scale - control elements for negative values is not looking correct

[scale - control elements for negative values.webm](https://user-images.githubusercontent.com/88893350/204076616-61d3b187-8d2a-451d-9b5a-b3f0d47d1750.webm)

4) transform origin - wrong words in input fields

[ice_video_20221126-084501_edit_0.webm](https://user-images.githubusercontent.com/88893350/204076145-90b1c5e9-743e-4865-b79e-8e9571d0b457.webm)

P.S.: maybe need separate issues for some of the points?

2022-11-29 09:37 UTC, Naaaaiix approved these changes
Placeholder seems fixed to me, not sure if has been more changes we need to check @MeltingWings1. Good job 👍

2022-11-29 12:28 UTC, Olekrut approved these changes

2022-12-06 12:45 UTC, elzadj approved these changes

2022-12-06 12:48 UTC, merged