Issue 3601 - replace wp components with their maxi counterparts
maxi-blocks/maxi-blocks pull request #3975
Opened 2022-11-24 19:52 UTC by myroslavve

# Description

 - Added `Dahsicon` to the `Icon` component, so its `icon` prop can be string.
<details>
  <summary>Replaced wp copmonents in following places:</summary>

  - Remove marker button in map-maxi
![image](https://user-images.githubusercontent.com/53875005/203855663-1ed9fb80-823d-45f3-91f8-cf439531d1b4.png)
 - Map search input and buttons (top right corner of the block)
 - Buttons on row template selector
 - 'Select icon' button on svg icon maxi
 - 'Style card manager' button and icon
![image](https://user-images.githubusercontent.com/53875005/203855403-58d82c4a-c356-4574-9e3d-edba0684f027.png)
 - Mover and up/down buttons and their icons in toolbar
 - Icon for number counter replay button
 - Icon in toolbar buttons
  
</details>

Fixes #3601

# How Has This Been Tested?
Checked that all replaced components look good and work as they should.

# Test checklist

**_ Front/Back Testing _**

-   [ ] Check that replaced components that are listed higher look good.

**_ Pre-Code Testing _**

-   [ ] Check that replaced components that are listed higher look good.
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

2022-11-25 08:38 UTC, Rustam198804 approved these changes

2022-11-25 11:35 UTC, MeltingWings1 requested changes
Could you update the snapshot on the e2e test?

2022-11-25 15:15 UTC, Naaaaiix approved these changes
Awesome 😸

2022-11-26 18:58 UTC, elzadj approved these changes

2022-11-26 18:58 UTC, merged