Issue 3981 Popover position for small blocks
maxi-blocks/maxi-blocks pull request #3984
Opened 2022-11-25 15:49 UTC by Marko64

The goal is to position the popover button better for small blocks. One example is the icon block when you size it down completely. In that case, the popover button covers the icon and you can't see it.

Added a special class for the icon's popover only when the canvas width is set to fit the content.

Fixes #3981 

# Test checklist

**_ Front/Back Testing _**

-   [ ] Add an SVG and try to reproduce the issue when the popover button covers the icon.

**_ Pre-Code Testing _**

-   [ ] Add an SVG and try to reproduce the issue when the popover button covers the icon.
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [x] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

2022-11-26 07:14 UTC, Olekrut requested changes
looks much better, but
1) when popover bigger than svg can it be aligned by left border of popover icon
![image](https://user-images.githubusercontent.com/88893350/204077023-e43426b6-afd0-4e23-9ee5-3666fac5f9a7.png)
2) popover icon position when in canvas width:fit-content
![image](https://user-images.githubusercontent.com/88893350/204076975-70321fec-4549-4a1c-a9d5-b3968197772c.png)

2022-11-29 08:11 UTC, Naaaaiix requested changes

2022-11-29 12:42 UTC, Olekrut requested changes
[looks weird.webm](https://user-images.githubusercontent.com/88893350/204532028-56302e5d-5d2d-403f-93d9-67ebc4bc77db.webm)

2022-11-30 10:47 UTC, Olekrut approved these changes

2022-11-30 11:29 UTC, elzadj requested changes
Looks good, just use the ```classnames``` function how @Naaaaiix says, please :+1:

2022-11-30 14:28 UTC, elzadj approved these changes

2022-11-30 15:42 UTC, merged