Issues 3809 && 3945 - Resetting when winBase === XXL && `undefined` attributes become valued after reloading
maxi-blocks/maxi-blocks pull request #3989
Opened 2022-11-28 09:46 UTC by Naaaaiix

# Description

This branch aims to fix these 2 issues:
1. The commented UX on resetting when the padding for Button Maxi (follow the discussion on this PR #3967).
2. The uncomfortable issue we were finding on #3945 that doesn't allow `null` as a valid and different value than `undefined`.

As both issues were having troubles with the resetting, found a way to fix them both at the same time. The main implementation is based on 3 points:
1. Removed different default values on `attributes.js` that are affecting other responsive attributes than `general` and moved into `blockData` with the label `maxiAttributes`.
2. Added a new system on `maxiBlockComponent` class that, in case that new attributes exist, they are implemented on the first creation of the block overwriting the WP default attribute.
3. Added a new handle for the resetting called `handleOnReset` and a new capacity to `getDefaultAttribute` to iterate that new `maxiAttributes` object.

This way, as for WP that attributes doesn't have a default value, they can stay `undefined` in case we save like that, so problem number 2 is solved. In the other side, the issue we were facing on resetting from different responsive stages of the Button Maxi padding is solved, as now XXL and XL values are decoupled and can be reset easily. It may not fix 100%, but enhanced for sure. Once seeing the necessity and the flow of the creators, we can take advantage of the new `handleOnReset` function to even go further and improve the experience for that concrete cases/exceptions. 

Let's see if this works out and we can move forward with these issues 👍 

PS: this branch is a mix of the one pointing to #3967 and the other presented and enhanced on [this comment](https://github.com/maxi-blocks/maxi-blocks/issues/3945#issuecomment-1325472961). So, if it's merged, the rest of PRs can be closed 👍 

Fixes #3809 && #3945

# How Has This Been Tested?

It must be tested in many different ways:
1. Test modifying and resetting from different breakpoints the `Width/height` options of Container and Row Maxi
2. Test modifying and resetting from different breakpoints the Padding of Button Maxi
3. Test modifying and resetting from different breakpoints SC
* to all of these points, save and reload and check the attributes are correctly saved

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test the points indicated above

**_ Pre-Code Testing _**

-   [ ] Test the points indicated above
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

2022-11-29 10:11 UTC, Olekrut requested changes
![image](https://user-images.githubusercontent.com/88893350/204501067-23d30bea-4c93-48a8-b64d-588fbc37f9b8.png)

need migrator for buttons which had padding:0px;

2022-11-30 15:34 UTC, elzadj approved these changes

2022-12-01 14:28 UTC, Olekrut requested changes
[reset for paddings are working not correct.webm](https://user-images.githubusercontent.com/88893350/205078057-387f5f3a-8f21-495e-89d6-59858fa9c2c1.webm)

[button paddings.txt](https://github.com/maxi-blocks/maxi-blocks/files/10133202/button.paddings.txt)

2022-12-02 11:44 UTC, MeltingWings1 requested changes

2022-12-08 10:43 UTC, MeltingWings1 approved these changes

2022-12-08 11:24 UTC, Olekrut approved these changes

2022-12-08 12:19 UTC, elzadj approved these changes

2022-12-12 09:45 UTC, merged