Fixed Columns native WP block into a Maxi Column
maxi-blocks/maxi-blocks pull request #3990
Opened 2022-11-28 11:41 UTC by Rustam198804

# Description

Added css width: 100% for column native WP block

Fixes #3912 

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type

**_ Pre-Code Testing _**

-   [ ] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

2022-11-28 13:39 UTC, Marko64 approved these changes

2022-11-29 08:13 UTC, Naaaaiix requested changes
This implementation just fixes WP native Columns block. Paragraph, Image or whatever other block won't look good inside a Maxi grid. Need fully compatibility please 👍

2022-11-29 13:32 UTC, Olekrut requested changes
![image](https://user-images.githubusercontent.com/88893350/204542005-297bccfe-6e4c-4337-8891-dec40ea5b194.png)

VE is ok
EE looks not good yet

2022-12-01 14:02 UTC, Olekrut approved these changes

2022-12-01 18:35 UTC, Naaaaiix approved these changes
Well done @Rustam198804 🚀

2022-12-01 18:35 UTC, merged