Issue 3958 - Background position after reset
maxi-blocks/maxi-blocks pull request #3997
Opened 2022-11-29 08:46 UTC by MeltingWings1

# Description

Removed the breakpoint from getDefaultAttribute in axis-control. It gets undefined as the default value for unit which breaks the input.

Fixes #3958 

# How Has This Been Tested?

1. Add different maxi blocks (text-maxi, container-maxi, etc)
2. Add a background layer and select set seperate
3. Change one of the position fields and then reset
4. Change it again and it should still update on the screen

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type

**_ Pre-Code Testing _**

-   [ ] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

2022-11-29 09:24 UTC, Naaaaiix reviewed
The idea fixes the issue, but breaks other parts:

https://user-images.githubusercontent.com/50477222/204488759-3b68c2b5-c9cb-44a6-8a79-16ec088b0d5d.mp4

The change on AxisControl affects other instances of the component. Let me try to give some clues about this issue. The most important thing to understand with BackgrouldLayersControl is its attributes: instead of Gutenberg normal attributes, what we've got is an ['array'](https://github.com/maxi-blocks/maxi-blocks/blob/5701aa355de196bc26b5c20d06722517cc8c2ba5/src/extensions/styles/defaults/background.js#L13-L18). The reason why is an array is that we can have infinite layers, and each layer will be an object inside this array. In that sense, WP native function to get default block attributes, `getBlockAttributes` ('@wordpress/blocks'), can't get the defaults of each layer as they aren't registered into the block `attributes.js` file, so the source is other. In this case, the source of each layer comes from `src/components/background-control/layers.js`. So, resuming:
1. Removing the breakpoint on the `onReset` function of AxisControl breaks other instances of the component.
2. The source to retrieve the default attribute is different from the usual one, so we need to find a way to let BackgroundLayersControl to reset from it's default layers values 👍

2022-12-07 11:42 UTC, Marko64 approved these changes

2022-12-07 16:58 UTC, Olekrut approved these changes

2022-12-07 17:27 UTC, elzadj approved these changes

2022-12-07 17:33 UTC, Naaaaiix requested changes
The issue has been fixed, but I think this implementation has an error: is delegating the responsibility of BackgroundControl reset into AxisControl. To keep a clean code strategy, each component should try to be as isolated as possible. Please, let's find another solution for it; one that can work can be to add a `onReset` prop on AxisControl that accepts a function, and in case it exists it is run instead of the original method used on AxisControl. That way the responsibility gets back to BackgroundControl and AxisControl keeps being an isolated and independent component 👍

2022-12-13 15:08 UTC, closed without merging