3988 - ColumnSizeControl is returning an undefined value
maxi-blocks/maxi-blocks pull request #4001
Opened 2022-11-29 10:48 UTC by MeltingWings1

# Description

getColumnTemplate under GetColumnDefaultValue had false set as the breakpoint value. Removed false.

Fixes: #3998 

# How Has This Been Tested?

1. Add a container maxi with multipe columns
2. Reset the column size and it should go back to the default size

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type

**_ Pre-Code Testing _**

-   [ ] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

2022-12-01 10:35 UTC, Marko64 requested changes
Works good!

One small change:
- If you do not change the value and reset it, or if you reset twice, the input value goes blank. The correct width is still applied, but the input value should still be displayed.

2022-12-01 15:23 UTC, Olekrut requested changes
[should reset to column size value by the current row scheme.webm](https://user-images.githubusercontent.com/88893350/205091207-a61977ca-110a-42ad-a9dd-002bbb9a1b2b.webm)

not sure how it should be fixed(

2022-12-06 10:03 UTC, Olekrut approved these changes

2022-12-06 10:11 UTC, Naaaaiix approved these changes

2022-12-06 11:14 UTC, Marko64 approved these changes

2022-12-06 11:51 UTC, elzadj approved these changes

2022-12-06 11:52 UTC, merged