Scale - control elements for negative values is not looking correct
maxi-blocks/maxi-blocks pull request #4011
Opened 2022-11-30 10:59 UTC by MeltingWings1

# Description

Added min and max values to the input fields. Scale should not have negative values

Fixes #4004

# How Has This Been Tested?

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type

**_ Pre-Code Testing _**

-   [ ] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

2022-11-30 11:21 UTC, Olekrut requested changes
no, we cant set negative value anymore( sometimes it is need!
sorry for confusion
I meant that need make range from -100 to 300 and fix navigation for that but I guess easier for fix will be make from -300 to 300. Then dot nav at 0 will be on the middle

2022-12-07 09:31 UTC, Olekrut requested changes
[weird behavior for dot nav.webm](https://user-images.githubusercontent.com/88893350/206141199-e675b354-4c32-43fc-b461-c5526b5f2e37.webm)

the same dot nav position for values: default 100, custom 0

2022-12-07 17:08 UTC, Olekrut requested changes
[displaying square control depend on the speed dot nav.webm](https://user-images.githubusercontent.com/88893350/206247653-a64daf5f-0380-44a4-bd61-5953185f0cf4.webm)



looks not right
square control is stopping in point when value changing to negative

2022-12-22 14:55 UTC, Naaaaiix approved these changes

2022-12-22 14:55 UTC, Olekrut approved these changes

2022-12-22 15:32 UTC, merged