Issue 3925 Preview for filled icons
maxi-blocks/maxi-blocks pull request #4017
Opened 2022-12-01 14:36 UTC by Marko64

The editor/library/editor.css file overrides the stroke colour for all icons in the settings. Added an exception for the button icon so it now shows the same colours ad the editor.

Fixes #3925

# Test checklist

**_ Front/Back Testing _**

-   [ ] Add a button and a filled icon. Check that fill, and stroke colours are the ones you choose from the palette. Test shapes and line icons too.

**_ Pre-Code Testing _**

-   [x] Add a button and a filled icon. Check that fill, and stroke colours are the ones you choose from the palette. Test shapes and line icons too.

-   [x] Check no commented code and no unnecessary imports
-   [x] Standards of the project have been followed
-   [x] No errors/warnings on console

# Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [x] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

2022-12-01 15:49 UTC, Olekrut requested changes
[not fixed.webm](https://user-images.githubusercontent.com/88893350/205097310-d36b137d-7e29-4843-a774-c91c10c49cd4.webm)

2022-12-27 15:32 UTC, Olekrut approved these changes

2022-12-28 11:10 UTC, myroslavve approved these changes

2022-12-28 13:13 UTC, Fybex requested changes

2022-12-28 13:49 UTC, Fybex approved these changes

2022-12-29 08:16 UTC, Naaaaiix approved these changes
Let's resolve conflicts and merge 🚀

2022-12-29 14:46 UTC, closed without merging