Dashboard text updates
maxi-blocks/maxi-blocks pull request #4064
Opened 2022-12-12 16:29 UTC by ckp267

fixed : https://github.com/maxi-blocks/maxi-blocks/issues/3962

Please check Maxi Dashboard for general bugs 
/wp-admin/admin.php?page=maxi-blocks-dashboard
wp-admin/admin.php?page=maxi-blocks-dashboard&tab=maxi_blocks_settings

========================================================================

Updated lots of text and all the links to work with short links /go/
@elzadj 
For some reason, no matter what i do i cannot get the h4 to show up for the google maps part
I commented it out now but you can see the alignment is shit.
Please fix that when you review the commit. See SC.

![image](https://user-images.githubusercontent.com/7437580/207099362-c7b71150-5ec4-484f-8776-dc53f0606168.png)

2022-12-20 15:21 UTC, elzadj approved these changes

2022-12-21 11:52 UTC, Marko64 approved these changes

2022-12-21 12:25 UTC, Olekrut approved these changes
Perfect)) only one thing ( not important), maybe make transition for opening tabs a bit longer? Looks very fast as for me..
https://jam.dev/c/7da927ac-e000-4b65-baf0-38fb6223ef7f

2022-12-21 14:47 UTC, MeltingWings1 requested changes
Need to remove commented out code before merging.

2022-12-21 18:28 UTC, Naaaaiix approved these changes

2022-12-22 09:53 UTC, MeltingWings1 approved these changes

2022-12-22 09:54 UTC, merged