Issue 4066 Accordion default animation duration
maxi-blocks/maxi-blocks pull request #4069
Opened 2022-12-13 11:29 UTC by Marko64

Added default 0.3 animation duration for accordion.

Fixes #4066

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test that the default animation duration for the accordion block is 0.3.

**_ Pre-Code Testing _**

-   [ ] Test that the default animation duration for the accordion block is 0.3.
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [x] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

2022-12-13 12:47 UTC, Naaaaiix requested changes
This implementation changes the way it looks as it forces the input to have a default value to show, but is not doing any change on the final result on frontend. If the attribute is not changed, there's not going to be any change. Please @Marko64, change the default attribute and not the component that is rendering it 👍

2022-12-14 11:47 UTC, Olekrut requested changes
1) A bit dragging on backend when accordion in the bottom of page
2) Can be transition on backend as well? ( not very important)
 Frontend is ok

2022-12-14 14:49 UTC, Naaaaiix requested changes

2022-12-21 11:18 UTC, Olekrut approved these changes

2022-12-21 13:26 UTC, Naaaaiix approved these changes
Looks good in terms of code 👍

2022-12-21 16:34 UTC, elzadj approved these changes

2022-12-21 16:34 UTC, merged