Issue 4078 - Strange behavior of Image on Column
maxi-blocks/maxi-blocks pull request #4084
Opened 2022-12-14 15:16 UTC by Naaaaiix

# Description

Basically, is fixed what the issue was commenting lol

Fixes #4078 

# How Has This Been Tested?

Copy the code-editor of the issue and check the size of one image is not affecting the other one. 

# Test checklist

**_ Front/Back Testing _**

-   [ ] Check the code editor of the issue works as expected

**_ Pre-Code Testing _**

-   [ ] Check the code editor of the issue works as expected
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] My changes generate no new warnings/errors
-   [x] I have added/updated tests that prove my fix is effective or that my feature works
-   [x] New and existing unit tests pass locally with my changes

2022-12-14 16:28 UTC, Olekrut requested changes
![image](https://user-images.githubusercontent.com/88893350/207651902-cd544d04-a1b9-4d4e-b918-4b77d1666595.png)
Height of image in first column influence to height of image in second column anyway
Only on backend
![image](https://user-images.githubusercontent.com/88893350/207652474-3e69977e-870c-47b7-8608-5d0b2fd9462b.png)

2022-12-15 09:15 UTC, Marko64 approved these changes

2022-12-15 10:29 UTC, Olekrut approved these changes

2022-12-15 10:32 UTC, elzadj approved these changes

2022-12-15 10:50 UTC, merged