Issue 4048 - SC typography
maxi-blocks/maxi-blocks pull request #4090
Opened 2022-12-15 16:44 UTC by elzadj

# Description

Fixes ```text-indent```  for SC.
Removes ```text-direction``` and  ```text-orientation```.

Fixes #4048 

# How Has This Been Tested?

Tested typography for different SCs.

# Test checklist

**_ Front/Back Testing _**

-   [x] Test SC typography for different blocks
-   [x] Test that block's typography also works
-   [x] Test typography for hover state 
-   [x] Check that the settings work on frontend
-   [x] Check that backend works and saves the settings after the editor reload
-   [x] Same 1-5 points on responsive

**_ Pre-Code Testing _**

-   [ ] Test SC typography for different blocks
-   [ ] Test that block's typography also works
-   [ ] Test typography for hover state 
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-5 points on responsive
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] My changes generate no new warnings/errors
-   [x] I have added/updated tests that prove my fix is effective or that my feature works
-   [x] New and existing unit tests pass locally with my changes

2022-12-16 12:48 UTC, Marko64 approved these changes

2022-12-17 10:36 UTC, Olekrut requested changes
![image](https://user-images.githubusercontent.com/88893350/208237389-51734998-05a2-4184-8508-e953b244cdf3.png)
1) text-orientation is not correct by default ( for none )
2) space between drop-list fields
3) height of SC field to big, cant see all tabs on the bottom - https://jam.dev/c/94f56e65-8555-49e6-a2cb-cff39591b5ef

2022-12-19 09:07 UTC, Olekrut requested changes
https://jam.dev/c/54fba057-a0bc-4437-b612-584743eced2f

Units for text-indent is not working correct after click to reset button

2022-12-20 08:39 UTC, Olekrut requested changes
![image](https://user-images.githubusercontent.com/88893350/208621284-3a1ed08f-bfbc-4d9e-8fd5-70fb1836cc64.png)
line-height for button - preview is not working

2022-12-21 10:48 UTC, Olekrut approved these changes

2022-12-21 14:30 UTC, MeltingWings1 approved these changes

2022-12-22 14:34 UTC, Naaaaiix approved these changes

2022-12-23 07:39 UTC, merged