Flexbox UI
maxi-blocks/maxi-blocks pull request #4091
Opened 2022-12-16 14:45 UTC by Rustam198804

# Description

Fixes #4040 

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type

**_ Pre-Code Testing _**

-   [ ] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

2022-12-16 15:30 UTC, Marko64 requested changes
Looking good.
One small thing: Some icons move up when you select them. I think it's because the border is added on click. Perhaps the buttons can have a transparent border in normal state and just change the colour on click.

2022-12-19 11:27 UTC, Marko64 approved these changes

2022-12-26 11:56 UTC, Olekrut approved these changes

2022-12-26 17:10 UTC, Fybex requested changes

2022-12-27 17:25 UTC, Fybex approved these changes
Two comments which left aren't necessary, so approving, but if you don't mind and don't have any doubts, apply them please 🙏

2022-12-28 09:20 UTC, Naaaaiix reviewed
https://user-images.githubusercontent.com/50477222/209789139-63f8e989-92eb-45c9-b230-390d24b9765a.mp4

2023-01-19 15:13 UTC, elzadj approved these changes

2023-01-19 15:13 UTC, merged