Issue 4132 - Video background fallback
maxi-blocks/maxi-blocks pull request #4137
Opened 2022-12-23 15:00 UTC by Marko64

Removed the video background fallback option from the hover tab. 

Fixes #4132 

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test that the bg video fallback option exists in the normal state but doesn't in the hover state.

**_ Pre-Code Testing _**

-   [x] Test that the bg video fallback option exists in the normal state but doesn't in the hover state.
-   [x] Check no commented code and no unnecessary imports
-   [x] Standards of the project have been followed
-   [x] No errors/warnings on console

# Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [x] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

2022-12-26 11:03 UTC, Olekrut requested changes
I guess, it should be removed from IB as well

2022-12-26 12:31 UTC, Olekrut approved these changes

2022-12-26 15:09 UTC, Fybex approved these changes

2022-12-27 08:17 UTC, Naaaaiix approved these changes

2022-12-27 08:17 UTC, merged