Issue 3938 - IB reset
maxi-blocks/maxi-blocks pull request #4140
Opened 2022-12-23 17:06 UTC by myroslavve

# Description
Changes:
 - changed all `handleOnReset` calls to adding `isReset: true` to onChange object, and calling `handleOnReset` on object in `handleSetAttributes`.
 - using `isReset: true` in `onChange` of `settingsComponent` in relation control to reset values to the ones that are in block by  deleting them from relation attributes.
 - Moved `getStyles` out of `onChange` and created function `getStylesObj` in relation control.

Fixes #3938

# How Has This Been Tested?
Tested that `handleOnReset` is always called on reset and `isReset` is not saved as attribute. Also tested that reset works correct in IB.

# Test checklist

**_Front/Back Testing_**

-   [ ] Test reset on IB in different settings.
-   [ ] Test reset on IB on responsive.

**_Pre-Code Testing_**

-   [ ] Test reset on IB in different settings.
-   [ ] Test reset on IB on responsive.
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] My changes generate no new warnings/errors
-   [x] I have added/updated tests that prove my fix is effective or that my feature works
-   [x] New and existing unit tests pass locally with my changes

2022-12-26 16:27 UTC, Olekrut requested changes
https://jam.dev/c/10507dd3-d7be-44d4-b830-b41273f96683
units for box-shadow are not dropping

2022-12-26 16:48 UTC, Olekrut approved these changes

2022-12-27 09:11 UTC, Naaaaiix approved these changes
Amazing job @TeksPeks, couldn't be done better 👏 

PS: please @Fybex, I'd really appreciate if you can have a look also as it's related with RelationControl 😸

2022-12-27 13:20 UTC, Fybex requested changes
Great job @TeksPeks, love your refactor of some parts of `RelationControl`.

But, @Naaaaiix, @TeksPeks is it a good idea to add `isReset` into attributes object? Why we can't transform `maxiSetAttributes({...obj, isReset})` to `maxiSetAttributes(obj, isReset)`.

I think it will help to debug, because it won't confuse that some params inside of attributes object, and it will have better visibility in debugger. Also, what if in some day we'll have `isReset` attribute? And in general, it's more natural approach IMO.

2022-12-27 17:18 UTC, Fybex approved these changes

2022-12-29 07:50 UTC, Naaaaiix approved these changes

2022-12-30 12:34 UTC, merged