Issue 4094 - BG video
maxi-blocks/maxi-blocks pull request #4146
Opened 2022-12-26 10:46 UTC by myroslavve

# Description
 - Added default video URL on background video;
 - Fixed fallback not appearing on uploader.
 
 Didn't fix the first point, as it will be fixed on #4093

Fixes #4094 

# How Has This Been Tested?
Checked that background fallback appears on uploader. Checked that on adding of video layer, it has default video selected.

# Test checklist

**_ Front/Back Testing _**

-   [ ] Check that background fallback appears on uploader. 
-   [ ] Check that on adding of video layer, it has default video selected.

**_ Pre-Code Testing _**

-   [x] Check that background fallback appears on uploader. 
-   [x] Check that on adding of video layer, it has default video selected.
-   [x] Check no commented code and no unnecessary imports
-   [x] Standards of the project have been followed
-   [x] No errors/warnings on console

# Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] My changes generate no new warnings/errors
-   [x] I have added/updated tests that prove my fix is effective or that my feature works
-   [x] New and existing unit tests pass locally with my changes

2022-12-26 14:31 UTC, Marko64 approved these changes

2022-12-26 14:52 UTC, Olekrut requested changes
https://jam.dev/c/dff22060-d16a-412d-9897-7b163fcc8623
BG Video is not covered since begin only after Hover

2022-12-27 08:15 UTC, Naaaaiix approved these changes

2022-12-27 09:11 UTC, Olekrut approved these changes

2022-12-27 12:09 UTC, Fybex approved these changes

2022-12-28 07:57 UTC, merged