Issue 3996 - Opacity location
maxi-blocks/maxi-blocks pull request #4161
Opened 2022-12-29 08:15 UTC by Marko64

- Moved the opacity settings to the advanced tab for all blocks.
- Made the button icon disappear if the breakpoint is not general and if the icon is not set. _Perhaps the code can be cleaner here?_

Fixes #3996 

# Test checklist

**_ Front/Back Testing _**

-   [ ] Check all blocks and make sure that opacity is in the advanced tab everywhere.
-   [ ] Make sure that the opacity still works normally in general.
-   [ ] Test the button icon. It should show on the general breakpoint in all cases, and should show on responsive only if the icon is set. 

**_ Pre-Code Testing _**

-   [ ] Check all blocks and make sure that opacity is in the advanced tab everywhere.
-   [ ] Make sure that the opacity still works normally in general.
-   [ ] Test the button icon. It should show on the general breakpoint in all cases, and should show on responsive only if the icon is set. 
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [x] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

2022-12-29 14:36 UTC, Olekrut approved these changes

2022-12-29 15:40 UTC, myroslavve requested changes
Search icon tab has the same problem, when the icon is removed, so I think need to do the same there.
![image](https://user-images.githubusercontent.com/53875005/209975992-b44d7631-83e4-4b6f-ae34-bfa0ef34faa3.png)

2022-12-30 13:51 UTC, myroslavve requested changes

2023-01-05 10:59 UTC, Fybex approved these changes

2023-01-05 14:11 UTC, myroslavve approved these changes

2023-01-05 14:32 UTC, elzadj approved these changes

2023-01-05 14:32 UTC, merged