Issue 4062 - video with image
maxi-blocks/maxi-blocks pull request #4163
Opened 2022-12-29 09:55 UTC by myroslavve

# Description
 - In image tab in sidebar added media uploader for ability to remove image.
 - Added `width/height` settings for image in video block.
 - The aspect ratio settings were modifying aspect ratio of the video when it was in pop-up, not the block canvas, changed that setting to always affect the block canvas and added settings for aspect ratio of video itself in 'Popup settings' tab.
 - Created `AspectRatioControl` which is a `SelectControl` with default aspect ratio options.

Fixes #4062

# How Has This Been Tested?
Checked that it is possible to remove image, change its width and height and change the aspect ratio.

# Test checklist

**_ Front/Back Testing _**

-   [x] Check if it is possible to remove image, change its width and height
-   [ ] Check if it is possible to change the aspect ratio

**_ Pre-Code Testing _**

-   [ ] Check if it is possible to remove image, change its width and height
-   [ ] Check if it is possible to change the aspect ratio
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

2022-12-29 11:14 UTC, Marko64 approved these changes

2022-12-29 14:50 UTC, Olekrut requested changes
1) https://jam.dev/c/f366ff4b-9746-4dcd-ba2e-e7f4e44cd778
after hide image, video doesn't have height
I guess, in this case play icon should be not absolute
2) maybe have sense to add opacity for image?

2022-12-30 13:48 UTC, Olekrut requested changes
https://jam.dev/c/0f558c55-9561-46b2-98fb-ab625726d4e7
check Play icon position in different cases, should be center

2022-12-30 14:27 UTC, Olekrut approved these changes

2022-12-30 17:03 UTC, Fybex requested changes

2023-01-02 14:33 UTC, Fybex approved these changes

2023-01-03 09:53 UTC, elzadj approved these changes

2023-01-03 09:53 UTC, merged