Issue 4171- Removed inset from divider
maxi-blocks/maxi-blocks pull request #4172
Opened 2022-12-30 11:46 UTC by Marko64

Removed the `inset` box shadow option for the divider block.

Fixes #4171 

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test that there's no inset option under box-shadow for `divider`.
-   [ ] Test that the option is still there for other blocks.

**_ Pre-Code Testing _**

-   [ ] Test that there's no inset option under box-shadow for `divider`.
-   [ ] Test that the option is still there for other blocks.
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [x] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

2022-12-30 12:31 UTC, Olekrut requested changes
were need to remove only for block, not for canvas) it is working on Canvas

2023-01-13 15:29 UTC, Olekrut approved these changes

2023-01-13 16:23 UTC, Fybex approved these changes
Approving, it works, but I leave the comment that it might be better to just create a prop `disableInset` and give it a block divider-maxi box-shadow inspector and control

2023-01-16 08:44 UTC, Naaaaiix requested changes
> Approving, it works, but I leave the comment that it might be better to just create a prop `disableInset` and give it a block divider-maxi box-shadow inspector and control

Please @Marko64, implement what @Fybex commented. We shouldn't create exceptions inside the components, that can create uncontrolled effects and also is running unnecessary processes (like getting the current block name) 👍  Thanks 😸

2023-01-16 17:07 UTC, Olekrut approved these changes

2023-01-17 07:25 UTC, Fybex approved these changes

2023-01-17 08:10 UTC, Naaaaiix approved these changes

2023-01-17 08:28 UTC, merged