Issue 4175 - Text border affecting width
maxi-blocks/maxi-blocks pull request #4182
Opened 2023-01-03 11:44 UTC by Marko64

Changed text hover and select from border to outline because it doesn't affect the element's width.

Also changed the hover colour and made the outline with the same so it looks a bit better.

Fixes #4175 

# Test checklist

**_ Front/Back Testing _**

-   [ ] Check the case from the issue where text width was affected by the border.

**_ Pre-Code Testing _**

-   [ ] Check the case from the issue where text width was affected by the border.
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [x] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

2023-01-13 17:15 UTC, Olekrut requested changes
https://jam.dev/c/dd3ebe29-f491-4bcd-b60f-956826fd7d61
Is not fixed

2023-01-19 15:57 UTC, Olekrut requested changes
https://jam.dev/c/fc136cbd-23c4-4ba1-b8e0-c411c60749e7
try in the Row! Dasha confirmed this bug
[text.txt](https://github.com/maxi-blocks/maxi-blocks/files/10458355/text.txt)

2023-02-20 08:16 UTC, Olekrut approved these changes

2023-02-20 08:30 UTC, Naaaaiix approved these changes

2023-02-22 13:45 UTC, merged