Issue 4114 - Standard style card
maxi-blocks/maxi-blocks pull request #4186
Opened 2023-01-03 15:53 UTC by elzadj

# Description

Adds matching with a standard SC to fill in missing props for newly imported SCs. Also reduces exported SC's code. 

Read #4114 for more details.

You need to reset the SCs first: ```wp.data.dispatch('maxiBlocks/style-cards').resetSC()```

and also 
```npm i --save deep-object-diff```

Fixes #4114

# How Has This Been Tested?

Test import and export for SCs in general. 

# Test checklist

**_ Front/Back Testing _**

-   [ ] Import several SCs from the library, 
-   [ ] Check that they have ```white-space```, ```word-spacing```, ```bottom-gap```, ```text-indent``` props for typography after import.
-   [ ] Check that the typography works in SC
-   [ ] Check that other SC settings are working
-   [ ] On frontend too
-   [ ] Export an SC to a .txt file
-   [ ] Import it and check the imported SC

**_ Pre-Code Testing _**

-   [x] Import several SCs from the library, 
-   [x] Check that they have ```white-space```, ```word-spacing```, ```bottom-gap```, ```text-indent``` props for typography after import.
-   [x] Check that the typography works in SC
-   [x] Check that other SC settings are working
-   [x] On frontend too
-   [x] Export an SC to a .txt file
-   [x] Import it and check the imported SC
-   [x] Check no commented code and no unnecessary imports
-   [x] Standards of the project have been followed
-   [x] No errors/warnings on console

# Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] My changes generate no new warnings/errors
-   [x] I have added/updated tests that prove my fix is effective or that my feature works
-   [x] New and existing unit tests pass locally with my changes

2023-01-13 10:55 UTC, Olekrut requested changes
https://jam.dev/c/06eab0ce-90c3-41f6-a570-928d5966b580
1) white-space is not working on backend (button)
2) bottom-gap is not working (button)
3) text-indent is braking row on backend https://jam.dev/c/00737fa7-438e-4d55-adf0-43a401634f6c
4) reset button is not resetting value in drop-list https://jam.dev/c/d495fa32-06ff-4418-a7e8-edcd524185ec

2023-01-13 12:55 UTC, Olekrut approved these changes

2023-01-16 11:52 UTC, Fybex approved these changes

2023-01-16 12:22 UTC, myroslavve approved these changes

2023-01-16 14:18 UTC, merged