Issue 4158 - text maxi list indent
maxi-blocks/maxi-blocks pull request #4191
Opened 2023-01-06 10:16 UTC by myroslavve

# Description
 - Changed how indents work on list.
 - Added test for multiline list item to check for correct styles.

Fixes #4158 

# How Has This Been Tested?
Changed settings in list options and typography controls and checked that they work right.

# Test checklist

**_ Front/Back Testing _**

-   [x] Check that issue is fixed.
-   [x] Change settings in list options and typography controls and check that they work right.

**_ Pre-Code Testing _**

-   [x] Check that issue is fixed.
-   [x] Change settings in list options and typography controls and check that they work right.
-   [x] Check no commented code and no unnecessary imports
-   [x] Standards of the project have been followed
-   [x] No errors/warnings on console

# Checklist

-   [X] My code follows the style guidelines of this project
-   [X] I have performed a self-review of my code
-   [X] I have commented my code, particularly in hard-to-understand areas
-   [X] My changes generate no new warnings/errors
-   [X] I have added/updated tests that prove my fix is effective or that my feature works
-   [X] New and existing unit tests pass locally with my changes

2023-01-09 10:04 UTC, Marko64 approved these changes

2023-01-12 14:38 UTC, Olekrut approved these changes

2023-01-12 19:14 UTC, Fybex approved these changes

2023-01-13 08:58 UTC, Naaaaiix requested changes
`Text indent` option seems is not working:

https://user-images.githubusercontent.com/50477222/212279581-c20828b2-f075-4746-b9ca-03aa6880d187.mp4

2023-01-19 15:31 UTC, merged