Issue 3832 - Firefox underline
maxi-blocks/maxi-blocks pull request #4200
Opened 2023-01-11 10:56 UTC by myroslavve

# Description
Changes:
 - Text decoration is now rendered both on `paragraph` and `anchor` elements.

Fixes #3832 

# How Has This Been Tested?
Checked that text decoration looks right in FF and chrome. Also created a test for `getTextDecoration` which ensures text decoration will be on anchor if the whole text is a link and on paragraph otherwise.

# Test checklist

**_Front/Back Testing_**

-   [ ] Check text decoration in FF and chrome.
-   [ ] Change text-decoration and link settings, and check that they look right.
-   [ ] Check with link on whole text and only on some part of it.

**_Pre-Code Testing_**

-   [ ] Check text decoration in FF chrome and safari.
-   [ ] Change text-decoration and link settings, and check that they look right.
-   [ ] Check with link on whole text and only on some part of it.
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] My changes generate no new warnings/errors
-   [x] I have added/updated tests that prove my fix is effective or that my feature works
-   [x] New and existing unit tests pass locally with my changes

2023-01-12 08:01 UTC, Olekrut requested changes
[FF is not working correct for me yet.webm](https://user-images.githubusercontent.com/88893350/212010208-55a0469c-1ffd-4d27-a017-9b2ff7ba2de9.webm)
[FF colour.txt](https://github.com/maxi-blocks/maxi-blocks/files/10399352/FF.colour.txt)

2023-01-12 20:44 UTC, Olekrut approved these changes

2023-01-13 14:22 UTC, Fybex requested changes

2023-01-13 14:38 UTC, Fybex approved these changes

2023-01-16 08:29 UTC, Naaaaiix approved these changes
Awesome idea, couldn't resolve it better. Good job @TeksPeks 👏

2023-01-16 08:30 UTC, merged