Issue 3979 -`Column picker` on narrow spaces
maxi-blocks/maxi-blocks pull request #4202
Opened 2023-01-11 15:29 UTC by Naaaaiix

# Description

Check the issue, but basically this branch fixes the way we are displaying the Row Maxi 'Column Picker' on narrow wrappers.

Fixes #3979 

# How Has This Been Tested?

Created a Container Maxi and checked it looks the same than in master, then reduced the Container to 100/200/300/400/500px and check it was looking correct.

# Test checklist

**_ Front/Back Testing _**

-   [ ] Check what has been commented above.

**_ Pre-Code Testing _**

-   [ ] Check what has been commented above.
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

2023-01-12 07:28 UTC, Olekrut requested changes
https://jam.dev/c/ace7c1a5-fc34-4c49-9c96-79d9285e309e
not sure that it is the best decision, but if it is, then ok

I guess, need to make it as pop-up window, similar as like we are using column picker in toolbar
![image](https://user-images.githubusercontent.com/88893350/212006708-8355e1b3-6108-4e2e-99db-7b4ee426da5d.png)

2023-01-12 12:11 UTC, Olekrut approved these changes

2023-01-12 17:53 UTC, Fybex approved these changes

2023-01-16 09:40 UTC, elzadj approved these changes

2023-01-16 09:40 UTC, merged