Issue 4129 - Fixes SVG and button icon width range slider
maxi-blocks/maxi-blocks pull request #4205
Opened 2023-01-12 11:16 UTC by Marko64

SVG and button icon have default width attribute. This was preventing the range slider going below that value (you can check on master, SVG width wouldn't go below 64px for example).

Fixes #4129 

# Test checklist

**_ Front/Back Testing _**

-   [ ] Add an SVG icon and make sure if you can set the width below 64px using the range slider. Check that you can make it 0 and that it matches the input value too.
-   [ ] Do the same as above for the button icon width.
-   [ ] Test some other range sliders and make sure they work well.

**_ Pre-Code Testing _**

-   [x] Add an SVG icon and make sure if you can set the width below 64px using the range slider. Check that you can make it 0 and that it matches the input value too.
-   [x] Do the same as above for the button icon width.
-   [x] Test some other range sliders and make sure they work well.
-   [x] Check no commented code and no unnecessary imports
-   [x] Standards of the project have been followed
-   [x] No errors/warnings in console

# Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [x] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

2023-01-13 18:13 UTC, Olekrut approved these changes

2023-01-16 09:45 UTC, Fybex requested changes
even without tooltip I can see that range value isn't correct, or is it expected @Marko64 🤔 ?
<img width="277" alt="image" src="https://user-images.githubusercontent.com/46112160/212647660-2e10d0f8-abbe-4c57-b40f-ff42673c037c.png">

2023-01-18 15:26 UTC, Olekrut requested changes
https://jam.dev/c/c15e785e-d827-48a3-9b65-8690b5a12057
is not fixed for hover button

2023-01-19 15:31 UTC, Olekrut approved these changes

2023-01-20 09:20 UTC, Fybex approved these changes

2023-01-20 09:26 UTC, merged