Issue 4032 - `ClipPathControl` units support
maxi-blocks/maxi-blocks pull request #4229
Opened 2023-01-18 11:07 UTC by Fybex

# Description

Update:
- changed 100 preset colours for clip path points to darker ones
- added `px` support
- improved reset on reset to defaults
- removed error from `search-maxi` on iframe, when was fixing `ClipPathControl` after updates in iframe

Fixes #4032 

# How Has This Been Tested?

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test the component in normal state in sidebar (visual editor, points editor, different clip-path types)
-   [ ] Test the component in hover state in sidebar (if hover exists) (visual editor, points editor, different clip-path types)
-   [ ] Test the component in IB
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points on responsive (maxi `s`, `xs` and gutenberg `tablet`, `mobile`)
-   [ ] Test if search-maxi don't have an error in gutenberg iframe(when breakpoint was selected by gutenberg preview buttons: `tablet` or `iframe`)

**_ Pre-Code Testing _**

-   [x] Test the component in normal state in sidebar (visual editor, points editor, different clip-path types)
-   [x] Test the component in hover state in sidebar (if hover exists) (visual editor, points editor, different clip-path types)
-   [x] Test the component in IB
-   [x] Check that the settings work on frontend
-   [x] Check that backend works and saves the settings after the editor reload
-   [x] Same 1-4 points on responsive (maxi `s`, `xs` and gutenberg `tablet`, `mobile`)
-   [x] Test if search-maxi don't have an error in gutenberg iframe(when breakpoint was selected by gutenberg preview buttons: `tablet` or `iframe`)
-   [x] Check no commented code and no unnecessary imports
-   [x] Standards of the project have been followed
-   [x] No errors/warnings on console

# Checklist

-   [X] My code follows the style guidelines of this project
-   [X] I have performed a self-review of my code
-   [X] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [X] New and existing unit tests pass locally with my changes

2023-01-23 22:57 UTC, Olekrut requested changes
1)UI -
1.1)  fields are not in one line ( elements have different height)
![image](https://user-images.githubusercontent.com/88893350/214159593-43c17af0-d1fd-410e-8db4-cb5b16e7595b.png)
1.2) to add a bit space between 100 (3-digit number) and nav arrows
![image](https://user-images.githubusercontent.com/88893350/214161163-ad0b9986-ade7-4f4c-be77-651a52895580.png)

2) wrong logic for reset button on hover https://jam.dev/c/bd81d13d-9dca-42bc-9b4a-a52065661c54
3) https://jam.dev/c/d4d433aa-853a-430c-bcd1-4f5f37ad7e19 - error

2023-01-24 11:39 UTC, Olekrut requested changes
https://jam.dev/c/60f85216-d4b2-4896-bdf5-a32871187ecb
to make input field bigger for (4-digit number) as like 25.54
![image](https://user-images.githubusercontent.com/88893350/214282282-99933e7b-27b6-4037-966e-517303801442.png)

2023-01-24 15:55 UTC, Olekrut approved these changes

2023-01-25 11:27 UTC, myroslavve requested changes

2023-01-25 12:01 UTC, myroslavve approved these changes

2023-01-25 13:19 UTC, Naaaaiix approved these changes

2023-01-25 13:19 UTC, merged