Issue 4214 - Video placeholder URL
maxi-blocks/maxi-blocks pull request #4231
Opened 2023-01-18 13:50 UTC by Marko64

Added our default video URL to be the placeholder. Now if the input is empty it will get the default URL automatically.

Removed unneccessary placeholder text colour.

Deleted deprecated prop frameborder.

Fixes #4214 

**_ Front/Back Testing _**

-   [ ] Check that if the video URL input is empty, it gets the default video URL.
-   [ ] Test that the video URL input works normally in general.

**_ Pre-Code Testing _**

-   [x] Check that if the video URL input is empty, it gets the default video URL.
-   [x] Test that the video URL input works normally in general.
-   [x] Check no commented code and no unnecessary imports
-   [x] Standards of the project have been followed
-   [x] No errors/warnings on console

# Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [x] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

2023-01-18 14:21 UTC, Olekrut requested changes
The same for BG Video Layer

2023-01-18 15:48 UTC, Olekrut approved these changes

2023-01-19 13:02 UTC, myroslavve approved these changes

2023-01-19 15:13 UTC, Naaaaiix approved these changes

2023-01-19 15:14 UTC, merged