Issue 4228 - Column Maxi BlockResizer `width` error
maxi-blocks/maxi-blocks pull request #4232
Opened 2023-01-18 14:49 UTC by Naaaaiix

# Description

Blockresizer for Column Maxi was getting the `width` from the column attribute directly, without considering the `rowProps`. The way we calculate Column's width is using a `calc()` that gets the size and subtract the gap set by the Row. For example, considering a gap of 2.5% and a column size of 80%, the width of a column would be `calc(80% - 1.25%)`. 

Fixes #4228 

# How Has This Been Tested?

Loaded the code editor provided on the issue and tested it; also tested this other [code editor](https://github.com/maxi-blocks/maxi-blocks/files/10447510/columnwidth.txt), that looks like this on master:
<img width="817" alt="Captura de Pantalla 2023-01-18 a las 15 47 29" src="https://user-images.githubusercontent.com/50477222/213202173-4a86d694-2008-4915-a751-5dc81f706f7f.png">

and currently should looks like:
<img width="817" alt="Captura de Pantalla 2023-01-18 a las 15 47 53" src="https://user-images.githubusercontent.com/50477222/213202272-c398812c-b37f-441a-8d01-846241d4c11f.png">

PS: resize columns from handlers from Rows toolbar doesn't work correctly; is a known bug and will be disabled for beta 👍 

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test the commented above

**_ Pre-Code Testing _**

-   [ ] Test the commented above
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

2023-01-18 16:00 UTC, Olekrut approved these changes

2023-01-18 16:07 UTC, Fybex approved these changes
👏

2023-01-18 16:26 UTC, elzadj approved these changes

2023-01-19 11:27 UTC, Olekrut approved these changes

2023-01-20 09:54 UTC, Fybex requested changes

2023-01-23 07:18 UTC, Olekrut approved these changes

2023-01-23 09:32 UTC, Fybex approved these changes

2023-01-23 10:56 UTC, elzadj approved these changes

2023-01-23 10:56 UTC, merged