Text maxi migrator
maxi-blocks/maxi-blocks pull request #4242
Opened 2023-01-20 09:24 UTC by Naaaaiix

# Description

As we added the new Typography attribute `bottom-gap` and made Text Maxi behaviour change when pressing enter, we found that it would affect the already created patterns. @Olekrut came with the idea to set all the Text Maxi on patterns with a `bottom-gap` of 0 to don't break them, so here's a migrator for it. 
It's important to see that this PR is pointing to merge into v0.0.1-SC5, as the migrator affects to all blocks until the ones created on that version 👍 

Also, this PR fixes a couple of small issues:
1. Removes a silly CSS property that doesn't exist.
2. Adds compatibility with blocks created before versioning (`0.1`), that is breaking some patterns on the update 👍 

# How Has This Been Tested?

Get patterns from the Cloud or from devdemo and check they look the same (in terms of Text Maxi, it may have other differences)

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test the comment above ⬆️ 

**_ Pre-Code Testing _**

-   [ ] Test the comment above ⬆️ 
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] My changes generate no new warnings/errors
-   [x] I have added/updated tests that prove my fix is effective or that my feature works
-   [x] New and existing unit tests pass locally with my changes

2023-01-20 12:17 UTC, Olekrut approved these changes

2023-01-20 12:55 UTC, Fybex requested changes

2023-01-20 18:38 UTC, Fybex approved these changes
Approving it as`maxiVersionOrigin` isn't related to migrator 👍

2023-01-23 09:04 UTC, elzadj approved these changes

2023-01-23 09:26 UTC, merged