Text Maxi list mode fix on SC5
maxi-blocks/maxi-blocks pull request #4262
Opened 2023-01-25 12:20 UTC by Naaaaiix

# Description

Shared an error on SC5 update on [this comment](https://github.com/maxi-blocks/maxi-blocks/discussions/4254#discussioncomment-4757902). This PR aims to fix the issue.

# How Has This Been Tested?

On master, create a Text Maxi and set it on list mode with some random content. With just one line is enough to test; add `bottom-gap` setting to 0.  Then, duplicate than same Text Maxi block and check that the SC `bottom-gap` option is affecting the `ul` or `ol` HTML element and adding the `bottom-gap`. If you return that Text Maxi to normal mode (no list), the bottom-gap disappears and it's correct. This branch fixes it 👍 

# Test checklist

**_ Front/Back Testing _**

-   [ ] Do the steps commented above

**_ Pre-Code Testing _**

-   [ ] Do the steps commented above
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] My changes generate no new warnings/errors
-   [x] I have added/updated tests that prove my fix is effective or that my feature works
-   [x] New and existing unit tests pass locally with my changes

2023-01-25 15:01 UTC, darimshlk requested changes
https://jam.dev/c/5b98aed4-9efe-4cfe-bfb2-cd685d96b698
bottom gap is appearing if add second level for list

2023-01-25 15:40 UTC, Olekrut approved these changes

2023-01-25 16:27 UTC, myroslavve approved these changes

2023-01-26 09:11 UTC, elzadj approved these changes

2023-01-26 10:45 UTC, darimshlk approved these changes

2023-01-26 11:15 UTC, merged