Issue 4117 - Image transition, grayscale and boundry
maxi-blocks/maxi-blocks pull request #4282
Opened 2023-01-27 13:11 UTC by Marko64

- Removes unnecessary transition styles from the image which were rendered even if no effects were selected.
- Fixes grayscale effect
- Fixes boundary glitch

Fixes #3808
Fixes #4117

**_ Front/Back Testing _**

-   [ ] Test that grayscale effect works (backend and frontend)
-   [ ] Test that zoom-in effect works normally and that the "Extend outside boundary" option works
-   [ ] Ensure that the image doesn't have any inline styles if no effects are selected or if show preview isn't selected

**_ Pre-Code Testing _**

-   [ ] Test that grayscale effect works (backend and frontend)
-   [ ] Test that zoom-in effect works normally and that the "Extend outside boundary" option works
-   [ ] Ensure that the image doesn't have any inline styles if no effects are selected or if show preview isn't selected
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [x] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

2023-01-27 13:24 UTC, Olekrut requested changes
1) I guess, slide is not working correct
https://jam.dev/c/d3e0d0e7-81fa-4b9d-8c53-1e3a306f5daf
2) BG and border have different transitions? https://jam.dev/c/d0217f63-65a4-48f4-8112-bdd736de1822
3) input fields for margin/paddings ?
![image](https://user-images.githubusercontent.com/88893350/215098543-f92b6ebe-1b79-4e96-8755-4ef498ca8253.png)
4) why extend outside boundary is not inside hover tabs?
![image](https://user-images.githubusercontent.com/88893350/215099627-a09926bc-30dd-40ce-8a98-63b38ea172e7.png)

2023-01-31 09:12 UTC, Olekrut requested changes
Awesome)
https://jam.dev/c/fc36a3bb-19c0-46bd-b67c-a85d80727c14
for slide need % or to add dropdown list with units

2023-01-31 12:30 UTC, Olekrut approved these changes

2023-01-31 13:50 UTC, elzadj approved these changes

2023-01-31 13:50 UTC, merged