Issue 4198 - Transition in/out support
maxi-blocks/maxi-blocks pull request #4283
Opened 2023-01-27 13:38 UTC by Fybex

# Description

Fixes #4198 

<img width="288" alt="image" src="https://user-images.githubusercontent.com/46112160/215089005-1123690f-016d-4d0d-90ff-e633ad1b3ace.png">

# How Has This Been Tested?
Checked if it works with different combinations in `TransitionControl` and `IB`, created [code editor](https://github.com/maxi-blocks/maxi-blocks/files/10518858/in.out-transition.txt) with some basic tests.

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test the [code editor](https://github.com/maxi-blocks/maxi-blocks/files/10518858/in.out-transition.txt)
-   [ ] Test `TransitionControl` in different combinations
-   [ ] Test `IB` in different combinations
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points on responsive

**_ Pre-Code Testing _**

-   [x] Test the [code editor](https://github.com/maxi-blocks/maxi-blocks/files/10518858/in.out-transition.txt)
-   [x] Test `TransitionControl` in different combinations
-   [x] Test `IB` in different combinations
-   [x] Check that the settings work on frontend
-   [x] Check that backend works and saves the settings after the editor reload
-   [x] Same 1-4 points on responsive
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [X] My code follows the style guidelines of this project
-   [X] I have performed a self-review of my code
-   [X] I have commented my code, particularly in hard-to-understand areas
-   [X] My changes generate no new warnings/errors
-   [x] I have added/updated tests that prove my fix is effective or that my feature works
-   [X] New and existing unit tests pass locally with my changes

2023-01-27 16:16 UTC, Olekrut approved these changes

2023-01-27 16:52 UTC, myroslavve requested changes
Seems like IB on responsive has wrong transition styles

https://user-images.githubusercontent.com/53875005/215145877-99f897b7-8a45-4c36-a25e-d5dddcf9b77a.mp4

2023-01-30 15:07 UTC, myroslavve approved these changes

2023-01-31 09:15 UTC, elzadj approved these changes

2023-01-31 09:15 UTC, merged