Issue 3909 - reusable blocks with maxi blocks
maxi-blocks/maxi-blocks pull request #4304
Opened 2023-02-02 19:14 UTC by myroslavve

# Description
This PR fixes the size of reusable maxi-blocks on backend.

The point about reusable blocks in column isn't fixed, as the way to fix it would be to forbid the insertion of reusable blocks which have a container inside of them, but it is only possible to forbid all reusable blocks.

Fixes #3909 

# How Has This Been Tested?
Added reusable block on the page, changed size and position settings, checked that it looks the same as non-reusable block.
The issue affects only editor, so no need to check frontend.

# Test checklist

**_ Front/Back Testing _**

-   [ ] Add reusable block on the page, check that it looks right.
-   [ ] Change its size and position settings, check that it looks the same as non-reusable block.

**_ Pre-Code Testing _**

-   [ ] Add reusable block on the page, check that it looks right.
-   [ ] Change its size and position settings, check that it looks the same as non-reusable block.
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

2023-02-06 09:17 UTC, Olekrut requested changes
Width is fixed
have found only UI - bug
![image](https://user-images.githubusercontent.com/88893350/216929376-197e7951-a9d5-48bd-8c20-b3fac3179191.png)
it can be fixed here? or need new issue?

2023-02-06 14:53 UTC, Olekrut requested changes
1) first render after paste looks broken
![image](https://user-images.githubusercontent.com/88893350/217003960-0bcbeeb9-3282-49ce-bea0-1b79b69ed760.png)
2) is it expected? if we change or remove smth from reusable block, it is automatically saving to original reusable block?
https://jam.dev/c/db2695b7-bdbc-40df-a687-990ccb428270

2023-02-20 18:25 UTC, Olekrut requested changes
1) Maybe need to disallow adding reusable blocks with equal labels?
![image](https://user-images.githubusercontent.com/88893350/220177835-070eaf54-016c-49da-97ad-db0760f9bd8f.png)
2) is it ok? maybe need to disallow ability to add reusable block to new reusable block?
![image](https://user-images.githubusercontent.com/88893350/220178392-975de484-f310-44fb-8983-0e50dd106e78.png)

2023-02-21 10:42 UTC, Olekrut approved these changes

2023-02-22 07:42 UTC, Naaaaiix approved these changes

2023-02-22 07:42 UTC, merged