New Library UI (icons, SCs, patterns)
maxi-blocks/maxi-blocks pull request #4323
Opened 2023-02-08 08:08 UTC by Rustam198804

# Description

Have fixed libraries for svg icon, button icon, background shape and SC library

Fixes #3944 #4274 

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type

**_ Pre-Code Testing _**

-   [ ] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

2023-02-14 14:16 UTC, Olekrut requested changes
1) maybe need to hide clear button before we type smth
![image](https://user-images.githubusercontent.com/88893350/218762070-2862285b-67a0-4fe7-9855-7ebcb41cef49.png)
2) why border for active tab is disappearing on hover, looks weird
https://jam.dev/c/da7487f0-2cf9-424d-8b60-1f736042bddc

2023-02-15 10:35 UTC, Olekrut requested changes
Active border for categories,  when we are clicking to the same cat for disable, border should disappear
1) for parent cat - https://jam.dev/c/2b065fa6-b918-43b6-8dd6-a5fa01a28c29
2) child cat - https://jam.dev/c/5fad90a9-75a6-4389-abd1-af71ad072598

2023-02-15 11:33 UTC, Olekrut approved these changes

2023-02-15 13:11 UTC, Naaaaiix approved these changes

2023-02-15 13:12 UTC, Marko64 requested changes
Clicking outside modal doesn't close it for me. Let me know if you need a video. Tested Chrome and FF.

2023-02-15 13:15 UTC, elzadj approved these changes

2023-02-15 13:17 UTC, darimshlk approved these changes

2023-02-15 13:18 UTC, Marko64 approved these changes

2023-02-15 14:02 UTC, merged