Issue 4322 - Font weight on family change
maxi-blocks/maxi-blocks pull request #4326
Opened 2023-02-08 10:09 UTC by Marko64

On font family change, the font weight was changing to 100 when it doesn't exist. For example, if you choose Monserrat 800 and switch to Roboto, it was changing to 100 because Roboto doesn't have 800. Now it changes to 400 if it doesn't exist.

Fixes #4322 

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test both cases, when the changed font has and doesn't have the current font weight.

**_ Pre-Code Testing _**

-   [ ] Test both cases, when the changed font has and doesn't have the current font weight.
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [x] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

2023-02-08 17:23 UTC, Olekrut requested changes
1) it is not working if change font-family from SC
https://jam.dev/c/c1a6c870-5edb-4815-866f-cc80ddea79f3
2) question: are all font-families have font-weight:Regular? what if font-family has not?

2023-03-18 16:10 UTC, Olekrut requested changes
https://jam.dev/c/0108d36c-a89a-463c-9b4e-3ad5fe25b2d7
settings from sidebar are not working if we are using custom SC
and warning in console
![image](https://user-images.githubusercontent.com/88893350/226118358-d5a7156f-b622-4ec8-817d-b6071f831b27.png)

2023-03-22 14:43 UTC, Olekrut requested changes
Reset for font-family is not working on this brunch anymore ( for SC as well)
![image](https://user-images.githubusercontent.com/88893350/226938770-b83ec103-9a78-4342-902d-f1415e8d5627.png)

2023-03-24 19:17 UTC, Olekrut approved these changes

2023-03-27 08:34 UTC, Naaaaiix approved these changes

2023-03-27 08:34 UTC, merged