Issue 4338 - Disable blocks on small screens
maxi-blocks/maxi-blocks pull request #4345
Opened 2023-02-10 10:43 UTC by Naaaaiix

# Description

Adds a block layer that forbids the use of Maxi on small screen like M, S or XS. It looks like this:
<img width="706" alt="Captura de Pantalla 2023-02-10 a las 11 31 11" src="https://user-images.githubusercontent.com/50477222/218069564-77f08bcc-d6e7-4088-bb20-d9d55d6f9475.png">

not sure if someboday should fancy it a bit lol

PS: there's a known 'issue' when clicking the block that the toolbar appears for a milisecond. Not a big deal, if consider important, let's derive to other issue and leave this as MVP.

PS1: fixes a small glitch on MaxiBlock lifecycle on the 'memo' part that wasn't running after checking children changes 👍 

Fixes #4338

# How Has This Been Tested?

Add a pattern or random blocks, and use the console to make the size of the screen smaller. It won't show anything if you're in a desktop type, but if you change to touchable or select a mobile device, it will appear 👍 

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test the steps commented above

**_ Pre-Code Testing _**

-   [ ] Test the steps commented above
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

2023-02-10 15:05 UTC, Olekrut approved these changes
but 
is not M (1024px) size for some of small laptops?

2023-02-10 18:11 UTC, Olekrut requested changes
![image](https://user-images.githubusercontent.com/88893350/218165600-783e6724-1c38-46b2-acea-574ac94a612c.png)

2023-02-13 16:03 UTC, Olekrut approved these changes

2023-02-14 12:30 UTC, elzadj approved these changes

2023-02-14 12:31 UTC, merged