Issue 3487 - Transition transform support
maxi-blocks/maxi-blocks pull request #4390
Opened 2023-02-17 18:22 UTC by Fybex

# Description

Update:

- added transition transform support (transition attribute have new key - transform, where transform transition attributes will be contained)
- changed text-maxi lists custom CSS structure (@Olekrut, can you remember if we have somewhere custom css for text-maxi lists in our patterns? If yes, I will create a migrator 👍 )

Fixes #3487 

# How Has This Been Tested?
Checked if transform transitions work in different cases, wrote unit tests to ensure

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test the component in normal state in sidebar
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points on responsive

**_ Pre-Code Testing _**

-   [ ] Test the component in normal state in sidebar
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points on responsive
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [X] My code follows the style guidelines of this project
-   [X] I have performed a self-review of my code
-   [X] I have commented my code, particularly in hard-to-understand areas
-   [X] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [X] New and existing unit tests pass locally with my changes

2023-02-21 11:22 UTC, Olekrut requested changes
could be fixed dragging?
 scale - https://jam.dev/c/ba2ea985-0151-4d26-88b9-d5e7c462ecd4
 translate - https://jam.dev/c/33eee969-9317-4a19-867c-06778ed8c1f7

2023-02-21 16:40 UTC, Olekrut requested changes
transition for transform-origin is not working https://jam.dev/c/0f4099dc-13eb-4815-aa7a-92ac62783907

2023-02-22 11:37 UTC, Olekrut approved these changes

2023-02-23 08:25 UTC, Naaaaiix approved these changes

2023-02-23 08:25 UTC, merged