Issue 4392 - Scroll effects default values
maxi-blocks/maxi-blocks pull request #4401
Opened 2023-02-20 10:47 UTC by Marko64

Fixed default values for scroll effects. But give it a close check to ensure they are all correct now.

Fixes #4392 

# How Has This Been Tested?

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test all individual effects (vertical, horizontal, rotate, scale, fade, blur) with all possible preset directions.
-   [ ] Test all scroll combinations.

**_ Pre-Code Testing _**

-   [ ] Test all individual effects (vertical, horizontal, rotate, scale, fade, blur) with all possible preset directions.
-   [ ] Test all scroll combinations.
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [x] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

2023-02-20 12:11 UTC, Olekrut requested changes
1) all rotate effects have the same values 90deg - https://jam.dev/c/f98a818b-76b6-49d5-9ca1-e1a081f48b95
2) Fade
Fade Out is ok
for Fade in end should be 100
suggestion:
in less ( 60-80-100)
in some ( 35-70-100)
in more left as is ( 0-50-100) 
3) Blur Scroll 
3.1)  all blur effects have the same values
3.2) wrong labels for presets 
![image](https://user-images.githubusercontent.com/88893350/220097927-67b64d56-f78a-49b2-ab0d-85bee0aec71d.png)
should be as for others
suggestion:
out less ( 0-2-4) px
out some ( 0-3.5-7) px
out more ( 0-5-10) px
in less (4-2-0) px
in some (7-3.5-0) px
in more (10-5-0) px
4) Scroll combinations 
4.1) 
![image](https://user-images.githubusercontent.com/88893350/220103018-d71ec1d4-d341-4d0e-8daa-9657a8857cdf.png)
remake labels - labels should consider scroll effects ( if vertical scroll + blur as in this case, should be - "in vertical blur", " out horizontal blur"....
4.2) check that both scroll effects for "IN" at the end point have start values, for "OUT" at the start point have start values

2023-02-20 18:04 UTC, Olekrut requested changes
Simple presets are OK
https://jam.dev/c/7688c7a4-17b9-4ea6-a98b-ac1535ac07bf
check all values for combinations, they are wrong) if you set values not from simple presets, > direction presets should not be chosen 
if you combine simple presets > values should be the same

2023-02-24 15:44 UTC, Olekrut approved these changes

2023-02-27 09:34 UTC, Naaaaiix approved these changes

2023-02-27 09:35 UTC, merged