Issue 4406 - Modal items titles
maxi-blocks/maxi-blocks pull request #4407
Opened 2023-02-21 12:44 UTC by Marko64

Changed items title from `post_number` to `post_title`.
Added special class for long titles to decrease the font size for them (needed for responsive).

Fixes #4406 

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test that we display the full title the all patterns now.
-   [ ] Test that long pattern titles look good on all screen sizes.
- 
**_ Pre-Code Testing _**

-   [ ] Test that we display the full title the all patterns now.
-   [ ] Test that long pattern titles look good on all screen sizes.
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [x] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

2023-02-21 16:28 UTC, Olekrut requested changes
https://jam.dev/c/e3e4a79d-4f37-475b-ad86-96ace7f81941
preview is not working when we are clicking to image, have noticed only for playground patterns'

2023-02-22 11:53 UTC, Olekrut approved these changes

2023-02-22 13:36 UTC, elzadj requested changes
1367px

![screenshot-wordpress local-2023 02 22-15_35_12](https://user-images.githubusercontent.com/2401618/220635373-87b30d9c-95ff-4e00-a090-aa7e3fa302f1.jpg)

2023-02-23 15:11 UTC, elzadj approved these changes

2023-02-23 15:11 UTC, merged