Issue 4411 - Copy/paste UI
maxi-blocks/maxi-blocks pull request #4414
Opened 2023-02-22 10:16 UTC by Marko64

Fixed copy/paste (special paste) UI. 

Fixes #4411 

# How Has This Been Tested?

**_ Front/Back Testing _**

-   [ ] Test that the hover issue has been fixed.
-   [ ] Test special paste style in general.
- 
**_ Pre-Code Testing _**

-   [ ] Test that the hover issue has been fixed.
-   [ ] Test special paste style in general.
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [x] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

2023-02-22 11:46 UTC, Olekrut requested changes
![image](https://user-images.githubusercontent.com/88893350/220610881-afe7b83c-45f5-4117-91be-b1beadfea913.png)
looks weird as for me. Maybe to add grey space over tabs as well?

is not better?
![image](https://user-images.githubusercontent.com/88893350/220611491-ca2c9598-d083-42f2-9e1d-acad7a5b2a41.png)

2023-02-22 15:26 UTC, Olekrut requested changes
![image](https://user-images.githubusercontent.com/88893350/220669488-d347497a-1b05-4bc9-90a6-c4681ea7c5e9.png)
maybe need to add min-width or smth

2023-02-23 11:04 UTC, Olekrut approved these changes

2023-02-24 13:43 UTC, elzadj approved these changes

2023-02-24 13:44 UTC, merged