Issue 4419 - Show/hide fixes
maxi-blocks/maxi-blocks pull request #4428
Opened 2023-02-24 11:32 UTC by Marko64

Fixed hiding for some blocks. 

Fixes #4419 

**_ Front/Back Testing _**

-   [ ] Test all blocks and make sure show/hide works correctly. On backend, they need to be visible and blurred. Check that blocks do not change position or style after hiding. On frontend, they need to be hidden.

**_ Pre-Code Testing _**

-   [ ] Test all blocks and make sure show/hide works correctly. On backend, they need to be visible and blurred. Check that blocks do not change position or style after hiding. On frontend, they need to be hidden.
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [x] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

2023-02-24 13:57 UTC, Olekrut requested changes
https://jam.dev/c/ec372151-1e8e-4a28-9810-3b88c68ed7f0
left to fix Map-block

2023-02-25 14:53 UTC, Olekrut approved these changes

2023-02-27 12:09 UTC, Naaaaiix approved these changes

2023-02-27 13:18 UTC, elzadj approved these changes

2023-02-27 13:18 UTC, merged