Issue 4447 - Only the last font weight from the page is loaded on frontend
maxi-blocks/maxi-blocks pull request #4452
Opened 2023-02-28 15:31 UTC by Naaaaiix

# Description

Seems the frontend font loader was mixing terms: was loading fonts from SC, but the font-weight and font-style were coming from the post, not from SC. Modified in a way that checks all possible SC weights and styles to load them. 

Fixes #4447 

# How Has This Been Tested?

Made a shallow test with the code editor of the issue. Please, test changing SC with different font-families for Headings, with different font-weights and font-styles. Also test saving the fonts on local from maxi-dashboard. All should work correctly, but before sharing there's an issue, check it in master 👍 

# Test checklist

**_ Front/Back Testing _**

-   [ ] Check the commented above

**_ Pre-Code Testing _**

-   [ ] Check the commented above
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

2023-03-01 09:29 UTC, Olekrut requested changes
![image](https://user-images.githubusercontent.com/88893350/222098930-ff8f1c12-a82a-47ee-b2b0-734638c71b9a.png)

looks different
backend
![image](https://user-images.githubusercontent.com/88893350/222101419-b04354b4-e433-498e-86be-ed6d3eeba089.png)
frontend
![image](https://user-images.githubusercontent.com/88893350/222101498-939182de-f3cf-4962-98a3-827f7ccaab50.png)

2023-03-01 10:59 UTC, Olekrut requested changes
![image](https://user-images.githubusercontent.com/88893350/222120272-386edc7b-7d47-4af4-b61a-a16875cefd4e.png)
40500 is not a mistake?

incognito
![image](https://user-images.githubusercontent.com/88893350/222120580-db252b45-3438-467a-b475-79041bbb2e1b.png)

2023-03-01 13:05 UTC, Olekrut requested changes
Previous request is fixed) it is not a problem, but..
What is happening with title text, when i have changed font-weight for text under title?
Take a look on 10 sec
https://jam.dev/c/9d9bdd65-1d8e-4957-adc3-10d42f82c374

2023-03-01 13:51 UTC, Olekrut approved these changes

2023-03-02 09:48 UTC, elzadj approved these changes

2023-03-02 09:48 UTC, merged