Issues 4487 & 4489 - Suspense Lazy load issues
maxi-blocks/maxi-blocks pull request #4491
Opened 2023-03-06 11:39 UTC by Naaaaiix

# Update
Tests were showing something wrong: had to refactor the lifecycle of the HOC. Resuming: 

⚠️  Test it again and deep, please! ⚠️ 

# Description

This PR aims to fix #4487 and #4489. Suspense logics had some issues and weren't loading the blocks correctly. This PR should deal with it 👍 

# How Has This Been Tested?

Check the issues and reproduce what has been explained there. The problems shouldn't exist anymore

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test comments above

**_ Pre-Code Testing _**

-   [ ] Test comments above
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

2023-03-06 12:23 UTC, Olekrut approved these changes

2023-03-06 12:41 UTC, darimshlk approved these changes

2023-03-07 17:17 UTC, Olekrut approved these changes

2023-03-08 15:02 UTC, Marko64 requested changes
Columns layout breaks for me:
https://user-images.githubusercontent.com/19425503/223748332-c2a85515-de10-4a6f-a580-2b3429efbbc4.mp4

2023-03-08 17:15 UTC, Fybex requested changes

2023-03-09 10:21 UTC, Olekrut requested changes
https://jam.dev/c/c406e746-ad77-48f9-b6b1-8e7df7ef9bf4
bug with column is not fixed for me

2023-03-09 10:56 UTC, Olekrut approved these changes

2023-03-09 11:10 UTC, darimshlk approved these changes

2023-03-09 11:29 UTC, elzadj approved these changes

2023-03-09 11:42 UTC, merged