Issue 4486 - content is pasted on 'Paste styles - all' part 2
maxi-blocks/maxi-blocks pull request #4498
Opened 2023-03-06 18:09 UTC by Fybex

# Description

Fixes #4486 

Update:
- on 'Paste styles - all' - search-maxi, map-maxi, button-maxi, accordion-maxi, slider-maxi icons won't be copied
- `accordion-maxi`: add ability to copy active icon

# How Has This Been Tested?
Tested if higher described things works as expected

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test if on 'Paste styles - all' - search-maxi, map-maxi, button-maxi, accordion-maxi, slider-maxi icons won't be copied
-   [ ] Test if `accordion-maxi` have ability to copy active icon on 'special select' and 'paste all'

**_ Pre-Code Testing _**

-   [ ] Test if on 'Paste styles - all' - search-maxi, map-maxi, button-maxi, accordion-maxi, slider-maxi icons won't be copied
-   [ ] Test if `accordion-maxi` have ability to copy active icon on 'special select' and 'paste all'
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [X] My code follows the style guidelines of this project
-   [X] I have performed a self-review of my code
-   [X] My changes generate no new warnings/errors

2023-03-06 18:42 UTC, Olekrut requested changes
1) NC - Number
2) MAP - markers
3) Video - need to add to special paste pop-up image

2023-03-06 19:51 UTC, Olekrut approved these changes

2023-03-07 09:49 UTC, darimshlk approved these changes

2023-03-07 11:01 UTC, elzadj approved these changes

2023-03-07 11:01 UTC, merged