Issue 4482 - List source reset button
maxi-blocks/maxi-blocks pull request #4500
Opened 2023-03-07 08:58 UTC by Marko64

Hides the reset button for the list custom icon source.

Fixes #4482 

# How Has This Been Tested?

# Test checklist

**_ Front/Back Testing _**

-   [ ] Add a text block and change to the unordered list. From the list of options choose 'custom' for the style option. Make sure the custom select doesn't have a reset button.

**_ Pre-Code Testing _**

-   [ ] Add a text block and change to the unordered list. From the list of options choose 'custom' for the style option. Make sure the custom select doesn't have a reset button.

-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [x] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

2023-03-07 09:41 UTC, darimshlk approved these changes

2023-03-07 10:36 UTC, Olekrut approved these changes
![image](https://user-images.githubusercontent.com/88893350/223397555-825de182-4c25-421d-a7d4-fb7cd18bddc7.png)
if we dont fill input field in custom sign or dont pick icon > we see ordered list, not sure that it is bad

2023-03-09 08:02 UTC, Naaaaiix requested changes

2023-03-20 08:57 UTC, Naaaaiix reviewed
Remove this space: make it easy, no exceptions. 

<img width="830" alt="Captura de Pantalla 2023-03-20 a las 9 56 58" src="https://user-images.githubusercontent.com/50477222/226291622-4d3eb96e-36b2-4b26-bc38-14fcfb934b38.png">

2023-03-21 08:18 UTC, merged