Fix Maxi Blocks for WP 6.2 (beta 5) and 6.1.1
maxi-blocks/maxi-blocks pull request #4508
Opened 2023-03-08 11:58 UTC by elzadj

# Description

WP 6.2 uses React 18, so we have a lot of issues.
Please also test for backward compatibility on 6.1.1

Fixes #4475 

# How Has This Been Tested?

**Local**

Install https://wordpress.org/plugins/wordpress-beta-tester/ to switch between versions (Use Bleeding edge - Beta/RC only for 6.2 beta5): 

![screenshot-wordpress local-2023 03 08-13_57_18](https://user-images.githubusercontent.com/2401618/223707377-3314064a-0895-476d-bbcc-4a424bd49e76.jpg)

**On a site**

You can test on 6.2 on https://randomtesting.maxiblocks.com/wp-admin 

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test everything. Not joking :smiling_face_with_tear:  (But please also compare any bugs you find with the master on 6.1, this branch is for fixing bugs for 6.2 / 6.1.1 only)

**_ Pre-Code Testing _**

-   [ ] Test everything. Not joking :smiling_face_with_tear:  (But please also compare any bugs you find with the master on 6.1, this branch is for fixing bugs for 6.2 / 6.1.1 only)
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [x] New and existing unit tests pass locally with my changes

2023-03-08 16:23 UTC, Olekrut requested changes
WP 6.2
1) error, try to use custom clip-path
![image](https://user-images.githubusercontent.com/88893350/223770144-b36ae2de-ae3e-4744-a3c1-ff92a647f03e.png)
2) custom caption under block
![image](https://user-images.githubusercontent.com/88893350/223770972-8ca07f1b-dfe0-4694-8919-3ca03d17f572.png)

2023-03-10 12:47 UTC, Olekrut approved these changes

2023-03-10 14:33 UTC, darimshlk approved these changes

2023-03-13 08:28 UTC, Naaaaiix requested changes
Finding many elements with linter advices, like the useEffect returns I've suggested modifying. Don't they appear as errors to you @elzadj? 🤔 maybe the linter is not working correctly, or we are using different configs? 

<img width="431" alt="Captura de Pantalla 2023-03-13 a las 9 26 56" src="https://user-images.githubusercontent.com/50477222/224646669-7a015da3-86fa-4959-84b7-c339b445bb72.png">

<img width="580" alt="Captura de Pantalla 2023-03-13 a las 9 27 30" src="https://user-images.githubusercontent.com/50477222/224646869-6fcba9c8-f1c7-4460-8b56-1f9da93545a0.png">

2023-03-14 13:53 UTC, Naaaaiix approved these changes
WP 6.2... here we gooooo! 🚀

2023-03-14 14:33 UTC, merged