Issue 4507 - FSE. IB work fix on pattern inserting/block duplication/copy-paste
maxi-blocks/maxi-blocks pull request #4530
Opened 2023-03-10 17:12 UTC by Fybex

# Description

Fixes #4507 

# How Has This Been Tested?
Added patterns, checked if after adding a few similar patterns, IB have expected targets, triggers (#4320, but on FSE)

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test adding pattern in FSE
-   [ ] Test pattern IB in FSE
-   [ ] Test pattern IB after duplicating block
-   [ ] Check that the settings work on frontend

**_ Pre-Code Testing _**

-   [ ] Test adding pattern in FSE
-   [ ] Test pattern IB in FSE
-   [ ] Test pattern IB after duplicating block
-   [ ] Check that the settings work on frontend
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [X] My code follows the style guidelines of this project
-   [X] I have performed a self-review of my code
-   [X] I have commented my code, particularly in hard-to-understand areas
-   [X] My changes generate no new warnings/errors

2023-03-13 08:42 UTC, Olekrut requested changes
https://jam.dev/c/5dc316b5-a9a9-40ec-8290-470f3ac671ac - backend
backend after refresh editor, but can't save
![image](https://user-images.githubusercontent.com/88893350/224650223-b3c6bfe9-21de-41d6-b412-1500dbd37953.png)


Frontend - 
![image](https://user-images.githubusercontent.com/88893350/224650132-004456f0-7a11-4ca1-9378-55ae1e132b4c.png)

2023-03-17 18:40 UTC, Olekrut approved these changes

2023-03-24 11:08 UTC, darimshlk approved these changes

2023-03-27 07:08 UTC, Naaaaiix approved these changes

2023-03-27 10:00 UTC, elzadj approved these changes

2023-03-27 10:00 UTC, merged