Add missing alt tag for parallax images
maxi-blocks/maxi-blocks pull request #4546
Opened 2023-03-14 16:18 UTC by elzadj

# Description

Adds a default alt tag to the BG Parallax images

Fixes a part of https://github.com/maxi-blocks/maxi-blocks/issues/4510#issuecomment-1467638836

# How Has This Been Tested?

Add bg parallaxes, make sure the image has an alt tag (the image's name by default). Test the Alt component in general.

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points on responsive

**_ Pre-Code Testing _**

-   [ ] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points on responsive
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [x] New and existing unit tests pass locally with my changes

2023-03-15 14:33 UTC, Olekrut approved these changes

2023-03-15 14:34 UTC, Olekrut requested changes
![image](https://user-images.githubusercontent.com/88893350/225342408-8e17dd52-bb20-4933-87ab-82e85d11a08d.png)
warning

2023-03-16 08:47 UTC, Olekrut approved these changes

2023-03-16 09:16 UTC, Naaaaiix approved these changes

2023-03-16 09:28 UTC, Naaaaiix approved these changes

2023-03-16 10:26 UTC, merged