Issue 4513 - DC link
maxi-blocks/maxi-blocks pull request #4568
Opened 2023-03-17 11:08 UTC by Marko64

Added a class to the text block which renders only if the text contains DC.
Added this class to styles.js to render link styles for it.

Fixes #4513 

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test DC link settings.
-   [ ] Test ordinary text block settings.
-   [ ] Test that ordinary text list works in general.
-   [ ] Check backend and frontend.

**_ Pre-Code Testing _**

-   [ ] Test DC link settings.
-   [ ] Test ordinary text block settings.
-   [ ] Test that ordinary text list works in general.
-   [ ] Check backend and frontend.
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [x] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

2023-03-17 15:47 UTC, Olekrut approved these changes

2023-03-17 23:19 UTC, darimshlk approved these changes

2023-03-21 08:14 UTC, Naaaaiix reviewed
Tests 👍

2023-03-22 08:12 UTC, Naaaaiix reviewed
Implemented the `classnames` dependency to deal with classes.

Some comments:
1. The update done `e2e-tests/blocks/text-maxi/__snapshots__/index.spec.js.snap` test snapshot is incorrect. It's important to check before updating snapshots: in this case it has been updated with an error, and it was showing an error of the code. 
2. Tests for list on Text Maxi are duplicating it's size. Check why is happening before updating it, please

2023-03-23 09:35 UTC, elzadj requested changes
need to check the tests, like @Naaaaiix noted

2023-06-15 12:37 UTC, closed without merging