Issue 4505 - Range tooltip position for long numbers
maxi-blocks/maxi-blocks pull request #4594
Opened 2023-03-21 12:03 UTC by Marko64

Fixes the tooltip position for `RangeControl` for big numbers.

Fixes #4505 

# How Has This Been Tested?

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test start and end numbers for NC. Test with different numbers (small, big, beginning and end of the slider)
-   [ ] Test the range slider for any other block and settings to make sure it works as before.

**_ Pre-Code Testing _**

-   [ ] Test start and end numbers for NC. Test with different numbers (small, big, beginning and end of the slider)
-   [ ] Test the range slider for any other block and settings to make sure it works as before.
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [x] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

2023-03-21 20:10 UTC, darimshlk approved these changes

2023-03-22 14:05 UTC, Olekrut requested changes
![image](https://user-images.githubusercontent.com/88893350/226929148-e11c947a-cdb7-4272-b110-553209fed017.png)
cool, and maybe need to make input field bigger?

2023-03-22 17:56 UTC, Olekrut approved these changes

2023-03-23 12:19 UTC, elzadj approved these changes

2023-03-23 12:19 UTC, merged