Issue 4561 - load default font weight for sc fonts
maxi-blocks/maxi-blocks pull request #4597
Opened 2023-03-21 17:07 UTC by myroslavve

# Description
Since all style cards have 500 weight for h1 by default, some fonts that are set there by default as well might not have that weight, so for all SC fonts default weight is now loaded as well as specified one.

Fixes #4561 

# How Has This Been Tested?
Checked that the issue has been fixed.

# Test checklist

**_ Front/Back Testing _**

-   [ ] Check frontend with bubble gum SC and h1 text (or other title size).

**_ Pre-Code Testing _**

-   [ ] Check frontend with bubble gum SC and h1 text (or other title size).
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

2023-03-22 16:03 UTC, Olekrut requested changes
![image](https://user-images.githubusercontent.com/88893350/226965805-c8f47f39-141a-408f-b878-64d81d50b42a.png)
It is roboto for paragraph on backend as well

2023-03-22 20:05 UTC, darimshlk approved these changes

2023-03-23 06:50 UTC, Olekrut approved these changes

2023-03-23 12:53 UTC, elzadj approved these changes
Getting 
GET https://fonts.googleapis.com/css2?family=Bubblegum+Sans%3Awght%40500&ver=6.1.1 net::ERR_ABORTED 400
on frontend

but that's for another issue

2023-03-23 12:55 UTC, merged