Issue 4602 - Video start end numbers min max
maxi-blocks/maxi-blocks pull request #4607
Opened 2023-03-22 16:00 UTC by Marko64

Changed min and max values for the start and end video time. Now the start number can't be higher than the end number.
Fixed a typo in NC.

Fixes #4602 

# Test checklist

**_ Front/Back Testing _**

-   [ ] Add a NC and make sure that the start time can't be higher than the end video time.
- 
**_ Pre-Code Testing _**

-   [ ] Add a NC and make sure that the start time can't be higher than the end video time.
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [x] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

2023-03-22 19:50 UTC, darimshlk approved these changes

2023-03-23 06:57 UTC, Olekrut requested changes
1) The same need to do for BG Video
![image](https://user-images.githubusercontent.com/88893350/227126478-d235c068-2f49-4a93-b0c7-ce842240208b.png)
2) is possible to get Max End time from the duration of loaded video?

2023-03-23 17:08 UTC, Olekrut approved these changes

2023-03-28 13:23 UTC, elzadj requested changes

2023-03-29 11:41 UTC, elzadj requested changes

2024-02-29 22:23 UTC, closed without merging