Issue 4369 - FSE. 'home' slug support
maxi-blocks/maxi-blocks pull request #4608
Opened 2023-03-22 16:41 UTC by Fybex

# Description

Fixes #4369 

# How Has This Been Tested?
Tried to use home template for home page. Checked if maxi styles work and custom data work on frontend.
Created front-page and checked if even without editing and saving front-page template, styles and custom data work. (front-page on creation copies home template blocks)

P.S. Don't forget that IB from patterns won't work until #4530 merge.

# Test checklist

**_ Front/Back Testing _**

-  [ ] Verify that maxi styles work on the frontend of home page(home template)
-  [ ] Confirm custom data works on the frontend of home page(home template)
-  [ ] Check that styles and custom data work without editing and saving the front-page template after its creation

**_ Pre-Code Testing _**

-   [ ] Verify that maxi styles work on the frontend of home page(home template)
-   [ ] Confirm custom data works on the frontend of home page(home template)
-   [ ] Check that styles and custom data work without editing and saving the front-page template after its creation
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [X] My code follows the style guidelines of this project
-   [X] I have performed a self-review of my code
-   [X] I have commented my code, particularly in hard-to-understand areas

2023-03-23 07:59 UTC, Naaaaiix reviewed
Not sure if this implementation overcomplicates the situations. Probably there are reasons to do it this way, but I don't understand why we are saving styles and connection to `MaxiBlocks_API` class from the same PHP side and modify the POST method to accept json and not json objects. Is there any way to normalize it and do it from JS the same way we save other `template_parts`? I think we are creating exceptions that might have a negative impact in future and complicate the code and the workflows of the data 🤔

2023-03-29 06:57 UTC, Naaaaiix approved these changes

2023-03-29 14:53 UTC, Olekrut requested changes
1) IB is not working and don't display in editor
![image](https://user-images.githubusercontent.com/88893350/228576557-267d0d5c-cb83-4d5e-81d9-2673f11909e7.png)
2) 2022 theme - styles are not working for header
![image](https://user-images.githubusercontent.com/88893350/228578098-8d68156b-768a-43e9-bf0d-5955f900f6b0.png)

2023-03-29 17:56 UTC, Olekrut approved these changes

2023-03-31 10:00 UTC, merged