Issue 4612 - IB relation label substring
maxi-blocks/maxi-blocks pull request #4613
Opened 2023-03-23 15:45 UTC by Marko64

Limited the label text width.

Fixes #4612 

**_ Front/Back Testing _**

-   [ ] Go to IB and type in a long relation name. Make sure that the title text is cut off and doesn't exceed the parent's container.

**_ Pre-Code Testing _**

-   [ ] Go to IB and type in a long relation name. Make sure that the title text is cut off and doesn't exceed the parent's container.
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [x] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

2023-03-23 17:11 UTC, Olekrut requested changes
is not fixed for me(
![image](https://user-images.githubusercontent.com/88893350/227282791-1acaee8b-5533-43ef-90a6-b9faf84d7680.png)

Weird, is it depending on key layout?
https://jam.dev/c/29cbbeac-a8fd-4895-8d15-2932f236ca7b
for EN it is not working, for UA it is working good

2023-03-23 17:50 UTC, darimshlk requested changes
![image](https://user-images.githubusercontent.com/116658168/227295251-77f1f963-f977-4297-9508-72cf597c49d3.png)
![image](https://user-images.githubusercontent.com/116658168/227296458-9d47587f-02e7-481d-a3af-a0bba5338ced.png) 
![image](https://user-images.githubusercontent.com/116658168/227296737-e8a3352d-88b9-4f93-9e8e-aeaa1309d67f.png)
some letters is ok,but some going out of border (esp. caps one,check G,D,H for example)
and different letters have different space to the border

2023-03-24 17:33 UTC, Olekrut approved these changes

2023-03-27 08:02 UTC, Naaaaiix reviewed
Use `text-overflow`:
https://user-images.githubusercontent.com/50477222/227878805-523844ba-e5fe-4b92-883a-30f2d2361b79.mp4

2023-03-27 12:00 UTC, darimshlk approved these changes

2023-03-29 06:58 UTC, Naaaaiix approved these changes

2023-03-29 10:58 UTC, merged