Issue 4467 - Toolbar settings cut off fix
maxi-blocks/maxi-blocks pull request #4615
Opened 2023-03-23 17:42 UTC by Fybex

# Description

Fixes #4467 

Before(background colour settings aren't visible at all):
![image](https://user-images.githubusercontent.com/46112160/227292721-b078ffcb-8aff-4644-8ec0-8f59caa54722.png)

After:
![image](https://user-images.githubusercontent.com/46112160/227292530-15b17736-e1b4-4715-8a3c-dc1e6ce91fe4.png)

# How Has This Been Tested?
Checked if toolbar settings are visible when block is first on the post or FSE editor.

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test if toolbar settings are visible when block is first on the post or FSE editor.

**_ Pre-Code Testing _**

-   [ ] Test if toolbar settings are visible when block is first on the post or FSE editor.
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [X] My code follows the style guidelines of this project
-   [X] I have performed a self-review of my code
-   [X] My changes generate no new warnings/errors

2023-03-23 18:29 UTC, Olekrut requested changes
1)![image](https://user-images.githubusercontent.com/88893350/227312763-d87c33f5-15c0-4de9-b38c-8585059d9bc5.png)
is not it toolbar?
2) text block edit
![image](https://user-images.githubusercontent.com/88893350/227314895-5247bb96-677a-4eac-b824-1da963fb5e07.png)

2023-03-24 20:07 UTC, Olekrut requested changes
1)
 ![image](https://user-images.githubusercontent.com/88893350/227628444-133537c9-bee4-45ef-8210-468ed163e9dd.png)
2) 
![image](https://user-images.githubusercontent.com/88893350/227629091-fe53fdb4-5303-4ef1-9790-96dab29c14f0.png)

2023-03-29 06:45 UTC, Olekrut approved these changes

2023-03-29 07:01 UTC, Olekrut requested changes
theme 2022
fse
![image](https://user-images.githubusercontent.com/88893350/228451841-199c2c62-f4fc-46f5-8b2b-cc991c4377ac.png)
simple page
![image](https://user-images.githubusercontent.com/88893350/228452171-d4358f65-7319-4e68-a9e6-413033b6ddd4.png)

2023-03-29 13:59 UTC, Olekrut approved these changes

2023-03-29 18:17 UTC, darimshlk approved these changes

2023-03-30 11:03 UTC, Naaaaiix approved these changes

2023-03-30 11:03 UTC, merged