Issue 4662 – DC. Get by date and get alphabetical relations
maxi-blocks/maxi-blocks pull request #4663
Opened 2023-03-30 18:00 UTC by Fybex

# Description

Fixes #4662 

@Naaaaiix at the keyboard:
This implementation adds 2 new types of relations on DC that are necessary for the future implementation of Context Loop (CL). These 2 new types are:
- Alphabetical
- By date

Each one has an `order` setting to decide if A->Z/Z->A and New->Old/Old->New respectively. And then it appears a new input called `Accumulator`; some points about it:
1. The label is temporary, let's focus on its functionality
2. What it does is to jump its value in the list of the requested elements; I think a video helps understanding:

https://user-images.githubusercontent.com/50477222/229063932-88c168d4-cdc5-402b-98f4-1b08b8abe774.mp4

(Seems the change from `new/old` to `old/new` didn't work on the video, but the video is to share what's accumulator)

So, if we want posts organizes by date and we've got a list of:
1. Post 1
2. Post 2
3. Post 3
4. Post 4

we'll receive `Post 1` if accumulator is 0, and `Post 2` if accumulator is 1, and so on...

# How Has This Been Tested?
Checked if new relations works as expected.

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test get by date DC relation
-   [ ] Test get alphabetical DC relation 

**_ Pre-Code Testing _**

-   [ ] Test get by date DC relation
-   [ ] Test get alphabetical DC relation 
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [X] My code follows the style guidelines of this project
-   [X] I have performed a self-review of my code
-   [X] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [X] New and existing unit tests pass locally with my changes

2023-03-31 08:00 UTC, Naaaaiix approved these changes
Awesome, that's a great one! 👏 

Some thoughts that I share loud:
1. Probably accumulator, apart of needing a better and friendly label for users, won't need the default when we'll implement CL; but let's see it when we arrive that point 👍 
2. An improvement we can implement later can be to check the amount of existing entities and limit the accumulator to that amount 🤔 

Well done @Fybex 🚀

2023-03-31 08:14 UTC, Naaaaiix requested changes
Found a bug while recording the video added on description; might need a look 👍

2023-03-31 19:33 UTC, Olekrut requested changes
works good) but maybe we can make limit for accumulator ( max value = amount of posts )
![image](https://user-images.githubusercontent.com/88893350/229212698-fde8f655-8cb3-4628-a762-df79b3d9cf2f.png)

2023-04-03 06:59 UTC, Olekrut approved these changes

2023-04-03 08:46 UTC, Naaaaiix approved these changes

2023-04-03 08:46 UTC, merged