Image caption toolbar
maxi-blocks/maxi-blocks pull request #4740
Opened 2023-04-17 10:57 UTC by Rustam198804

Removed bold and italic from image caption toolbar

Fixes #4628 

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type

**_ Pre-Code Testing _**

-   [ ] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

2023-04-17 12:42 UTC, Olekrut approved these changes

2023-05-01 09:59 UTC, elzadj requested changes
Works great, but I think we need to switch places for the Edit and the colour - the colour first, like it's for the typography 

Compare
Image
![screenshot-wordpress local-2023 05 01-12_57_33](https://user-images.githubusercontent.com/2401618/235437962-c01efb8a-637e-497e-ae23-c0e3e66605db.jpg)

Typography:

![screenshot-wordpress local-2023 05 01-12_58_58](https://user-images.githubusercontent.com/2401618/235438054-c9fe8fce-dd06-45b5-a13f-ff6dc31d6b60.jpg)

2023-05-02 08:37 UTC, elzadj requested changes
The alignment in the toolbar works, but doesn't change its state (the sidebar one looks ok)

[screencast-wordpress.local-2023.05.02-11_35_27.webm](https://user-images.githubusercontent.com/2401618/235619116-fef43718-9e09-4346-9a6d-73f7d2364e54.webm)

2023-05-02 13:47 UTC, elzadj approved these changes

2023-05-02 13:47 UTC, merged