Issue 4695 - XXL and general attributes conflict on saving from XXL baseBreakpoint
maxi-blocks/maxi-blocks pull request #4741
Opened 2023-04-17 11:16 UTC by Naaaaiix

# Description

This PR is an alternative to #4709 branch and is based on [this comment](https://github.com/maxi-blocks/maxi-blocks/pull/4709#pullrequestreview-1385918907). The difference in terms of experience is the same, but this branch saves the attributes differently from the commented PR; doesn't mean is better, is an alternative I hope it works good and might be a point to discuss with @TeksPeks and @Fybex about 👍 

Fixes #4695 

# How Has This Been Tested?

Test what has been commented on #4709 and #4695 👍 

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type

**_ Pre-Code Testing _**

-   [ ] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

2023-04-17 14:54 UTC, Olekrut requested changes
https://jam.dev/c/03cdd34d-3d82-41ca-9cdb-c4f08b8832f5

[Button padding inheriting .txt](https://github.com/maxi-blocks/maxi-blocks/files/11251515/Button.padding.inheriting.txt)

1) If create button when base is XXL:
values and units are inheriting for XL and if after that change base BP to XL and change values and units it will be inherited to XXL

2)  If create button when base is XL:
and change values and units for XL
to XXL will be inherited only units

2023-04-17 17:41 UTC, Fybex approved these changes
Love this idea more, bc it's not creating exception, when we have general and same base breakpoint attribute for XXL.

2023-04-18 15:29 UTC, Olekrut approved these changes

2023-04-18 15:48 UTC, myroslavve reviewed
Overall, this PR solves the problem as well as the other one, doesn't create more attributes, and I don't see any problems it can cause unless we add default attributes on xxl, so let's merge this one 👍, I'll close the other one.

2023-04-18 16:45 UTC, darimshlk approved these changes

2023-04-19 14:50 UTC, elzadj approved these changes

2023-04-19 14:53 UTC, merged