Fixes font-family with spaces
maxi-blocks/maxi-blocks pull request #4773
Opened 2023-04-26 12:07 UTC by Naaaaiix

# Description

As @elzadj noticed, the font families with a space in the middle (like `Exo 2` or `Slabo 27px`) weren't working on master; this implementation deals with it 👍 

# How Has This Been Tested?

On master, try setting that fonts into a Text Block and check the result. Also can check SC like `Wally`.
With this branch these fonts are working correctly 👍 

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type

**_ Pre-Code Testing _**

-   [ ] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

2023-04-26 12:58 UTC, Olekrut requested changes
if use SC ( Wally ) > font-family: undefined 
if pick font-family by manual > it is working

https://jam.dev/c/26c7c3d4-504d-479a-ae48-097c0fc93287

2023-04-27 08:38 UTC, Olekrut approved these changes

2023-04-27 09:58 UTC, Olekrut requested changes
![image](https://user-images.githubusercontent.com/88893350/234828950-391ea8c2-206e-4e37-95f5-3437e3dbe2d9.png)

2023-04-27 11:21 UTC, Olekrut requested changes
Should be Exo 2

![image](https://user-images.githubusercontent.com/88893350/234847291-17195a36-263a-4c9f-85cc-67bd7f764660.png)

2023-04-27 11:47 UTC, Olekrut approved these changes

2023-04-27 12:17 UTC, elzadj approved these changes

2023-04-27 12:28 UTC, merged