Issue 4642 - ACF DC integration
maxi-blocks/maxi-blocks pull request #4794
Opened 2023-04-28 17:13 UTC by myroslavve

# Description

Added ACF integration to DC.

Fixes part of #4642 

# How Has This Been Tested?
Before testing, you need to install ACF plugin.

Checked that ACF fields are selectable from text maxi, image maxi and button maxi,
here's how to create an ACF field and select it:

https://user-images.githubusercontent.com/53875005/235209772-8080f6f9-8ece-40ce-8baf-cd712c14adc9.mp4

# Test checklist

**_Front/Back Testing_**

-   [ ] Test text maxi, button maxi and image maxi acf integration.
-   [ ] Test blocks behaviour after acf plugin is disabled.
-   [ ] Check that only suitable acf fields are available in blocks (for example, only image field should appear in image maxi)
-   [ ] Check frontend.

**_Pre-Code Testing_**

-   [ ] Test text maxi, button maxi and image maxi acf integration.
-   [ ] Test blocks behaviour after acf plugin is disabled.
-   [ ] Check that only suitable acf fields are available in blocks (for example, only image field should appear in image maxi)
-   [ ] Check frontend.
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [x] New and existing unit tests pass locally with my changes

2023-05-02 19:34 UTC, Olekrut requested changes
have checked 15 points
working only 2 of 15
![image](https://user-images.githubusercontent.com/88893350/235765131-b6c49b4e-e289-4d46-a3fc-9855d3ea5fa0.png)
some of them is not displaying in list
![image](https://user-images.githubusercontent.com/88893350/235767298-47a6cfc5-0755-4843-ae10-edfcdf1fbb5e.png)

2023-05-12 16:25 UTC, Olekrut approved these changes

2023-05-26 09:42 UTC, elzadj approved these changes
Approved, but would be great if @Naaaaiix review it too. It's a big one.

2023-05-26 10:30 UTC, Naaaaiix reviewed
Good implementation, let's see if we what I share can improve the code quality and prevent some future issues 😸 

I think the API implementation is not necessary. ACF has it's own API where we can ping, but also we've got 2 others easier ways to GET and POST ACF information: the first, the well-known `getEntityRecords` that can directly remove the implementation done in the Maxi API; the second, which I consider even better, is to use the `acf` native package that can be used on backend. Here's the [ACF API for JS](https://www.advancedcustomfields.com/resources/javascript-api/). At the same time, this API contents some methods we already implemented. 

My suggestion: replace as much of our code by native WP/ACF methods. The reason is easy: they have better tools for these technologies than us, as its their product. Don't reinvent the wheel and use things supported by native technologies will mean less issues in future, lighter implementations and easier methods to keep growing and scaling the job.

Let's have a look with this perspective and once decided if we go with it or not, I'll check the rest of the PR and the implementation. Thanks 😸

2023-06-08 15:54 UTC, elzadj approved these changes

2023-06-08 15:54 UTC, merged