Issue 4774 - Changed image wrapper height from inherit to 100%
maxi-blocks/maxi-blocks pull request #4914
Opened 2023-06-12 09:47 UTC by Marko64

As the title says I changed the image wrapper height from inherit to 100%.

Did this because setting image height using the `%` didn't work as it didn't have any value to inherit from. 
![image](https://github.com/maxi-blocks/maxi-blocks/assets/19425503/70b5c2ba-2763-4cbc-b102-e844d42cda82)

See the example in the issue.

Fixes #4774 

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test image height and combine with the canvas height, make sure it works as expected.
-   [ ] Load a few patterns from the library and make sure images look good.

**_ Pre-Code Testing _**

-   [ ] Test image height and combine with the canvas height, make sure it works as expected.
-   [ ] Load a few patterns from the library and make sure images look good.
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

2023-06-12 17:57 UTC, Olekrut requested changes
https://jam.dev/c/1ad25ef4-6184-4e11-b928-00876fba1d65
1) frontend and backend dont match
2) in this case need to add margin for alignment, but as i understand we don't have image`s margins  for some reason?

2023-06-13 12:15 UTC, Olekrut requested changes
1) Check frontend and backend without margins
2) check how margins influence to backend and frontend

https://jam.dev/c/fc1bb4f2-3151-4fc1-a34a-08569f1b0fe2

2023-06-13 15:49 UTC, Olekrut approved these changes

2023-06-14 19:31 UTC, darimshlk approved these changes

2023-06-19 14:05 UTC, elzadj approved these changes

2023-06-19 14:26 UTC, merged