Issue 4862 - Disallowed new bg layer on hover
maxi-blocks/maxi-blocks pull request #4915
Opened 2023-06-12 09:59 UTC by Marko64

Fixes #4862

**_ Front/Back Testing _**

-   [ ] Check that you can't new bg layer on the hover tab.

**_ Pre-Code Testing _**

-   [ ] Check that you can't new bg layer on the hover tab.
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

2023-06-12 16:32 UTC, darimshlk approved these changes

2023-06-12 17:19 UTC, Olekrut requested changes
https://jam.dev/c/c36568d2-7b19-4d32-9231-49b91a72889a
is not fixed and errors are appearing

2023-06-13 11:50 UTC, Olekrut approved these changes
weird, cant re-produce anymore

2023-06-14 08:32 UTC, elzadj approved these changes
Approved, but we are waiting for attributes optimization before merging. Will re-evaluate on Friday.

2023-06-14 12:47 UTC, merged