Issue 4890 - Scroll effects position to transform
maxi-blocks/maxi-blocks pull request #4919
Opened 2023-06-14 12:16 UTC by Marko64

- Changed horizontal and vertical scroll effects to use the `transform` property instead of `position`. 

Fixes #4890 

**_ Front/Back Testing _**

-   [x] Test that horizontal, vertical and rotate scroll effects work well. Test them individually and together. Check the CSS that's rendered.

**_ Pre-Code Testing _**

-   [x] Test that horizontal, vertical and rotate scroll effects work well. Test them individually and together. Check the CSS that's rendered.
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

2023-06-14 20:21 UTC, Olekrut requested changes
Scroll transform overwrites transform for canvas
![image](https://github.com/maxi-blocks/maxi-blocks/assets/88893350/c91bc0ff-4100-43d4-bf7e-9be2c0a5038b)

2023-06-15 12:20 UTC, Olekrut approved these changes

2023-06-26 07:18 UTC, Fybex requested changes
We need migrator, I suppose. Created [code editor](https://github.com/maxi-blocks/maxi-blocks/files/11865421/position_to_transform.txt)on master and on switch to this branch, I have this:
![image](https://github.com/maxi-blocks/maxi-blocks/assets/46112160/edc730e6-5ef5-498d-876e-82e50bbbc73f)

Don't have much experience with scroll effects, but it looks like in previous versions `data-scroll-effect-horizontal-general` always had default start/end etc. zone values 🤔 So I'm not sure at all if we need this data attribute

2023-08-08 22:54 UTC, Olekrut approved these changes

2023-08-09 13:18 UTC, myroslavve approved these changes

2023-08-28 09:24 UTC, elzadj approved these changes

2023-08-28 09:24 UTC, merged