Issue 4717 - fix IB reset
maxi-blocks/maxi-blocks pull request #4929
Opened 2023-06-16 14:19 UTC by myroslavve

# Description
reset on IB didn't work at all for me, but after I fixed it couldn't reproduce the issue, seems fixed.

Fixes #4717

# How Has This Been Tested?
Checked that reset works right on IB.

# Test checklist

**_Front/Back Testing_**

-   [ ] Check that reset works right on IB

**_Pre-Code Testing_**

-   [ ] Check that reset works right on IB
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [x] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [x] New and existing unit tests pass locally with my changes

2023-06-19 09:44 UTC, Olekrut requested changes
https://jam.dev/c/1da06241-fb81-4a47-9dd7-94e95d2d877e
IB reset is not working for responsive

2023-06-20 13:50 UTC, Olekrut approved these changes

2023-06-20 16:06 UTC, Fybex approved these changes

2023-06-20 19:03 UTC, darimshlk approved these changes

2023-06-21 08:28 UTC, elzadj approved these changes

2023-06-21 08:28 UTC, merged