Issue 4880 - DC, CL. Add relations by category, author, tag
maxi-blocks/maxi-blocks pull request #4931
Opened 2023-06-19 14:46 UTC by Fybex

# Description

Fixes #4880 

[Updated CL schema](https://docs.google.com/drawings/d/1oC_rF3x-XyHLrTRAFd5aDm2KS-MA-o6rpJ6NUErcojI/edit)

# How Has This Been Tested?
Tested how relations by category, author, tag work with DC, CL on editor and frontend

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test the relations by category, author, tag with DC and CL
-   [ ] Check if the other options work as they did
-   [ ] Check that the settings work on frontend

**_ Pre-Code Testing _**

-   [ ] Test the relations by category, author, tag with DC and CL
-   [ ] Check if the other options work as they did
-   [ ] Check that the settings work on frontend
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [X] My code follows the style guidelines of this project
-   [X] I have performed a self-review of my code
-   [X] My changes generate no new warnings/errors

2023-06-20 13:36 UTC, Olekrut requested changes
https://jam.dev/c/55843354-93d0-4d98-91f5-0a7f76edb391
is not rendering tags, categories, and  iguess, with Authors the same

2023-06-21 09:33 UTC, Olekrut approved these changes

2023-06-22 17:30 UTC, myroslavve approved these changes

2023-06-23 09:12 UTC, elzadj requested changes
Something is not right on the frontend/php part, it shows a wrong post:

[screencast-bpconcjcammlapcogcnnelfmaeghhagj-2023.06.23-12_06_49.webm](https://github.com/maxi-blocks/maxi-blocks/assets/2401618/c33bec76-7140-4da4-a2ac-db490f8a7e3c)

The structure of the categories:

- Test cat 1
- - (sub-category) Test subcat 1
- Test Cat 2

Posts in order from new to old inside "Test subcat 1":

- TEST REMOVE BEFORE INDEX
- changed post
- test post 134234234

Try to change the Accumulator value.

2023-06-26 09:57 UTC, elzadj approved these changes
Just one small thing, and we can merge @Fybex

2023-06-26 10:12 UTC, elzadj approved these changes

2023-06-26 11:32 UTC, merged