Issue 4746 - IB unit bugs
maxi-blocks/maxi-blocks pull request #4932
Opened 2023-06-21 09:16 UTC by myroslavve

# Description

Fixes #4746

# How Has This Been Tested?
Checked that bugs from the issue are fixed.

# Test checklist

**_ Front/Back Testing _**

-   [x] Test the component in normal state in sidebar
-   [x] Test the component in hover state in sidebar (if hover exists)
-   [x] Check that the settings work on frontend
-   [x] Check that backend works and saves the settings after the editor reload
-   [x] Same 1-4 points for the toolbar
-   [x] Same 1-4 points on responsive
-   [x] Test the block inside the grid (Container + Row + Column)
-   [x] Test the block as a standalone block
-   [x] Duplicate the block, test that the settings of the first do not affect the second
-   [x] Test with 2 blocks of the same type

**_ Pre-Code Testing _**

-   [ ] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [x] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [x] New and existing unit tests pass locally with my changes

2023-06-21 10:53 UTC, Olekrut requested changes
https://jam.dev/c/016a6f70-67be-4461-b735-71592f18b5a0

2023-06-23 09:14 UTC, Olekrut requested changes
https://jam.dev/c/26e73532-7942-41d5-8718-6d9a53cd17a6
[ib bug.txt](https://github.com/maxi-blocks/maxi-blocks/files/11846785/ib.bug.txt)

2023-06-27 18:41 UTC, Olekrut approved these changes

2023-06-28 18:10 UTC, darimshlk approved these changes

2023-07-04 10:44 UTC, Fybex approved these changes

2023-07-04 11:07 UTC, elzadj approved these changes

2023-07-04 12:02 UTC, merged