Issue 4936 - marker size migrator
maxi-blocks/maxi-blocks pull request #4938
Opened 2023-06-27 15:05 UTC by myroslavve

# Description
Added migrator that removes height and width that were saved in SVG content string.

Fixes #4936 

# How Has This Been Tested?
Checked that marker size on PTL-02 can be changed.

# Test checklist

**_ Front/Back Testing _**

-   [x] Check that marker size on PTL-02 or any other pattern with markers can be changed.

**_ Pre-Code Testing _**

-   [x] Check that marker size on PTL-02 or any other pattern with markers can be changed.
-   [x] Check no commented code and no unnecessary imports
-   [x] Standards of the project have been followed
-   [x] No errors/warnings on console

# Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [x] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [x] New and existing unit tests pass locally with my changes

2023-06-27 20:49 UTC, Olekrut approved these changes

2023-06-28 12:13 UTC, Fybex requested changes

2023-06-28 19:47 UTC, darimshlk approved these changes

2023-06-29 08:32 UTC, Fybex approved these changes

2023-06-29 09:17 UTC, elzadj approved these changes
Just one small change @TeksPeks 
Thanks!

2023-06-29 09:34 UTC, merged