Issue 4875 - typography colors on responsive
maxi-blocks/maxi-blocks pull request #4939
Opened 2023-06-27 16:07 UTC by myroslavve

# Description
Opacity wasn't working on XXL for colors that were the same as on general,
fixed that.

Fixes #4875 

# How Has This Been Tested?
Checked that when palette colors on general and XXL are the same opacity can be changed on XXL.

# Test checklist

**_Front/Back Testing_**

-   [x] Check that when palette colors on general and XXL are the same opacity can be changed on XXL.

**_Pre-Code Testing_**

-   [x] Check that when palette colors on general and XXL are the same opacity can be changed on XXL.
-   [x] Check no commented code and no unnecessary imports
-   [x] Standards of the project have been followed
-   [x] No errors/warnings on console

# Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [x] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [x] New and existing unit tests pass locally with my changes

2023-06-27 20:36 UTC, Olekrut requested changes
[warning.txt](https://github.com/maxi-blocks/maxi-blocks/files/11887011/warning.txt)
![image](https://github.com/maxi-blocks/maxi-blocks/assets/88893350/6d7ea73f-731d-4829-a269-dd7c77a8a1e2)

2023-06-28 11:42 UTC, Olekrut approved these changes

2023-06-28 12:20 UTC, Fybex approved these changes

2023-06-28 12:21 UTC, Fybex requested changes
Tests are failing, looks like a lot of redundant css was added, bc now we're using `getLastBreakpointAttribute`, shouldn't be like this

2023-06-29 10:09 UTC, Fybex approved these changes

2023-07-12 09:11 UTC, merged