Issue 4796 - IB BG transitions
maxi-blocks/maxi-blocks pull request #4950
Opened 2023-07-03 08:51 UTC by myroslavve

# Description

Fixed transition problem on IB frontend, added migrator.
Also fixed error when removing container with IB triggers inside.

Fixes #4796
Resolves https://github.com/maxi-blocks/maxi-blocks/issues/4945

# How Has This Been Tested?
Checked that issue is fixed, inserted [BG Layers IB.txt](https://github.com/maxi-blocks/maxi-blocks/files/11364536/BG.Layers.IB.txt) and checked that it is migrated and works right.
Checked that editor doesn't break when removing container from the pattern.

# Test checklist

**_Front/Back Testing_**

-   [x] Check that the transition issue is fixed.
-   [x] insert [BG Layers IB.txt](https://github.com/maxi-blocks/maxi-blocks/files/11364536/BG.Layers.IB.txt) and check that it is migrated and works right
-   [x] Check that editor doesn't break when removing the container from the pattern.

**_Pre-Code Testing_**

-   [x] Check that the transition issue is fixed.
-   [x] insert [BG Layers IB.txt](https://github.com/maxi-blocks/maxi-blocks/files/11364536/BG.Layers.IB.txt) and check that it is migrated and works right
-   [x] Check that editor doesn't break when removing the container from the pattern.
-   [x] Check no commented code and no unnecessary imports
-   [x] Standards of the project have been followed
-   [x] No errors/warnings on console

# Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [x] New and existing unit tests pass locally with my changes

2023-07-11 12:46 UTC, Olekrut requested changes
Bug with transition is not fixed, 
bug with removing is fixed

2023-07-12 09:58 UTC, Olekrut requested changes
https://devdemo.maxiblocks.com/hero-light-hol-pro-part-6/
#53
[hol-pro-53.txt](https://github.com/maxi-blocks/maxi-blocks/files/12026511/hol-pro-53.txt)
Check with existed pattern
is not working with it
is need a migrator?

2023-07-13 10:27 UTC, Olekrut approved these changes

2023-07-13 13:23 UTC, Fybex approved these changes
LGTM

2023-07-17 12:24 UTC, elzadj approved these changes

2023-07-17 13:22 UTC, Olekrut approved these changes

2023-07-17 13:55 UTC, merged