Issue 4848 - BG gradient opacity reset
maxi-blocks/maxi-blocks pull request #4954
Opened 2023-07-03 12:56 UTC by Marko64

Set opacity to reset to 1, that's our default everywhere, but not sure if this is the best way to do it.
Fixes #4848 

**_ Front/Back Testing _**

-   [ ] Add a container or a group and add gradient bg. Try resetting - it should reset to 100 and the bg should be visible.  On master the value was 100 but bg was hidden.

-   [ ] Add a container or a group and add gradient bg. Try resetting - it should reset to 100 and the bg should be visible.  On master the value was 100 but bg was hidden.

-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

2023-07-04 07:47 UTC, Olekrut approved these changes

2023-07-04 12:47 UTC, darimshlk approved these changes

2023-07-04 14:25 UTC, myroslavve requested changes
Shared possible solution without resetting to 1 below.

2023-07-05 12:15 UTC, myroslavve approved these changes

2023-07-06 09:00 UTC, elzadj requested changes
From the tests: ```"background-palette-status-general-hover": true,```

That doesn't look right, check how ```cleaned = true``` for ```getIsValid``` affects it.

2023-08-01 09:47 UTC, elzadj approved these changes

2023-08-01 09:47 UTC, merged