Issue 4946 - DC link for context loop blocks
maxi-blocks/maxi-blocks pull request #4961
Opened 2023-07-06 08:41 UTC by myroslavve

# Description
Added ability to use DC link on blocks that have context loop.
Added context loop to slide and pane maxi.

Fixes #4946

# How Has This Been Tested?
Checked that DC link can be added on blocks with CL enabled.

# Test checklist

**_Front/Back Testing_**

-   [x] Check that DC link can be added on blocks with CL enabled.
-   [x] Check that context loop works on slide and pane maxi.
-   [x] Check that the settings work on frontend
-   [x] Check that backend works and saves the settings after the editor reload

**_Pre-Code Testing_**

-   [x] Check that DC link can be added on blocks with CL enabled.
-   [x] Check that context loop works on slide and pane maxi.
-   [x] Check that the settings work on frontend
-   [x] Check that backend works and saves the settings after the editor reload
-   [x] Check no commented code and no unnecessary imports
-   [x] Standards of the project have been followed
-   [x] No errors/warnings on console

# Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [x] New and existing unit tests pass locally with my changes

2023-07-06 13:39 UTC, Olekrut requested changes
1) DC link influence to inside blok`s styles
https://jam.dev/c/6b14d1ec-b2c7-4c80-b392-7d81b9f0474a
2) linnk is adding to parent and to child entire blocks as well/
frontend: link is working only for child, but it was not added there
https://jam.dev/c/f7a8d8a6-0f55-4846-9ea1-565fffa8ec0a
3) Context loop auto accumulation is not working with slider, between slides,
the same with accordion and panes ( maybe another issue? )
4) Cant use DC for accordion's title ( maybe need new issue? ) 
![image](https://github.com/maxi-blocks/maxi-blocks/assets/88893350/81a4db0e-4e72-4b40-96da-fe8d0309849d)

5) need DC link for author as well (as like for Cat and Tags. I guess, it should have been added here https://github.com/maxi-blocks/maxi-blocks/pull/4923,, but maybe you can add in this PR, or need to create new issue?

2023-07-10 17:47 UTC, Olekrut requested changes
Pane`s DC links are not working 
https://jam.dev/c/f6844e98-67df-475e-a067-aefeb6cbeb34

2023-07-11 08:42 UTC, Olekrut approved these changes

2023-07-13 13:19 UTC, Fybex requested changes

2023-07-14 09:39 UTC, Fybex approved these changes

2023-07-17 11:08 UTC, elzadj approved these changes

2023-07-17 11:08 UTC, merged