Issue 4976 - fix visited links colour for custom formats
maxi-blocks/maxi-blocks pull request #4977
Opened 2023-07-13 13:09 UTC by myroslavve

# Description
Removed the css that caused the problem. Didn't find any problems. 

Fixes #4976

# How Has This Been Tested?
Checked visited colour in chrome, Firefox on frontend and editor.

# Test checklist

**_Front/Back Testing_**

-   [x] Check that visited links on editor have non-visited colour.
-   [x] Check that visited links colour on frontend is right.
-   [ ] Test the above points in Firefox.

**_Pre-Code Testing_**

-   [x] Check that visited links on editor have non-visited colour.
-   [x] Check that visited links colour on frontend is right.
-   [x] Test the above points in Firefox, Safari.
-   [x] Check no commented code and no unnecessary imports
-   [x] Standards of the project have been followed
-   [x] No errors/warnings on console

# Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [x] New and existing unit tests pass locally with my changes

2023-07-17 13:05 UTC, Olekrut requested changes
FF

https://github.com/maxi-blocks/maxi-blocks/assets/88893350/6f268649-a0b7-47ac-b55f-a31aefaf9504

Check transition for hover with visited colour

2023-07-18 14:29 UTC, Olekrut approved these changes

2023-07-21 07:24 UTC, Fybex approved these changes

2023-07-24 10:12 UTC, elzadj approved these changes

2023-07-24 10:12 UTC, merged