Issue 4899 - fix toolbar indent/outdent not working properly
maxi-blocks/maxi-blocks pull request #4983
Opened 2023-07-20 08:59 UTC by myroslavve

# Description
Checked the large styles, they are added on purpose, and what they do is add width for markers of different levels in ordered lists, so since `ol`s have markers like `1 > 1.1 > 1.1.1 > ...` they need different width, it is hard to check how many levels lists have, so they are just statically generated.

Fixed the indent problem that Sasha has shared on the issue.

Fixes #4899 

# How Has This Been Tested?
Checked that the issue with indenting lists in toolbar is fixed.

# Test checklist

**_Front/Back Testing_**

-   [ ] Check that the issue with indenting lists in toolbar is fixed.

**_Pre-Code Testing_**

-   [x] Check that the issue with indenting lists in toolbar is fixed.
-   [x] Check no commented code and no unnecessary imports
-   [x] Standards of the project have been followed
-   [x] No errors/warnings on console

# Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [x] New and existing unit tests pass locally with my changes

2023-07-23 09:56 UTC, Olekrut requested changes
1) left problem with style.css
![image](https://github.com/maxi-blocks/maxi-blocks/assets/88893350/5049b5a1-a8bd-4097-a218-11d0f6e8987c)
2) https://jam.dev/c/0b45ffde-3d41-4192-8f4a-f1d652734141
the same list numbers in this case
3) not sure, but i guess, need a migrator
we don't have problem with pattern like it 
but maybe somebody has...
https://jam.dev/c/bc53f6f3-b560-41b1-8b22-fac9f135405a

2023-07-24 15:34 UTC, Olekrut requested changes
1) https://jam.dev/c/20058376-6afb-4093-8308-514ab5f7adbb
weird behavior with list`s levels
2) maybe need a new issue?
I guess, need a value for changing this padding
![image](https://github.com/maxi-blocks/maxi-blocks/assets/88893350/b63b3d35-490b-4444-89a5-166b1d6b3b8b)

2023-07-26 11:35 UTC, Olekrut approved these changes

2023-07-26 16:43 UTC, Fybex approved these changes

2023-07-27 08:37 UTC, elzadj approved these changes

2023-07-27 08:37 UTC, merged