Issue 4984 - WP 6.3-RC3 bugs
maxi-blocks/maxi-blocks pull request #4986
Opened 2023-07-24 09:31 UTC by myroslavve

# Description
Fixed the bugs from the issue. There is a problem with links settings UI, will fix it in #4985.

Fixes #4984 

# How Has This Been Tested?
Checked that bugs that Sasha's shared on the issue have been fixed.

# Test checklist

**_Front/Back Testing_**

-   [x] Check that the bugs from the issue are fixed.
-   [ ] Check that everything works right on current version of WordPress.

**_Pre-Code Testing_**

-   [ ] Check that the bugs from the issue are fixed.
-   [ ] Check that everything works right on current version of WordPress.
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [x] New and existing unit tests pass locally with my changes

2023-07-24 16:48 UTC, Olekrut requested changes
1) Can't pick anything inside column (old pages) 
https://jam.dev/c/229bcc65-2a8c-4540-ace6-50fdbe5c0fd0
2) not sure, looks like Maxi get slower

2023-07-31 18:18 UTC, Olekrut requested changes
1) https://jam.dev/c/03056747-a288-4360-b41b-cd7c3c18adfb
smth weird with IB

2) IB is working for Homepage, but not for 404 page or blog page, etc

2023-08-03 10:48 UTC, Olekrut approved these changes

2023-08-03 11:22 UTC, Marko64 approved these changes

2023-08-03 12:24 UTC, Fybex requested changes

2023-08-03 12:39 UTC, darimshlk approved these changes

2023-08-03 14:10 UTC, Fybex approved these changes

2023-08-04 09:52 UTC, elzadj requested changes
> Seems like performance issue to me, was loading for me but very long. Optimized maxi on FSE which hopefully will help, check again please.

Works much, much faster, great job! 

But I can't open the top toolbar now: 

![screenshot-wordpress local-2023 08 04-12_51_50](https://github.com/maxi-blocks/maxi-blocks/assets/2401618/43e55059-5845-4edb-ae6a-362a4a5a8315)

2023-08-04 11:47 UTC, elzadj approved these changes

2023-08-04 11:48 UTC, merged