Issue 4996 - Experimental settings translation to PHP
maxi-blocks/maxi-blocks pull request #5001
Opened 2023-08-01 15:08 UTC by Fybex

# Description

Fixes #4996 

# How Has This Been Tested?

https://github.com/maxi-blocks/maxi-blocks/assets/46112160/b74f5f70-fa51-4dff-872b-3fe355ac8e43

So on master when user changes toggle, font changes will apply only for pages which were updated after toggle change. On this branch, after enabling Affect native blocks toggle, it will automatically add needed fonts.

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test the case from video
-   [ ] Try to find any other problems with styles/fonts of native blocks(which are affected by SC toggle)
-   [ ] Test if Affect native blocks toggle still works as expected

**_ Pre-Code Testing _**

-   [ ] Test the case from video
-   [ ] Try to find any other problems with styles/fonts of native blocks(which are affected by SC toggle)
-   [ ] Test if Affect native blocks toggle still works as expected
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [X] My code follows the style guidelines of this project
-   [X] I have performed a self-review of my code
-   [X] My changes generate no new warnings/errors

2023-08-08 20:30 UTC, Olekrut requested changes
1) hmm,.. For changing Gutenberg's blocks, we can use only SC. and it is not cool, because it influences to all site’s blocks, will be need to overwrite it.
if it is possible, would be good, awesome, wonderful, to make toggle button, which will change  SC only for Gutenberg's blocks
2) 
![image](https://github.com/maxi-blocks/maxi-blocks/assets/88893350/df0977af-57f5-446f-aded-741919dedcd4)
3) 
![image](https://github.com/maxi-blocks/maxi-blocks/assets/88893350/974b8ba1-59f1-44b4-8e07-0c4ccbdfbeb9)
is not too big?

Only this PR
are these problems resolved in another PR?
4)
![image](https://github.com/maxi-blocks/maxi-blocks/assets/88893350/12068145-7212-49f5-ac78-98fc6e98915d)
5) https://jam.dev/c/627b7d27-5d54-4187-b773-04d9a060873c
bug with duplicating

2023-08-10 13:12 UTC, Olekrut approved these changes

2023-08-10 13:54 UTC, elzadj approved these changes

2023-08-10 14:18 UTC, myroslavve approved these changes

2023-08-10 14:44 UTC, merged