Issue 5000 - Fix container indicators
maxi-blocks/maxi-blocks pull request #5005
Opened 2023-08-03 14:34 UTC by Fybex

# Description

Fixes #5000 

# How Has This Been Tested?

# Test checklist

**_ Front/Back Testing _**

- [ ] Check if the video problem has disappeared, if container indicators work and look like expected

**_ Pre-Code Testing _**

- [x] Check if the video problem has disappeared, if container indicators work and look like expected
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [X] My code follows the style guidelines of this project
-   [X] I have performed a self-review of my code
-   [X] My changes generate no new warnings/errors

2023-08-03 14:50 UTC, Marko64 approved these changes

2023-08-03 19:04 UTC, Olekrut requested changes
Looks ok for new containers, but can you check PTML-PRO-60 ( Margin indicators )
![image](https://github.com/maxi-blocks/maxi-blocks/assets/88893350/9226dcc2-55d6-4450-b34f-5deebcb9fd85)

2023-08-04 19:42 UTC, Olekrut approved these changes

2023-08-04 20:36 UTC, darimshlk approved these changes

2023-08-07 08:23 UTC, myroslavve approved these changes

2023-08-07 08:45 UTC, elzadj approved these changes

2023-08-07 08:45 UTC, merged