Issue 4985 - LinkControl fix for WP 6.3
maxi-blocks/maxi-blocks pull request #5008
Opened 2023-08-04 18:12 UTC by Fybex

# Description

Fixes #4985 

# How Has This Been Tested?
Checked if link component is working for text-maxi, group-maxi and other blocks with 6.2.2 and 6.3 WP versions

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test if it's working on WP 6.2 with different blocks!(important! test it with text-maxi and some other blocks, their components are different)
-   [ ] Test if it's working on WP 6.3 with different blocks!(important! test it with text-maxi and some other blocks, their components are different)

**_ Pre-Code Testing _**

-   [ ] Test if it's working on WP 6.2 with different blocks!(important! test it with text-maxi and some other blocks, their components are different)
-   [ ] Test if it's working on WP 6.3 with different blocks!(important! test it with text-maxi and some other blocks, their components are different)
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [X] My code follows the style guidelines of this project
-   [X] I have performed a self-review of my code
-   [X] I have commented my code, particularly in hard-to-understand areas
-   [X] My changes generate no new warnings/errors

2023-08-08 21:25 UTC, Olekrut requested changes
it should be fixed as i understand
![image](https://github.com/maxi-blocks/maxi-blocks/assets/88893350/99bd85c0-bed6-44f0-a4ff-984c047c0e47)

2023-08-10 09:48 UTC, Olekrut approved these changes

2023-08-10 13:37 UTC, myroslavve approved these changes

2023-08-10 14:34 UTC, elzadj approved these changes

2023-08-11 09:59 UTC, merged