issue-451
maxi-blocks/maxi-blocks pull request #542
Opened 2020-09-30 15:43 UTC by abder

This PR aims to fix the issue mentioned in #451

2020-10-01 06:29 UTC, javadsamiee approved these changes
Good job 👍

2020-10-01 11:31 UTC, Naaaaiix reviewed
As I understood #451, the plan was to hide the column pattern from the Toolbar when the big pattern selector is on the center of the block for first time; @javadsamiee correct me if I'm wrong.

Another bug found, maybe not related with the issue and the PR, is that if I modify the pattern using the handlers doesn't deactivate the active status, so the pattern selected doesn't fit with the pattern 👍

2020-10-01 15:13 UTC, Naaaaiix approved these changes
Perfect, merging! 👍 Good job men

2020-10-01 15:14 UTC, Naaaaiix requested changes

2020-10-02 07:25 UTC, Naaaaiix approved these changes

2020-10-02 07:25 UTC, merged