Issue 750
maxi-blocks/maxi-blocks pull request #757
Opened 2020-12-15 06:45 UTC by javadsamiee

Some fixes

2020-12-15 08:24 UTC, elzadj approved these changes
Tested, works. Thanks, @javadsamiee !

2020-12-15 14:18 UTC, Naaaaiix requested changes

2020-12-17 16:06 UTC, Naaaaiix approved these changes

2020-12-18 08:18 UTC, Naaaaiix approved these changes
Cool! 😄

2020-12-28 09:56 UTC, Naaaaiix approved these changes
Cool! Good job @javadsamiee 💪

2020-12-28 09:56 UTC, merged