Issue 772
maxi-blocks/maxi-blocks pull request #775
Opened 2020-12-17 14:11 UTC by javadsamiee

Remove icon block

2020-12-17 14:29 UTC, elzadj requested changes
@javadsamiee please remove /src/extensions/attributes/index.js line 29 and /src/extensions/dom/index.js line 33
And maybe do a search in files with 'icon-maxi', just in case we have it somewhere else too.

2020-12-17 16:15 UTC, Naaaaiix approved these changes
Goooodbyyyy Icon!

2020-12-18 08:17 UTC, Naaaaiix approved these changes
Thanks @javadsamiee ; update with master and we can merge if @elzadj approves also 😄

2020-12-18 08:56 UTC, elzadj approved these changes

2020-12-18 12:56 UTC, Naaaaiix approved these changes

2020-12-18 12:56 UTC, merged