Issue 785
maxi-blocks/maxi-blocks pull request #786
Opened 2020-12-21 10:38 UTC by javadsamiee

2020-12-21 12:26 UTC, elzadj requested changes
Looks like the box shadow does not work on frontend (backend is ok).

2020-12-22 08:46 UTC, elzadj requested changes
Works nicely, just one tiny change please - should be "Enable Box Shadow on Hover":
![Edit-Page-‹-DEV-Maxi-Blocks-—-WordPress (3)](https://user-images.githubusercontent.com/2401618/102868442-dced4680-4442-11eb-835c-4144225f1242.jpg)

2020-12-22 09:12 UTC, elzadj approved these changes

2020-12-23 10:36 UTC, Naaaaiix approved these changes
Good job! 👍 

Can you also fix the none button selected as default please:
<img width="316" alt="Captura de pantalla 2020-12-23 a las 11 35 43" src="https://user-images.githubusercontent.com/50477222/102987722-13929200-4513-11eb-9b8d-e3e9415013ed.png">

2021-01-05 09:39 UTC, Naaaaiix approved these changes

2021-01-05 09:39 UTC, merged