Issue 793
maxi-blocks/maxi-blocks pull request #798
Opened 2020-12-23 12:29 UTC by javadsamiee

some fixes

2020-12-28 08:29 UTC, elzadj approved these changes

2020-12-28 10:13 UTC, Naaaaiix requested changes
Not sure if this solution is fixing the issues; look what I'm finding:
1. On setting an image layer, the image appears twice.
2. If you generated a layer on other block, the same options are copied to the next one.
![Kapture 2020-12-28 at 11 13 03](https://user-images.githubusercontent.com/50477222/103207095-bb3a0680-48fd-11eb-98c6-4fb849dede61.gif)

2021-01-07 09:51 UTC, Naaaaiix requested changes
We are soooo close!

2021-01-07 10:21 UTC, Naaaaiix approved these changes
Cool! 😸

2021-01-07 10:21 UTC, merged