Issue 796
maxi-blocks/maxi-blocks pull request #800
Opened 2020-12-23 15:45 UTC by javadsamiee

Minor fix

2020-12-28 08:59 UTC, elzadj approved these changes

2020-12-28 10:40 UTC, Naaaaiix reviewed
Don't understand what has been done. When are we going to use the advanced options related with 'disableAdvanced' prop?
My suggestion on #796 is that, when border-style is 'none', the rest of options doesn't appear:
<img width="318" alt="Captura de pantalla 2020-12-28 a las 11 37 14" src="https://user-images.githubusercontent.com/50477222/103208651-7d3ee180-4901-11eb-82a9-800855f0d3ee.png">

2021-01-05 08:53 UTC, Naaaaiix requested changes
Cool, works good! But found this:
![Kapture 2021-01-05 at 09 52 28](https://user-images.githubusercontent.com/50477222/103625838-cadbcf80-4f3b-11eb-8509-1295de02c7f6.gif)

2021-01-07 09:00 UTC, Naaaaiix approved these changes
Oh yeah! That's right! 😄

2021-01-07 09:00 UTC, merged