Issue 794
maxi-blocks/maxi-blocks pull request #801
Opened 2020-12-24 06:46 UTC by javadsamiee

Minor fix

2020-12-28 08:21 UTC, elzadj requested changes
Remove the console.log pls

2020-12-28 10:03 UTC, Naaaaiix requested changes

2020-12-29 13:52 UTC, elzadj requested changes
Please test the column's width on frontend - it gets a wrong value.

2021-01-04 09:01 UTC, elzadj requested changes
I still see that bug with the columns' width on the frontend.

2021-01-27 08:56 UTC, closed without merging