Issue 828
maxi-blocks/maxi-blocks pull request #829
Opened 2021-01-15 14:56 UTC by javadsamiee

Some fixes

2021-01-18 10:16 UTC, Naaaaiix requested changes
For entrance animation I find this:
![Kapture 2021-01-18 at 11 04 48](https://user-images.githubusercontent.com/50477222/104901197-582c1480-597d-11eb-8a67-9fe20952b601.gif)

For motion:
![Kapture 2021-01-18 at 11 12 46](https://user-images.githubusercontent.com/50477222/104901851-33846c80-597e-11eb-99f3-a295a00cf9c6.gif)

2021-01-18 10:58 UTC, elzadj requested changes
Same issues as for @Naaaaiix 
I've made the Entrance Animation work on one image, not sure how tho. Seems absolutely random.

2021-01-20 14:27 UTC, Naaaaiix approved these changes
Works fantastic!

2021-01-27 08:38 UTC, elzadj approved these changes

2021-01-27 10:53 UTC, merged