SVG optimisation
maxi-blocks/maxi-blocks pull request #854
Opened 2021-02-02 10:09 UTC by javadsamiee

2021-02-02 11:10 UTC, elzadj requested changes
Great work!

2021-02-02 12:35 UTC, Naaaaiix requested changes
Great work!

2021-02-03 09:38 UTC, Naaaaiix approved these changes
Cool; I guess the error with the display has been derived to #858 , so for me it can be merged 👍 
Good job 🥳

2021-02-03 11:10 UTC, elzadj approved these changes

2021-02-03 13:19 UTC, merged