Fix Column Maxi gap
maxi-blocks/maxi-blocks pull request #893
Opened 2021-02-08 18:23 UTC by Naaaaiix

Code is kind of messy, needs a refactoring (someday lol)

2021-02-09 07:11 UTC, javadsamiee reviewed
Good job mab 👍🏻

2021-02-09 08:23 UTC, elzadj requested changes
I confirm the bug @javadsamiee found.

2021-02-15 11:23 UTC, elzadj requested changes
Much, much better

2021-02-15 11:46 UTC, elzadj approved these changes

2021-02-15 12:33 UTC, javadsamiee approved these changes

2021-02-15 15:09 UTC, merged