Issue #858
maxi-blocks/maxi-blocks pull request #902
Opened 2021-02-09 15:59 UTC by Naaaaiix

Fixes #858

2021-02-09 16:14 UTC, javadsamiee reviewed
I can see the error yet and also display don't work in the toolbar as well.

2021-02-10 08:16 UTC, elzadj requested changes
> I can see the error yet and also display don't work in the toolbar as well.

I confirm both bugs.

2021-02-10 10:23 UTC, javadsamiee approved these changes

2021-02-10 11:26 UTC, elzadj approved these changes

2021-02-10 11:48 UTC, merged