Issue 965
maxi-blocks/maxi-blocks pull request #967
Opened 2021-02-19 08:53 UTC by javadsamiee

Minor fix

I have checked the unit and preview problems those are working correctly, please check it on a new page and make sure for caching.

2021-02-19 11:13 UTC, elzadj requested changes
Motion effect Move - works

Scale - nope, I've also got this error when I've tried to remove it from an image block:
TypeError: Cannot read property '0' of undefined
    at MotionPreview (webpack-internal:///638:26)
    at je (react-dom.min.js:78)
    at qe (react-dom.min.js:89)
    at ph (react-dom.min.js:216)
    at lh (react-dom.min.js:126)
    at O (react-dom.min.js:121)
    at ze (react-dom.min.js:118)
    at react-dom.min.js:53
    at unstable_runWithPriority (react.min.js:26)
    at Ma (react-dom.min.js:52)
    
Rotate - nope (I've tried z-axis)
Skew - nope, same error as with Scale

2021-02-22 09:06 UTC, elzadj requested changes
Checked Skew - it still is not working for me. Can you please record a video of how you make each of the Motion Effects work on an Image? Thanks.

2021-02-22 09:42 UTC, elzadj approved these changes

2021-02-23 09:32 UTC, Naaaaiix approved these changes

2021-02-23 09:32 UTC, merged