Implement Copy, Paste and Special Paste
maxi-blocks/maxi-blocks pull request #971
Opened 2021-02-19 18:58 UTC by Naaaaiix

@javadsamiee please, use your magic and make it beautiful 😄 

Fixes #365

2021-02-22 07:55 UTC, javadsamiee approved these changes
Supper super sexy feature, I ❤️ it and hello to new component "CopyPaste" 😄 

I should use my special and hidden magics for this particular feature 💀

2021-02-22 09:11 UTC, elzadj approved these changes

2021-02-22 14:58 UTC, elzadj requested changes
Bye

2021-02-23 09:51 UTC, elzadj approved these changes
Great work! The Text Level is not copied, buuuut I'm not sure if we need to copy it. :thinking:

2021-02-23 09:57 UTC, merged