Restyle Copy & paste feature
maxi-blocks/maxi-blocks pull request #975
Opened 2021-02-22 13:19 UTC by javadsamiee

2021-02-22 14:56 UTC, elzadj requested changes

2021-02-22 15:00 UTC, Naaaaiix approved these changes
That's so beautiful! 😍 good job!

2021-02-22 15:45 UTC, Naaaaiix approved these changes
![](https://media.giphy.com/media/RLW9YEaSBfBMt79fm4/giphy.gif)

2021-02-23 09:52 UTC, elzadj approved these changes

2021-02-23 09:56 UTC, merged