Issue 988
maxi-blocks/maxi-blocks pull request #991
Opened 2021-02-23 12:56 UTC by javadsamiee

Fix hover problem

2021-02-23 13:25 UTC, elzadj requested changes
Bakend is ok now, but I still cannot disable the bg hover on frontend:

(also, do we have an issue about the image alignment not working on frontend?)

2021-02-23 16:07 UTC, Naaaaiix approved these changes

2021-02-24 08:01 UTC, elzadj approved these changes

2021-02-25 09:43 UTC, Alejandro9kgm approved these changes

2021-02-25 09:51 UTC, merged